CREATE TABLE [dbo].[CRS_GOVERNMENT] (
    [CLIN]              NVARCHAR (255) NULL,
    [DESCRIPTION]       NVARCHAR (255) NULL,
    [UNIT_PRICE]        MONEY          NULL,
    [UNIT_OF_ISSUE]     NVARCHAR (255) NULL,
    [TYPE_OR_UNIT_FEE]  NVARCHAR (255) NULL,
    [HEADER_CLIN]       NVARCHAR (255) NULL,
    [AREA]              NVARCHAR (255) NULL,
    [PERIOD]            NVARCHAR (255) NULL,
    [PERIOD_START_DATE] SMALLDATETIME  NULL,
    [PERIOD_END_DATE]   SMALLDATETIME  NULL
);

