CREATE TABLE [dbo].[ISExportData_484724609093299506$] (
    [RULE_NAMES]                       NVARCHAR (255) NULL,
    [ARCHIVE]                          NVARCHAR (255) NULL,
    [CENTRAL BLOCK]                    NVARCHAR (255) NULL,
    [NOT RELEASED]                     NVARCHAR (255) NULL,
    [DATA ORIGIN]                      FLOAT (53)     NULL,
    [CITY]                             NVARCHAR (255) NULL,
    [COUNTRY]                          NVARCHAR (255) NULL,
    [PO BOX]                           NVARCHAR (255) NULL,
    [PO BOX CITY]                      NVARCHAR (255) NULL,
    [PO BOX COUNTRY]                   NVARCHAR (255) NULL,
    [PO BOX POSTAL CODE]               NVARCHAR (255) NULL,
    [PO BOX REGION]                    NVARCHAR (255) NULL,
    [POSTAL CODE]                      NVARCHAR (255) NULL,
    [REGION]                           NVARCHAR (255) NULL,
    [STREET]                           NVARCHAR (255) NULL,
    [STREET2]                          NVARCHAR (255) NULL,
    [STREET4]                          NVARCHAR (255) NULL,
    [ADDRESS ID]                       FLOAT (53)     NULL,
    [COMMUNICATION LANGUAGE]           NVARCHAR (255) NULL,
    [CONCUR INDUSTRY VERTICAL SECTORS] NVARCHAR (255) NULL,
    [SIC]                              FLOAT (53)     NULL,
    [CRM ACCOUNT ID]                   FLOAT (53)     NULL,
    [CUSTOMER CATEGORY CODE]           NVARCHAR (255) NULL,
    [CUSTOMER CLASSIFICATION CODE]     NVARCHAR (255) NULL,
    [DUNS NUMBER]                      FLOAT (53)     NULL,
    [ERP ACCOUNT ID]                   FLOAT (53)     NULL,
    [METRANET REFERENCE ID]            FLOAT (53)     NULL,
    [ACCOUNT NAME]                     NVARCHAR (255) NULL,
    [ORACLE REFERENCE ID]              FLOAT (53)     NULL,
    [CONCUR ACCOUNT ID]                FLOAT (53)     NULL,
    [SALES CHANNEL CODE]               NVARCHAR (255) NULL,
    [SALESFORCE ACCOUNT ID]            NVARCHAR (255) NULL,
    [TAX ID / VAT]                     NVARCHAR (255) NULL,
    [TELEPHONE NUMBER]                 FLOAT (53)     NULL,
    [ORG URL]                          NVARCHAR (255) NULL,
    [ORG EMAIL]                        NVARCHAR (255) NULL,
    [TURNOVER / REVENUE (LOCAL)]       FLOAT (53)     NULL,
    [EMPLOYEES]                        FLOAT (53)     NULL,
    [SRC]                              FLOAT (53)     NULL,
    [CREATE_DATE]                      FLOAT (53)     NULL,
    [CREATE_BY]                        NVARCHAR (255) NULL,
    [CHANGE_DATE]                      FLOAT (53)     NULL,
    [CHANGE_BY]                        NVARCHAR (255) NULL,
    [CHANGED]                          NVARCHAR (255) NULL,
    [CREATE_TYPE]                      NVARCHAR (255) NULL,
    [ADDRESS TYPE]                     NVARCHAR (255) NULL,
    [TAX TYPE]                         NVARCHAR (255) NULL,
    [TAX JURISDICTION CODE]            FLOAT (53)     NULL,
    [ADDRESS VALID FROM]               NVARCHAR (255) NULL,
    [ADDRESS VALID TO]                 NVARCHAR (255) NULL,
    [CARE_OF_NAME]                     NVARCHAR (255) NULL,
    [F52]                              NVARCHAR (255) NULL
);

