CREATE TABLE [dbo].[Account_0809] (
    [Account_Manager__c]                          NVARCHAR (1300) NULL,
    [Account_Plan_Comments__c]                    NVARCHAR (255)  NULL,
    [AccountNumber]                               NVARCHAR (40)   NULL,
    [Accounts_Payable_Staff_Size__c]              DECIMAL (18)    NULL,
    [AccountStatus__c]                            NVARCHAR (255)  NULL,
    [Active_Users__c]                             DECIMAL (18)    NULL,
    [Actual_Air_Spend__c]                         DECIMAL (18)    NULL,
    [Actual_Expense_Report_Volume_Month__c]       DECIMAL (18)    NULL,
    [Actual_Launch_Date__c]                       DATETIME2 (7)   NULL,
    [Ad_Category__c]                              NVARCHAR (255)  NULL,
    [Additional_card_2__c]                        NVARCHAR (255)  NULL,
    [Additional_card__c]                          NVARCHAR (255)  NULL,
    [Additional_Expense_Comments__c]              NTEXT           NULL,
    [Additional_Invoice_Comments__c]              NTEXT           NULL,
    [Additional_Travel_Comments__c]               NTEXT           NULL,
    [Admin_Last_Login__c]                         DATETIME2 (7)   NULL,
    [Affiliate_Landing_Page__c]                   NVARCHAR (255)  NULL,
    [Agency_provided_ETS_Help_Desk_explanatio__c] NVARCHAR (255)  NULL,
    [Agency_provided_ETS_Help_Desk_s__c]          NVARCHAR (255)  NULL,
    [AM_Program__c]                               NVARCHAR (255)  NULL,
    [AM_Region__c]                                NVARCHAR (1300) NULL,
    [AM_Segment__c]                               NVARCHAR (1300) NULL,
    [Amex_AD_Region__c]                           NVARCHAR (255)  NULL,
    [Amex_Business_Unit_ID__c]                    NVARCHAR (18)   NULL,
    [Annual_Meetings__c]                          NVARCHAR (255)  NULL,
    [Annual_PNRs__c]                              DECIMAL (18)    NULL,
    [Annual_Revenue__c]                           DECIMAL (18, 2) NULL,
    [Annual_T_E_Spend__c]                         NVARCHAR (255)  NULL,
    [Annual_Vouchers__c]                          NVARCHAR (200)  NULL,
    [AnnualRevenue]                               DECIMAL (18)    NULL,
    [Assigned_Account_MDR2__c]                    NCHAR (18)      NULL,
    [Assigned_Account_MDR_Partner__c]             NCHAR (18)      NULL,
    [Audit_Method__c]                             NVARCHAR (255)  NULL,
    [BigMachines__Partner_Organization__c]        NVARCHAR (255)  NULL,
    [Billing_City__c]                             NVARCHAR (80)   NULL,
    [Billing_Contact__c]                          NCHAR (18)      NULL,
    [Billing_Country__c]                          NVARCHAR (255)  NULL,
    [Billing_County__c]                           NVARCHAR (80)   NULL,
    [Billing_Cycle__c]                            NVARCHAR (255)  NULL,
    [Billing_Email__c]                            NVARCHAR (80)   NULL,
    [Billing_First_Name__c]                       NVARCHAR (40)   NULL,
    [Billing_Geocode__c]                          NVARCHAR (140)  NULL,
    [Billing_Last_Name__c]                        NVARCHAR (80)   NULL,
    [Billing_St__c]                               NVARCHAR (140)  NULL,
    [Billing_St_Line_2__c]                        NVARCHAR (140)  NULL,
    [Billing_State_Province__c]                   NVARCHAR (60)   NULL,
    [Billing_Zip_Postal__c]                       NVARCHAR (40)   NULL,
    [BillingCity]                                 NVARCHAR (40)   NULL,
    [BillingCountry]                              NVARCHAR (80)   NULL,
    [BillingPostalCode]                           NVARCHAR (20)   NULL,
    [BillingState]                                NVARCHAR (80)   NULL,
    [BillingStreet]                               NVARCHAR (255)  NULL,
    [Brand_Awareness__c]                          NVARCHAR (255)  NULL,
    [Breeze_Account_Stage__c]                     NVARCHAR (255)  NULL,
    [Breeze_Channel__c]                           NVARCHAR (255)  NULL,
    [Breeze_CID__c]                               NVARCHAR (100)  NULL,
    [Breeze_Date_Stamp__c]                        DATETIME2 (7)   NULL,
    [Breeze_Date_Stamp_Preparation__c]            DATETIME2 (7)   NULL,
    [Breeze_Date_Stamp_Usage__c]                  DATETIME2 (7)   NULL,
    [Breeze_Last_CID__c]                          NVARCHAR (100)  NULL,
    [Breeze_Last_Lead_Source__c]                  NVARCHAR (100)  NULL,
    [Breeze_Lead_Source__c]                       NVARCHAR (100)  NULL,
    [Breeze_Referral_Received__c]                 NCHAR (18)      NULL,
    [Breeze_Referral_Sent__c]                     NCHAR (18)      NULL,
    [Breeze_Representative__c]                    NCHAR (18)      NULL,
    [Breeze_Survey_Received__c]                   DATETIME2 (7)   NULL,
    [Breeze_Survey_Sent__c]                       DATETIME2 (7)   NULL,
    [Breeze_Team__c]                              NVARCHAR (255)  NULL,
    [BSA_Region__c]                               NVARCHAR (255)  NULL,
    [BTA_Card__c]                                 NVARCHAR (255)  NULL,
    [Business_Focus__c]                           NTEXT           NULL,
    [Business_Focus_Other__c]                     NVARCHAR (40)   NULL,
    [Business_Type__c]                            NTEXT           NULL,
    [Business_Unit__c]                            NVARCHAR (255)  NULL,
    [Buying_Horizon__c]                           NVARCHAR (255)  NULL,
    [Card_to_Cash__c]                             DECIMAL (18, 2) NULL,
    [Categorization__c]                           NVARCHAR (255)  NULL,
    [CES_Reseller__c]                             NVARCHAR (255)  NULL,
    [Charge_Volume__c]                            DECIMAL (18)    NULL,
    [Client_Status__c]                            NVARCHAR (255)  NULL,
    [Cliqbook_Client__c]                          NVARCHAR (255)  NULL,
    [Cliqbook_Reseller__c]                        NVARCHAR (255)  NULL,
    [Closed_Lost_This_Year__c]                    DECIMAL (18, 2) NULL,
    [Closed_Won_This_Year__c]                     DECIMAL (18, 2) NULL,
    [Comments__c]                                 NTEXT           NULL,
    [Company_Created_Date__c]                     DATETIME2 (7)   NULL,
    [Company_Launch_Date__c]                      NVARCHAR (255)  NULL,
    [Company_was_Acquired__c]                     VARCHAR (5)     NULL,
    [Comparison_field__c]                         NVARCHAR (90)   NULL,
    [Contract__c]                                 NCHAR (18)      NULL,
    [Contract_Effective_Date__c]                  DATETIME2 (7)   NULL,
    [Contract_Expiration_Date__c]                 DATETIME2 (7)   NULL,
    [Contract_Renewal_Date__c]                    DATETIME2 (7)   NULL,
    [Contract_Status__c]                          NVARCHAR (255)  NULL,
    [Contract_Termination_Date__c]                DATETIME2 (7)   NULL,
    [Contracting_Entity__c]                       NVARCHAR (255)  NULL,
    [Core_Service_Transitioned__c]                DATETIME2 (7)   NULL,
    [Core_Solutions_Sold__c]                      NVARCHAR (255)  NULL,
    [Country_Scope__c]                            NVARCHAR (255)  NULL,
    [CreatedById]                                 NCHAR (18)      NULL,
    [CreatedDate]                                 DATETIME2 (7)   NOT NULL,
    [Credit_Comments__c]                          NVARCHAR (255)  NULL,
    [Credit_Status__c]                            NVARCHAR (255)  NULL,
    [CRM__c]                                      NVARCHAR (255)  NULL,
    [Curr_Booking_Method_Contract_Expiration__c]  NVARCHAR (12)   NULL,
    [CurrencyIsoCode]                             NVARCHAR (3)    NULL,
    [Current_Booking_Process__c]                  NVARCHAR (255)  NULL,
    [Current_Booking_Solution__c]                 NVARCHAR (255)  NULL,
    [Current_Expense_Contract_Expiration__c]      DATETIME2 (7)   NULL,
    [Current_Expense_Process__c]                  NVARCHAR (255)  NULL,
    [Current_Expense_Solution__c]                 NVARCHAR (255)  NULL,
    [Current_Expense_Solution_Other__c]           NVARCHAR (255)  NULL,
    [Current_Invoice_Process__c]                  NVARCHAR (255)  NULL,
    [Current_Invoice_Solution__c]                 NVARCHAR (255)  NULL,
    [Current_Purchase_Process__c]                 NVARCHAR (255)  NULL,
    [Current_T_E_Audit__c]                        NVARCHAR (255)  NULL,
    [Current_T_E_Solutions_Integrated__c]         NVARCHAR (255)  NULL,
    [Customer_Currency__c]                        NVARCHAR (255)  NULL,
    [Customer_Profile__c]                         NVARCHAR (255)  NULL,
    [Customer_Region__c]                          NVARCHAR (255)  NULL,
    [Customer_Since__c]                           DATETIME2 (7)   NULL,
    [Date_Company_Made_Reference__c]              DATETIME2 (7)   NULL,
    [DBA__c]                                      NVARCHAR (75)   NULL,
    [Deployed__c]                                 DECIMAL (18)    NULL,
    [Description]                                 NTEXT           NULL,
    [Do_Not_Call__c]                              VARCHAR (5)     NULL,
    [DunsParentAccount__c]                        NCHAR (18)      NULL,
    [DunsUltimateParentAccount__c]                NCHAR (18)      NULL,
    [Employee_Band_Worldwide__c]                  NVARCHAR (255)  NULL,
    [Employee_Growth__c]                          DECIMAL (18)    NULL,
    [Employee_Travel_Volume__c]                   NVARCHAR (255)  NULL,
    [Employees_at_Location__c]                    DECIMAL (18)    NULL,
    [Employees_Band__c]                           NVARCHAR (255)  NULL,
    [Employees_Worldwide__c]                      DECIMAL (18)    NULL,
    [Entity_ID__c]                                NVARCHAR (45)   NULL,
    [Est_of_Indirect_Invoices__c]                 DECIMAL (18)    NULL,
    [ETS1_Vendor__c]                              NVARCHAR (255)  NULL,
    [Expense_Pay__c]                              NVARCHAR (255)  NULL,
    [Expense_Pay_By_Concur__c]                    NVARCHAR (255)  NULL,
    [Expense_Report_Filers__c]                    DECIMAL (18)    NULL,
    [Expense_Report_Volume_Month__c]              NVARCHAR (255)  NULL,
    [Fax]                                         NVARCHAR (40)   NULL,
    [Financial_System__c]                         NVARCHAR (255)  NULL,
    [Financial_System_Other__c]                   NVARCHAR (255)  NULL,
    [Fiscal_Year_End__c]                          NVARCHAR (255)  NULL,
    [Formal_Corporate_Expense_Policy__c]          NVARCHAR (255)  NULL,
    [Fortune_500_Global_Rank__c]                  DECIMAL (18)    NULL,
    [Fortune_500_Public_Rank__c]                  DECIMAL (18)    NULL,
    [Fortune_Member__c]                           VARCHAR (5)     NULL,
    [Free_Trial_Days_Remaining__c]                DECIMAL (18)    NULL,
    [Free_Trial_Edition__c]                       NVARCHAR (255)  NULL,
    [Funding_Bank__c]                             NVARCHAR (50)   NULL,
    [Future_Expansion__c]                         NTEXT           NULL,
    [GCC_LOA_Print_Date__c]                       DATETIME2 (7)   NULL,
    [GDS__c]                                      NVARCHAR (255)  NULL,
    [GE_Client_ID__c]                             DECIMAL (18)    NULL,
    [GE_Client_Type__c]                           NVARCHAR (255)  NULL,
    [GE_Go_Live_Date__c]                          DATETIME2 (7)   NULL,
    [Gelco_Account_Id__c]                         NVARCHAR (18)   NULL,
    [Global_Parent_Account__c]                    NCHAR (18)      NULL,
    [global_parent_account_set__c]                VARCHAR (5)     NULL,
    [Global_Parent_DUNS__c]                       NVARCHAR (25)   NULL,
    [How_Pay_Expense_Reports__c]                  NVARCHAR (50)   NULL,
    [Id]                                          NCHAR (18)      NOT NULL,
    [Immediate_Parent_DUNS__c]                    NVARCHAR (25)   NULL,
    [Implementation_Status__c]                    NVARCHAR (255)  NULL,
    [Incumbent_TMC__c]                            NVARCHAR (255)  NULL,
    [Industry]                                    NVARCHAR (40)   NULL,
    [Industry_Sub_Type__c]                        NVARCHAR (255)  NULL,
    [Initiatives__c]                              NVARCHAR (255)  NULL,
    [Integration_Partner__c]                      NVARCHAR (255)  NULL,
    [Integration_Partnership_Details__c]          NTEXT           NULL,
    [International_Filers__c]                     VARCHAR (5)     NULL,
    [International_Opportunities__c]              VARCHAR (5)     NULL,
    [Invoice_Capture__c]                          NVARCHAR (255)  NULL,
    [Invoice_Language__c]                         NVARCHAR (255)  NULL,
    [Invoice_Pay__c]                              NVARCHAR (255)  NULL,
    [Invoice_Solution_Reseller__c]                NVARCHAR (255)  NULL,
    [Invoice_Volument_Month__c]                   NVARCHAR (255)  NULL,
    [IsCustomerPortal]                            VARCHAR (5)     NOT NULL,
    [IsDeleted]                                   VARCHAR (5)     NOT NULL,
    [IsPartner]                                   VARCHAR (5)     NOT NULL,
    [jsImpacts__Added_from_Data_com__c]           DECIMAL (18)    NULL,
    [jsImpacts__Data_com_does_not_auto_update__c] VARCHAR (5)     NULL,
    [jsImpacts__Data_com_Managed__c]              DECIMAL (18)    NULL,
    [Last_Credit_Update__c]                       DATETIME2 (7)   NULL,
    [LastActivityDate]                            DATETIME2 (7)   NULL,
    [LastModifiedById]                            NCHAR (18)      NULL,
    [LastModifiedDate]                            DATETIME2 (7)   NOT NULL,
    [Lead_Score__c]                               NVARCHAR (50)   NULL,
    [Lead_Source__c]                              NVARCHAR (255)  NULL,
    [Legacy_Service_Model__c]                     NVARCHAR (255)  NULL,
    [Market__c]                                   NVARCHAR (255)  NULL,
    [Marketing_Awareness__c]                      NVARCHAR (255)  NULL,
    [Marketing_Tier__c]                           NVARCHAR (255)  NULL,
    [Marketing_Tier_Travel__c]                    NVARCHAR (255)  NULL,
    [MasterRecordId]                              NCHAR (18)      NULL,
    [MD_Comments__c]                              NVARCHAR (255)  NULL,
    [MD_Date__c]                                  DATETIME2 (7)   NULL,
    [MDR_ID__c]                                   NVARCHAR (20)   NULL,
    [Meetings_Management_Tool__c]                 NVARCHAR (255)  NULL,
    [Member_Designation__c]                       NTEXT           NULL,
    [Member_ID__c]                                NVARCHAR (18)   NULL,
    [Member_Type__c]                              NVARCHAR (255)  NULL,
    [Mid_Office_System__c]                        NTEXT           NULL,
    [MN_Update_ID__c]                             NVARCHAR (40)   NULL,
    [Mobile_Device_used__c]                       NVARCHAR (255)  NULL,
    [Modified_Contract_Required__c]               VARCHAR (5)     NULL,
    [Multiple_Billing_Accounts__c]                VARCHAR (5)     NULL,
    [NAICS_Code__c]                               NVARCHAR (50)   NULL,
    [NAICS_Description__c]                        NVARCHAR (255)  NULL,
    [Name]                                        NVARCHAR (255)  NOT NULL,
    [Named_Account__c]                            VARCHAR (5)     NULL,
    [Nature_of_interfaces__c]                     NVARCHAR (255)  NULL,
    [Needs_Identified__c]                         NVARCHAR (50)   NULL,
    [New_Customer_Date_Time_Stamp__c]             DATETIME2 (7)   NULL,
    [Next_Steps__c]                               NTEXT           NULL,
    [Next_Steps_Due_Date__c]                      DATETIME2 (7)   NULL,
    [No_Of_CBA_s__c]                              DECIMAL (18)    NULL,
    [No_of_Financial_Systems__c]                  DECIMAL (18)    NULL,
    [No_of_Interfaces__c]                         DECIMAL (18)    NULL,
    [No_of_Reconciliation_Reports__c]             DECIMAL (18)    NULL,
    [No_of_Steady_State_Domestic_Tickets__c]      DECIMAL (18)    NULL,
    [No_of_Steady_State_INTL_Tickets__c]          DECIMAL (18)    NULL,
    [No_of_Steady_State_Local_Vouchers__c]        DECIMAL (18)    NULL,
    [No_of_Steady_State_TDY_Vouchers__c]          DECIMAL (18)    NULL,
    [Not_Engaged_Reason__c]                       NVARCHAR (255)  NULL,
    [Notes__c]                                    NTEXT           NULL,
    [Notice_Address_City__c]                      NVARCHAR (80)   NULL,
    [Notice_Address_Country__c]                   NVARCHAR (255)  NULL,
    [Notice_Address_County__c]                    NVARCHAR (80)   NULL,
    [Notice_Address_State__c]                     NVARCHAR (60)   NULL,
    [Notice_Address_Street_1__c]                  NVARCHAR (140)  NULL,
    [Notice_Address_Street_2__c]                  NVARCHAR (140)  NULL,
    [Notice_Address_Zip__c]                       NVARCHAR (40)   NULL,
    [Notice_Email__c]                             NVARCHAR (80)   NULL,
    [Notice_Fax__c]                               NVARCHAR (40)   NULL,
    [Notice_First_Name__c]                        NVARCHAR (40)   NULL,
    [Notice_Geocode__c]                           NVARCHAR (140)  NULL,
    [Notice_Last_Name__c]                         NVARCHAR (80)   NULL,
    [Notice_Telephone__c]                         NVARCHAR (40)   NULL,
    [Notify_on_Close__c]                          VARCHAR (5)     NULL,
    [Notify_on_Defects__c]                        VARCHAR (5)     NULL,
    [Notify_on_Status__c]                         VARCHAR (5)     NULL,
    [Number_Card_Holders__c]                      DECIMAL (18)    NULL,
    [Number_Cards_in_Force__c]                    DECIMAL (18)    NULL,
    [Number_of_Cards_Added__c]                    DECIMAL (18)    NULL,
    [Number_of_Exports__c]                        DECIMAL (18)    NULL,
    [Number_of_Mobile_Users__c]                   DECIMAL (18)    NULL,
    [Number_of_Travel_Configs__c]                 DECIMAL (18)    NULL,
    [Number_of_Travel_Sites__c]                   DECIMAL (18)    NULL,
    [Number_of_Travelers__c]                      NVARCHAR (255)  NULL,
    [Number_of_TripIt_Users__c]                   DECIMAL (18)    NULL,
    [Number_TripIt_Pro_Users__c]                  DECIMAL (18)    NULL,
    [NumberOfEmployees]                           INT             NULL,
    [OBT_adoption__c]                             DECIMAL (18)    NULL,
    [of_Non_PO_Based_Invoices__c]                 DECIMAL (18)    NULL,
    [of_PO_Based_Invoices__c]                     DECIMAL (18)    NULL,
    [Online_Booking_Tool__c]                      NVARCHAR (80)   NULL,
    [Open_Pipeline_This_Year__c]                  DECIMAL (18, 2) NULL,
    [Open_Won__c]                                 DECIMAL (18, 2) NULL,
    [Opportunities__c]                            DECIMAL (18)    NULL,
    [Opportunities_Lost__c]                       DECIMAL (18)    NULL,
    [Opportunities_Open__c]                       DECIMAL (18)    NULL,
    [Opportunities_Won__c]                        DECIMAL (18)    NULL,
    [Oracle_ID__c]                                NVARCHAR (45)   NULL,
    [OwnerId]                                     NCHAR (18)      NOT NULL,
    [Ownership]                                   NVARCHAR (40)   NULL,
    [P_Card__c]                                   NVARCHAR (255)  NULL,
    [ParentId]                                    NCHAR (18)      NULL,
    [Partner_Rep_1__c]                            NCHAR (18)      NULL,
    [Partner_Rep_1_Last_Updated__c]               DATETIME2 (7)   NULL,
    [Partner_Rep_2__c]                            NCHAR (18)      NULL,
    [Partner_Rep_2_Last_Updated__c]               DATETIME2 (7)   NULL,
    [Partner_Rep_3__c]                            NCHAR (18)      NULL,
    [Partner_Rep_3_Last_Updated__c]               DATETIME2 (7)   NULL,
    [Partner_Rep_4__c]                            NCHAR (18)      NULL,
    [Payee_Address__c]                            NVARCHAR (255)  NULL,
    [Payee_Name__c]                               NVARCHAR (100)  NULL,
    [Payment_Method__c]                           NVARCHAR (255)  NULL,
    [Payment_Terms__c]                            NVARCHAR (255)  NULL,
    [Payment_Type__c]                             NVARCHAR (255)  NULL,
    [Payroll__c]                                  NVARCHAR (255)  NULL,
    [Payroll_Provider__c]                         NVARCHAR (80)   NULL,
    [Phone]                                       NVARCHAR (40)   NULL,
    [PO_Number__c]                                NVARCHAR (30)   NULL,
    [PO_to_be_Issued__c]                          VARCHAR (5)     NULL,
    [Pre_Production__c]                           VARCHAR (5)     NULL,
    [Pre_Trip_Authorized__c]                      VARCHAR (5)     NULL,
    [Premier_Account__c]                          VARCHAR (5)     NULL,
    [Previous_Booking_Solution__c]                NVARCHAR (255)  NULL,
    [Previous_Cliqbook_Client_Type__c]            NVARCHAR (80)   NULL,
    [Previous_Expense_Solution__c]                NVARCHAR (255)  NULL,
    [Pricing_Promo_Rate__c]                       NVARCHAR (255)  NULL,
    [Primary_Card__c]                             NVARCHAR (255)  NULL,
    [Primary_Card_Expiration_Date__c]             DATETIME2 (7)   NULL,
    [Primary_Email_Domain__c]                     NVARCHAR (50)   NULL,
    [Pro_Enterprise_PNR_Price__c]                 DECIMAL (18, 2) NULL,
    [Pro_Reseller_Price__c]                       DECIMAL (18)    NULL,
    [Program_Type__c]                             NVARCHAR (255)  NULL,
    [Promo_Code__c]                               NVARCHAR (255)  NULL,
    [Qualified_Out_Reasons__c]                    NVARCHAR (255)  NULL,
    [Quarterly_Travel_Adoption__c]                DECIMAL (18)    NULL,
    [Rating]                                      NVARCHAR (40)   NULL,
    [Reassign_Owner_Reason__c]                    NVARCHAR (255)  NULL,
    [Receive__c]                                  NVARCHAR (255)  NULL,
    [RecordTypeId]                                NCHAR (18)      NULL,
    [Reference_Status__c]                         NVARCHAR (255)  NULL,
    [Reference_Status_Updated_by__c]              NVARCHAR (100)  NULL,
    [Referred_Revenue_ARR__c]                     DECIMAL (18)    NULL,
    [Referred_Revenue_CMMR__c]                    DECIMAL (18)    NULL,
    [Region__c]                                   NVARCHAR (255)  NULL,
    [Reimbursement_Method__c]                     NVARCHAR (255)  NULL,
    [Remove_from_Nuturing__c]                     NVARCHAR (255)  NULL,
    [Report_Analytic__c]                          NVARCHAR (255)  NULL,
    [Reports_Submitted__c]                        DECIMAL (18)    NULL,
    [Retain_Segmentation__c]                      VARCHAR (5)     NULL,
    [Revenue_Group__c]                            NVARCHAR (255)  NULL,
    [rrpu__Alert_Message__c]                      NVARCHAR (255)  NULL,
    [Sales_Executive__c]                          NVARCHAR (255)  NULL,
    [Segment__c]                                  NVARCHAR (255)  NULL,
    [Service_Address_City__c]                     NVARCHAR (80)   NULL,
    [Service_Address_Country__c]                  NVARCHAR (255)  NULL,
    [Service_Address_County__c]                   NVARCHAR (80)   NULL,
    [Service_Address_State__c]                    NVARCHAR (60)   NULL,
    [Service_Address_Street_1__c]                 NVARCHAR (140)  NULL,
    [Service_Address_Street_2__c]                 NVARCHAR (140)  NULL,
    [Service_Address_Zip__c]                      NVARCHAR (40)   NULL,
    [Service_Administration__c]                   NVARCHAR (255)  NULL,
    [Service_Email__c]                            NVARCHAR (80)   NULL,
    [Service_Fax__c]                              NVARCHAR (40)   NULL,
    [Service_First_Name__c]                       NVARCHAR (40)   NULL,
    [Service_Geocode__c]                          NVARCHAR (140)  NULL,
    [Service_Last_Name__c]                        NVARCHAR (80)   NULL,
    [Service_Model__c]                            NVARCHAR (255)  NULL,
    [Service_Telephone__c]                        NVARCHAR (40)   NULL,
    [Services_Sold__c]                            NTEXT           NULL,
    [ShippingCity]                                NVARCHAR (40)   NULL,
    [ShippingCountry]                             NVARCHAR (80)   NULL,
    [ShippingPostalCode]                          NVARCHAR (20)   NULL,
    [ShippingState]                               NVARCHAR (80)   NULL,
    [ShippingStreet]                              NVARCHAR (255)  NULL,
    [Sic]                                         NVARCHAR (20)   NULL,
    [SIC_Description__c]                          NCHAR (18)      NULL,
    [Site]                                        NVARCHAR (80)   NULL,
    [SOSAO__SecondAccountOwner__c]                NCHAR (18)      NULL,
    [Status__c]                                   NVARCHAR (255)  NULL,
    [Steady_State_Vouchers__c]                    DECIMAL (18)    NULL,
    [SubType__c]                                  NVARCHAR (255)  NULL,
    [Sync_to_RN__c]                               VARCHAR (5)     NULL,
    [SystemModstamp]                              DATETIME2 (7)   NOT NULL,
    [T_E_Company_Compliance__c]                   NVARCHAR (255)  NULL,
    [T_E_Policy_Education_Frequency__c]           NVARCHAR (255)  NULL,
    [T_E_Shared_Service_Centre__c]                NVARCHAR (255)  NULL,
    [Target_Account__c]                           VARCHAR (5)     NULL,
    [Target_Account_Partner__c]                   VARCHAR (5)     NULL,
    [Target_Account_Travel__c]                    VARCHAR (5)     NULL,
    [Target_Assignment_Date__c]                   DATETIME2 (7)   NULL,
    [Target_Launch_Date__c]                       DATETIME2 (7)   NULL,
    [Targeted_By__c]                              NVARCHAR (255)  NULL,
    [Tax_Exemption_Claimed__c]                    VARCHAR (5)     NULL,
    [Tax_ID_Number__c]                            NVARCHAR (20)   NULL,
    [Termination_for_Convenience__c]              VARCHAR (5)     NULL,
    [Termination_Notice_Period__c]                NVARCHAR (255)  NULL,
    [Ticker_Symbol__c]                            NVARCHAR (30)   NULL,
    [TickerSymbol]                                NVARCHAR (20)   NULL,
    [Time_Management_Provider_Solution__c]        NVARCHAR (255)  NULL,
    [Time_Zone__c]                                NVARCHAR (255)  NULL,
    [Timeframe_T_E_Solution__c]                   NVARCHAR (255)  NULL,
    [TMC_Travel_Agency__c]                        NVARCHAR (255)  NULL,
    [TMC_Travel_Agency_Contract_Exp_Date__c]      DATETIME2 (7)   NULL,
    [TMC_Travel_Agency_Other__c]                  NVARCHAR (200)  NULL,
    [TMCs__c]                                     NVARCHAR (255)  NULL,
    [Toll_Free_2__c]                              NVARCHAR (40)   NULL,
    [Toll_Free__c]                                NVARCHAR (40)   NULL,
    [Total_Added_Users__c]                        DECIMAL (18)    NULL,
    [Total_Air_Spend__c]                          NVARCHAR (255)  NULL,
    [Total_Possible_Users__c]                     DECIMAL (18)    NULL,
    [Total_Users_Last_Month__c]                   DECIMAL (18)    NULL,
    [Travel_Account_Manager__c]                   NCHAR (18)      NULL,
    [Travel_Countries_Deployed__c]                NTEXT           NULL,
    [Travel_Org_Type__c]                          NVARCHAR (255)  NULL,
    [Travel_Service_Administration__c]            NVARCHAR (255)  NULL,
    [Travel_Trans_Country__c]                     DECIMAL (18)    NULL,
    [Travel_Utilization__c]                       NTEXT           NULL,
    [Travel_Volume_Month__c]                      DECIMAL (18)    NULL,
    [Travel_Volume_Month_Band__c]                 NVARCHAR (255)  NULL,
    [TripIt_for_Business__c]                      NVARCHAR (255)  NULL,
    [TripIt_For_Business_Subscription_ID__c]      NVARCHAR (50)   NULL,
    [TripIt_Group_Link__c]                        NVARCHAR (75)   NULL,
    [TripIt_Group_Name__c]                        NVARCHAR (75)   NULL,
    [TripIt_Group_Users__c]                       DECIMAL (18)    NULL,
    [TripIt_Pro__c]                               NVARCHAR (255)  NULL,
    [TripIt_Pro_Rate__c]                          DECIMAL (18)    NULL,
    [TripIt_Users__c]                             DECIMAL (18)    NULL,
    [Type]                                        NVARCHAR (40)   NULL,
    [Type_of_Authentication__c]                   NTEXT           NULL,
    [UK_Employees__c]                             NVARCHAR (255)  NULL,
    [UK_Primary_SIC_Code__c]                      NVARCHAR (25)   NULL,
    [UK_Registration__c]                          NVARCHAR (25)   NULL,
    [UK_Subsidiaries__c]                          DECIMAL (18)    NULL,
    [Unique_financial_integration_reqmts__c]      NVARCHAR (255)  NULL,
    [Unique_Security_Requirements__c]             NVARCHAR (255)  NULL,
    [Unique_Travel_Requirements__c]               NVARCHAR (255)  NULL,
    [Upgrade_from_SmartExpense__c]                NVARCHAR (255)  NULL,
    [Use_a_TMC_Travel_Agency__c]                  NVARCHAR (255)  NULL,
    [Use_Name_In_PR__c]                           VARCHAR (5)     NULL,
    [Use_Travel_Requests__c]                      NVARCHAR (255)  NULL,
    [User_Support_Desk__c]                        NVARCHAR (255)  NULL,
    [VAT__c]                                      NVARCHAR (255)  NULL,
    [VAT_Provider__c]                             NVARCHAR (255)  NULL,
    [VAT_Reclaim__c]                              NVARCHAR (255)  NULL,
    [Vertical_Grouping__c]                        NVARCHAR (255)  NULL,
    [Virtual_Account_Manager__c]                  VARCHAR (5)     NULL,
    [W9_Recieved__c]                              VARCHAR (5)     NULL,
    [Web_Address_3__c]                            NVARCHAR (255)  NULL,
    [Website]                                     NVARCHAR (255)  NULL,
    [X3_Way_Match_Invoices__c]                    NVARCHAR (255)  NULL,
    [Zuora__Active__c]                            NVARCHAR (255)  NULL,
    [Zuora__CustomerPriority__c]                  NVARCHAR (255)  NULL,
    [Zuora__NumberofLocations__c]                 DECIMAL (18)    NULL,
    [Zuora__SLA__c]                               NVARCHAR (255)  NULL,
    [Zuora__SLAExpirationDate__c]                 DATETIME2 (7)   NULL,
    [Zuora__SLASerialNumber__c]                   NVARCHAR (10)   NULL,
    [Zuora__UpsellOpportunity__c]                 NVARCHAR (255)  NULL,
    [Zuora_CMRR__c]                               DECIMAL (18, 2) NULL,
    [Zuora_Status__c]                             NVARCHAR (100)  NULL,
    [Account_Area__c]                             NVARCHAR (255)  NULL,
    [Acct_Owner_Business_Unit__c]                 NVARCHAR (1300) NULL,
    [Acct_Owner_Division__c]                      NVARCHAR (1300) NULL,
    [Acct_Owner_Market__c]                        NVARCHAR (1300) NULL,
    [Acct_Owner_Region__c]                        NVARCHAR (1300) NULL,
    [Acct_Owner_Revenue_Group__c]                 NVARCHAR (1300) NULL,
    [Acct_Owner_Team__c]                          NVARCHAR (1300) NULL,
    [Acct_Owner_Theater__c]                       NVARCHAR (1300) NULL,
    [HMC_Entity__c]                               NVARCHAR (80)   NULL,
    [Edition__c]                                  NVARCHAR (100)  NULL,
    [Global_Account__c]                           VARCHAR (5)     NULL,
    [Free_Trial_Expiration_date__c]               DATETIME        NULL,
    [Revenue_Category__c]                         NVARCHAR (1300) NULL,
    [Size_category__c]                            NVARCHAR (1300) NULL,
    [D_B_Employees_at_Location__c]                DECIMAL (18)    NULL,
    [D_B_Employees_Worldwide__c]                  DECIMAL (18)    NULL,
    [Expense_SA__c]                               NVARCHAR (255)  NULL,
    [Invoice_SA__c]                               NVARCHAR (255)  NULL,
    [Travel_SA__c]                                NVARCHAR (255)  NULL,
    [Last_Price_Increase__c]                      DATETIME        NULL,
    [PI_Letter_Sent_Date__c]                      DATETIME        NULL,
    [PI_Program_Date__c]                          DATETIME        NULL,
    [Renewal_Program__c]                          NVARCHAR (255)  NULL,
    [Transitioned_to_Client_Development__c]       DATETIME        NULL,
    [Global_Client_Exec__c]                       NCHAR (18)      NULL,
    [OOT_Deferral_Decision__c]                    NVARCHAR (255)  NULL,
    [OOT_Deferral_Reason__c]                      NVARCHAR (255)  NULL,
    [Preferred_SAP_Account_Contact__c]            NVARCHAR (255)  NULL,
    [SAP_Account_ID__c]                           NVARCHAR (15)   NULL,
    [SAP_Account_Type__c]                         NVARCHAR (255)  NULL,
    [SAP_Financial_Customer__c]                   NVARCHAR (255)  NULL,
    [CD_Portfolio_Exception__c]                   NVARCHAR (255)  NULL,
    [Contract_Term_Status__c]                     NVARCHAR (1300) NULL,
    [CD_Portfolio_State__c]                       NVARCHAR (255)  NULL,
    [SAP_Internal_Account_Classification__c]      NVARCHAR (255)  NULL,
    [Global_Sales_Executive__c]                   NCHAR (18)      NULL,
    [SAP_Global_Ultimate_Account__c]              NCHAR (18)      NULL,
    [SAP_Named_Global_Ultimate__c]                VARCHAR (5)     NULL,
    [SAP_Segment_Alignment__c]                    NVARCHAR (1300) NULL,
    [SAP_Global_Ultimate_Roll_Up__c]              NVARCHAR (99)   NULL,
    [SAP_Contact_Phone_Number__c]                 NVARCHAR (40)   NULL,
    [Global_Ultimate_Duns_Number__c]              NVARCHAR (10)   NULL,
    [SAP_Global_Ultimate_Account_ID__c]           NVARCHAR (25)   NULL,
    [Advisor_Channel_Sales_Manager__c]            NCHAR (18)      NULL,
    [Advisor_Sales_Owner__c]                      NCHAR (18)      NULL,
    [SAP_Data_Verified_Date__c]                   DATETIME        NULL,
    [First_Character__c]                          NVARCHAR (1300) NULL,
    [X2016_Ownership_Dispute_Approved__c]         VARCHAR (5)     NULL,
    [Service_Account_Team__c]                     NCHAR (18)      NULL,
    [Contractual_ARR__c]                          DECIMAL (18, 2) NULL,
    [Account_Level__c]                            NVARCHAR (1300) NULL,
    [Named_Partner__c]                            NCHAR (18)      NULL,
    [Qualified_Out_Reason_Date_Stamp__c]          DATETIME        NULL,
    [Renewal_Targeting__c]                        NVARCHAR (255)  NULL,
    [SAP_Master_Code__c]                          NVARCHAR (99)   NULL,
    [SAP_Customer_ID__c]                          NVARCHAR (99)   NULL,
    [DunsNumber]                                  NVARCHAR (9)    NULL,
    [Registration_Date__c]                        DATETIME        NULL,
    [SAP_IAC_Exception__c]                        NVARCHAR (100)  NULL,
    [CD_Account_Pod__c]                           NVARCHAR (255)  NULL,
    [Private_Equity_Partner__c]                   NVARCHAR (255)  NULL,
    [SAP_Business_Partner_Id__c]                  NVARCHAR (10)   NULL,
    [SAP_Export_Compliance_Screening__c]          DATETIME        NULL,
    [SAP_Market_Region__c]                        NVARCHAR (99)   NULL,
    [SAP_Market_Unit__c]                          NVARCHAR (99)   NULL,
    [SAP_Planning_Entity__c]                      VARCHAR (5)     NULL,
    [SAP_Previous_CY_IAC__c]                      NVARCHAR (99)   NULL,
    [SAP_Strategy_Customer_Program__c]            NVARCHAR (255)  NULL,
    [Premier_Support_Coordinator__c]              NCHAR (18)      NULL,
    [T_Cs_Accepted__c]                            DATETIME        NULL,
    [SAP_Planning_Entity_Account_ID__c]           NVARCHAR (55)   NULL,
    [SAP_Planning_Entity_Name__c]                 NVARCHAR (255)  NULL,
    [SAP_Planning_Entity_IAC__c]                  NVARCHAR (255)  NULL,
    [SAP_Planning_Entity_Account_Owner__c]        NVARCHAR (255)  NULL,
    [SAP_Planning_Entity_Account_executive__c]    NVARCHAR (255)  NULL,
    [SAP_Planning_Refresh_Date__c]                DATETIME        NULL,
    [SAP_Buying_Product_Relationship__c]          NVARCHAR (255)  NULL,
    [SAP_Verified_Match__c]                       NVARCHAR (255)  NULL,
    [Original_Segment__c]                         NVARCHAR (255)  NULL,
    [Primary_Sales_Account__c]                    NVARCHAR (255)  NULL,
    [Concur_Primary_Account__c]                   NVARCHAR (18)   NULL,
    [Expense_20_Percent_Util_Date__c]             DATETIME        NULL,
    [Invoice_20_Percent_Util_Date__c]             DATETIME        NULL,
    [PreSales_SC__c]                              NCHAR (18)      NULL,
    [SAP_Planning_PE_Locked__c]                   NVARCHAR (255)  NULL,
    [SAP_Previous_Year_PE_ID_Locked__c]           NVARCHAR (80)   NULL,
    [Expense_Free_Trial_End_Date__c]              DATETIME        NULL,
    [Expense_Free_Trial_Start_Date__c]            DATETIME        NULL,
    [Invoice_Free_Trial_End_Date__c]              DATETIME        NULL,
    [Invoice_Free_Trial_Start_Date__c]            DATETIME        NULL,
    [Acct_Owner_SAP_Region__c]                    NVARCHAR (1300) NULL,
    [Next_FY_Account_SAP_Region__c]               NVARCHAR (255)  NULL,
    [Next_FY_Account_Revenue_Group__c]            NVARCHAR (255)  NULL,
    [Next_FY_Account_Owner__c]                    NCHAR (18)      NULL,
    [Next_FY_Account_Division__c]                 NVARCHAR (255)  NULL,
    [Next_FY_Account_Business_Unit__c]            NVARCHAR (255)  NULL,
    [Next_FY_Account_Market__c]                   NVARCHAR (255)  NULL,
    [Next_FY_Account_Region__c]                   NVARCHAR (255)  NULL,
    [Next_FY_Account_Team__c]                     NVARCHAR (255)  NULL,
    [Next_FY_Account_Theater__c]                  NVARCHAR (255)  NULL,
    [Next_FY_Acct_Owner_18_Digit_ID__c]           NVARCHAR (255)  NULL,
    [SAP_Account_Executive_Name__c]               NVARCHAR (80)   NULL,
    [SAP_Regional_Buying_Classification__c]       NVARCHAR (80)   NULL,
    [DandbCompanyId]                              NCHAR (18)      NULL,
    [Analytics_Conversion_Status__c]              NVARCHAR (255)  NULL,
    [MDG_C_ID__c]                                 NVARCHAR (80)   NULL,
    [SAP_Locked_Named_List__c]                    NVARCHAR (255)  NULL,
    [SAP_Locked_Planning_Entity_Primary_SIC__c]   NVARCHAR (99)   NULL,
    [SAP_Planning_Entity_Primary_SIC__c]          NVARCHAR (99)   NULL,
    [AKA_Company_Name__c]                         NVARCHAR (255)  NULL,
    CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
    ON [dbo].[Account_0809]([Type] ASC)
    INCLUDE([CreatedDate], [Customer_Since__c], [Id], [Name], [Service_Address_City__c], [Service_Address_Country__c], [Service_Address_State__c], [Service_Address_Street_1__c], [Service_Address_Street_2__c], [Service_Address_Zip__c]);

