CREATE TABLE [dbo].[AP_PRODUCT_MAP] (
    [ID]                     INT           IDENTITY (1, 1) NOT NULL,
    [BIGMACHINES_PARTNUMBER] VARCHAR (255) NULL,
    [MN_ID]                  VARCHAR (255) NULL,
    [MN_PI_NAME]             VARCHAR (255) NULL,
    [MN_ITEM_TYPE]           VARCHAR (255) NULL,
    [MN_PO]                  VARCHAR (255) NULL,
    [MN_PO_NAME]             VARCHAR (255) NULL,
    [MN_NAME]                VARCHAR (255) NULL,
    [MN_SUB]                 DATETIME      NULL,
    [MN_BILL]                VARCHAR (255) NULL,
    [MN_CREATED]             DATETIME      NULL,
    [SF_ID]                  VARCHAR (255) NULL,
    [SF_NAME]                VARCHAR (255) NULL,
    [SF_MARKETING_NAME]      VARCHAR (255) NULL,
    [I4P_ID]                 VARCHAR (255) NULL,
    [I4P_PO]                 VARCHAR (255) NULL,
    [I4P_MATERIAL]           VARCHAR (255) NULL,
    [I4P_MATERIAL_DESC]      VARCHAR (255) NULL,
    [I4P_TYPE_DESC]          VARCHAR (255) NULL,
    [SALES_ORG]              VARCHAR (255) NULL,
    [ALL_SYNC_FLAG]          VARCHAR (1)   DEFAULT ('N') NULL,
    [MN_SFDC_SYNC_FLAG]      VARCHAR (1)   DEFAULT ('N') NULL,
    [MN_I4P_SYNC_FLAG]       VARCHAR (1)   DEFAULT ('N') NULL,
    [SFDC_I4P_SYNC_FLAG]     VARCHAR (1)   DEFAULT ('N') NULL,
    [ONLY_SFDC_FLAG]         VARCHAR (1)   DEFAULT ('N') NULL,
    [ONLY_MN_FLAG]           VARCHAR (1)   DEFAULT ('N') NULL,
    [ONLY_I4P_FLAG]          VARCHAR (1)   DEFAULT ('N') NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

