CREATE TABLE [dbo].[CRS_I4P_PRODUCTS] (
    [Material]          NVARCHAR (255) NULL,
    [Mat Description]   NVARCHAR (255) NULL,
    [Group]             NVARCHAR (255) NULL,
    [Group Desc]        NVARCHAR (255) NULL,
    [AAG]               NVARCHAR (255) NULL,
    [Old material no#]  NVARCHAR (255) NULL,
    [Type]              NVARCHAR (255) NULL,
    [Type Desc]         NVARCHAR (255) NULL,
    [Plnt]              NVARCHAR (255) NULL,
    [ItCGr]             NVARCHAR (255) NULL,
    [SOrg#]             NVARCHAR (255) NULL,
    [DChl]              NVARCHAR (255) NULL,
    [I]                 NVARCHAR (255) NULL,
    [Dv]                NVARCHAR (255) NULL,
    [BUn]               NVARCHAR (255) NULL,
    [R]                 NVARCHAR (255) NULL,
    [PI]                NVARCHAR (255) NULL,
    [PO]                NVARCHAR (255) NULL,
    [Ctry]              NVARCHAR (255) NULL,
    [TaxM1]             NVARCHAR (255) NULL,
    [TaxM1 Description] NVARCHAR (255) NULL,
    [TaxM2]             NVARCHAR (255) NULL,
    [Language]          NVARCHAR (255) NULL,
    [Created By]        NVARCHAR (255) NULL,
    [ChangeName]        NVARCHAR (255) NULL,
    [Created]           SMALLDATETIME  NULL,
    [Last Chg]          SMALLDATETIME  NULL,
    [Changed by]        NVARCHAR (255) NULL,
    [ChangeName1]       NVARCHAR (255) NULL,
    [St]                NVARCHAR (255) NULL
);

