CREATE TABLE [dbo].[AccountCleanInfo] (
    [AccountId]                         NCHAR (18)       NOT NULL,
    [AccountSite]                       NVARCHAR (80)    NULL,
    [AnnualRevenue]                     DECIMAL (18)     NULL,
    [City]                              NVARCHAR (40)    NULL,
    [CleanedByJob]                      VARCHAR (5)      NOT NULL,
    [CleanedByUser]                     VARCHAR (5)      NOT NULL,
    [CompanyName]                       NVARCHAR (255)   NULL,
    [CompanyStatusDataDotCom]           NVARCHAR (255)   NULL,
    [Country]                           NVARCHAR (80)    NULL,
    [CreatedById]                       NCHAR (18)       NULL,
    [CreatedDate]                       DATETIME2 (7)    NOT NULL,
    [CurrencyIsoCode]                   NVARCHAR (3)     NULL,
    [DandBCompanyDunsNumber]            NVARCHAR (9)     NULL,
    [DataDotComId]                      NVARCHAR (20)    NULL,
    [Description]                       NTEXT            NULL,
    [DunsNumber]                        NVARCHAR (9)     NULL,
    [DunsRightMatchConfidence]          INT              NULL,
    [DunsRightMatchGrade]               NVARCHAR (255)   NULL,
    [Fax]                               NVARCHAR (40)    NULL,
    [GeocodeAccuracy]                   NVARCHAR (255)   NULL,
    [Id]                                NCHAR (18)       NOT NULL,
    [Industry]                          NVARCHAR (40)    NULL,
    [IsDeleted]                         VARCHAR (5)      NOT NULL,
    [IsDifferentAccountSite]            VARCHAR (5)      NOT NULL,
    [IsDifferentAnnualRevenue]          VARCHAR (5)      NOT NULL,
    [IsDifferentCity]                   VARCHAR (5)      NOT NULL,
    [IsDifferentCompanyName]            VARCHAR (5)      NOT NULL,
    [IsDifferentCountry]                VARCHAR (5)      NOT NULL,
    [IsDifferentCountryCode]            VARCHAR (5)      NOT NULL,
    [IsDifferentDandBCompanyDunsNumber] VARCHAR (5)      NOT NULL,
    [IsDifferentDescription]            VARCHAR (5)      NOT NULL,
    [IsDifferentDunsNumber]             VARCHAR (5)      NOT NULL,
    [IsDifferentFax]                    VARCHAR (5)      NOT NULL,
    [IsDifferentIndustry]               VARCHAR (5)      NOT NULL,
    [IsDifferentNaicsCode]              VARCHAR (5)      NOT NULL,
    [IsDifferentNaicsDescription]       VARCHAR (5)      NOT NULL,
    [IsDifferentNumberOfEmployees]      VARCHAR (5)      NOT NULL,
    [IsDifferentOwnership]              VARCHAR (5)      NOT NULL,
    [IsDifferentPhone]                  VARCHAR (5)      NOT NULL,
    [IsDifferentPostalCode]             VARCHAR (5)      NOT NULL,
    [IsDifferentSic]                    VARCHAR (5)      NOT NULL,
    [IsDifferentSicDescription]         VARCHAR (5)      NOT NULL,
    [IsDifferentState]                  VARCHAR (5)      NOT NULL,
    [IsDifferentStateCode]              VARCHAR (5)      NOT NULL,
    [IsDifferentStreet]                 VARCHAR (5)      NOT NULL,
    [IsDifferentTickerSymbol]           VARCHAR (5)      NOT NULL,
    [IsDifferentTradestyle]             VARCHAR (5)      NOT NULL,
    [IsDifferentWebsite]                VARCHAR (5)      NOT NULL,
    [IsDifferentYearStarted]            VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongAccountSite]         VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongAddress]             VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongAnnualRevenue]       VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongCompanyName]         VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongDescription]         VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongDunsNumber]          VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongFax]                 VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongIndustry]            VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongNaicsCode]           VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongNaicsDescription]    VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongNumberOfEmployees]   VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongOwnership]           VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongPhone]               VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongSic]                 VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongSicDescription]      VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongTickerSymbol]        VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongTradestyle]          VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongWebsite]             VARCHAR (5)      NOT NULL,
    [IsFlaggedWrongYearStarted]         VARCHAR (5)      NOT NULL,
    [IsInactive]                        VARCHAR (5)      NOT NULL,
    [IsReviewedAccountSite]             VARCHAR (5)      NOT NULL,
    [IsReviewedAddress]                 VARCHAR (5)      NOT NULL,
    [IsReviewedAnnualRevenue]           VARCHAR (5)      NOT NULL,
    [IsReviewedCompanyName]             VARCHAR (5)      NOT NULL,
    [IsReviewedDandBCompanyDunsNumber]  VARCHAR (5)      NOT NULL,
    [IsReviewedDescription]             VARCHAR (5)      NOT NULL,
    [IsReviewedDunsNumber]              VARCHAR (5)      NOT NULL,
    [IsReviewedFax]                     VARCHAR (5)      NOT NULL,
    [IsReviewedIndustry]                VARCHAR (5)      NOT NULL,
    [IsReviewedNaicsCode]               VARCHAR (5)      NOT NULL,
    [IsReviewedNaicsDescription]        VARCHAR (5)      NOT NULL,
    [IsReviewedNumberOfEmployees]       VARCHAR (5)      NOT NULL,
    [IsReviewedOwnership]               VARCHAR (5)      NOT NULL,
    [IsReviewedPhone]                   VARCHAR (5)      NOT NULL,
    [IsReviewedSic]                     VARCHAR (5)      NOT NULL,
    [IsReviewedSicDescription]          VARCHAR (5)      NOT NULL,
    [IsReviewedTickerSymbol]            VARCHAR (5)      NOT NULL,
    [IsReviewedTradestyle]              VARCHAR (5)      NOT NULL,
    [IsReviewedWebsite]                 VARCHAR (5)      NOT NULL,
    [IsReviewedYearStarted]             VARCHAR (5)      NOT NULL,
    [LastMatchedDate]                   DATETIME2 (7)    NOT NULL,
    [LastModifiedById]                  NCHAR (18)       NULL,
    [LastModifiedDate]                  DATETIME2 (7)    NOT NULL,
    [LastStatusChangedById]             NCHAR (18)       NULL,
    [LastStatusChangedDate]             DATETIME2 (7)    NULL,
    [Latitude]                          DECIMAL (18, 15) NULL,
    [Longitude]                         DECIMAL (18, 15) NULL,
    [NaicsCode]                         NVARCHAR (8)     NULL,
    [NaicsDescription]                  NVARCHAR (120)   NULL,
    [Name]                              NVARCHAR (255)   NOT NULL,
    [NumberOfEmployees]                 INT              NULL,
    [Ownership]                         NVARCHAR (40)    NULL,
    [Phone]                             NVARCHAR (40)    NULL,
    [PostalCode]                        NVARCHAR (20)    NULL,
    [Sic]                               NVARCHAR (20)    NULL,
    [SIC_Code_Different__c]             NVARCHAR (1300)  NULL,
    [SicDescription]                    NVARCHAR (80)    NULL,
    [State]                             NVARCHAR (80)    NULL,
    [Street]                            NVARCHAR (255)   NULL,
    [SystemModstamp]                    DATETIME2 (7)    NOT NULL,
    [TickerSymbol]                      NVARCHAR (20)    NULL,
    [Tradestyle]                        NVARCHAR (255)   NULL,
    [Website]                           NVARCHAR (255)   NULL,
    [YearStarted]                       NVARCHAR (12)    NULL,
    CONSTRAINT [PK_AccountCleanInfo_Id] PRIMARY KEY NONCLUSTERED ([Id] ASC)
);

