CREATE TABLE [dbo].[Account] (
    [Acc_Assignment_Matcher__c]                  NVARCHAR (1300) NULL,
    [Account_Age_Is_Past_45_Days__c]             VARCHAR (5)     NULL,
    [Account_Area__c]                            NVARCHAR (255)  NULL,
    [Account_Level__c]                           NVARCHAR (1300) NULL,
    [Account_Manager__c]                         NVARCHAR (1300) NULL,
    [Account_Owner_ID__c]                        NVARCHAR (1300) NULL,
    [Account_Plan_Comments__c]                   NVARCHAR (255)  NULL,
    [Account_Status__c]                          NVARCHAR (255)  NULL,
    [AccountNumber]                              NVARCHAR (40)   NULL,
    [Accounts_Payable_Staff_Size__c]             DECIMAL (18)    NULL,
    [AccountStatus__c]                           NVARCHAR (255)  NULL,
    [Acct_Owner_Business_Unit__c]                NVARCHAR (1300) NULL,
    [Acct_Owner_Division__c]                     NVARCHAR (1300) NULL,
    [Acct_Owner_Market__c]                       NVARCHAR (1300) NULL,
    [Acct_Owner_Region__c]                       NVARCHAR (1300) NULL,
    [Acct_Owner_Revenue_Group__c]                NVARCHAR (1300) NULL,
    [Acct_Owner_SAP_Region__c]                   NVARCHAR (1300) NULL,
    [Acct_Owner_Team__c]                         NVARCHAR (1300) NULL,
    [Acct_Owner_Theater__c]                      NVARCHAR (1300) NULL,
    [Active_Users__c]                            DECIMAL (18)    NULL,
    [Actual_Air_Spend__c]                        DECIMAL (18)    NULL,
    [Additional_card__c]                         NVARCHAR (255)  NULL,
    [Admin_Last_Login__c]                        DATETIME        NULL,
    [Advisor_Channel_Sales_Manager__c]           NCHAR (18)      NULL,
    [Advisor_Sales_Owner__c]                     NCHAR (18)      NULL,
    [Agency_Id__c]                               NVARCHAR (255)  NULL,
    [AKA_Company_Name__c]                        NVARCHAR (255)  NULL,
    [AM_Program__c]                              NVARCHAR (255)  NULL,
    [AM_Program_Date_Assigned__c]                DATETIME        NULL,
    [AM_Region__c]                               NVARCHAR (1300) NULL,
    [AM_Segment__c]                              NVARCHAR (1300) NULL,
    [Amex_Auth_Delivered__c]                     DATETIME        NULL,
    [Amex_Auth_for_Client_Data__c]               NVARCHAR (255)  NULL,
    [Amex_Signature__c]                          NVARCHAR (255)  NULL,
    [Annual_Meetings__c]                         NVARCHAR (255)  NULL,
    [Annual_PNRs__c]                             DECIMAL (18)    NULL,
    [Annual_Revenue__c]                          DECIMAL (18, 2) NULL,
    [Annual_T_E_Spend__c]                        NVARCHAR (255)  NULL,
    [AnnualRevenue]                              DECIMAL (18)    NULL,
    [Anticipated_Yearly_Revenue__c]              DECIMAL (18)    NULL,
    [Approve_Reject__c]                          NVARCHAR (1300) NULL,
    [AR_Analyst__c]                              NCHAR (18)      NULL,
    [Area_Code__c]                               NVARCHAR (1300) NULL,
    [Assigned_Account_MDR_Partner__c]            NCHAR (18)      NULL,
    [Assigned_Account_MDR2__c]                   NCHAR (18)      NULL,
    [Audit_Method__c]                            NVARCHAR (255)  NULL,
    [Billing_Contact__c]                         NCHAR (18)      NULL,
    [Billing_Contact_Email__c]                   NVARCHAR (1300) NULL,
    [Billing_Contact_Phone__c]                   NVARCHAR (1300) NULL,
    [Billing_Cycle__c]                           NVARCHAR (255)  NULL,
    [Billing_Email__c]                           NVARCHAR (80)   NULL,
    [Billing_First_Name__c]                      NVARCHAR (40)   NULL,
    [Billing_Geocode__c]                         NVARCHAR (140)  NULL,
    [Billing_Last_Name__c]                       NVARCHAR (80)   NULL,
    [BMI_OED_of_last_Submitted_Order__c]         NVARCHAR (50)   NULL,
    [BMI_Submit_Order_Date__c]                   NVARCHAR (50)   NULL,
    [BPS_Status__c]                              NVARCHAR (255)  NULL,
    [Brand_Awareness__c]                         NVARCHAR (255)  NULL,
    [Breeze_Account_Stage__c]                    NVARCHAR (255)  NULL,
    [Breeze_Channel__c]                          NVARCHAR (255)  NULL,
    [Breeze_CID__c]                              NVARCHAR (100)  NULL,
    [Breeze_Last_CID__c]                         NVARCHAR (100)  NULL,
    [Breeze_Lead_Source__c]                      NVARCHAR (100)  NULL,
    [Breeze_Referral_Received__c]                NCHAR (18)      NULL,
    [Breeze_Referral_Sent__c]                    NCHAR (18)      NULL,
    [Breeze_Representative__c]                   NCHAR (18)      NULL,
    [Breeze_Team__c]                             NVARCHAR (255)  NULL,
    [BSA_Region__c]                              NVARCHAR (255)  NULL,
    [BTA_Card__c]                                NVARCHAR (255)  NULL,
    [BUMS__c]                                    NVARCHAR (1300) NULL,
    [Business_Focus__c]                          NVARCHAR (MAX)  NULL,
    [Business_Focus_Other__c]                    NVARCHAR (40)   NULL,
    [Business_Type__c]                           NVARCHAR (MAX)  NULL,
    [Business_Unit__c]                           NVARCHAR (255)  NULL,
    [Buying_Horizon__c]                          NVARCHAR (255)  NULL,
    [Buying_Horizon_Date__c]                     DATETIME        NULL,
    [Categorization__c]                          NVARCHAR (255)  NULL,
    [CD_Portfolio_State__c]                      NVARCHAR (255)  NULL,
    [CES_Reseller__c]                            NVARCHAR (255)  NULL,
    [Charge_Volume__c]                           DECIMAL (18)    NULL,
    [Clean_Address__c]                           VARCHAR (5)     NULL,
    [Cliqbook_Client__c]                         NVARCHAR (255)  NULL,
    [Cliqbook_Reseller__c]                       NVARCHAR (255)  NULL,
    [Closed_Lost_This_Year__c]                   DECIMAL (18, 2) NULL,
    [Closed_Won_This_Year__c]                    DECIMAL (18, 2) NULL,
    [Comments__c]                                NVARCHAR (MAX)  NULL,
    [Company_Created_Date__c]                    DATETIME        NULL,
    [Company_Launch_Date__c]                     NVARCHAR (255)  NULL,
    [Company_was_Acquired__c]                    VARCHAR (5)     NULL,
    [Concur_Primary_Account__c]                  NVARCHAR (18)   NULL,
    [Concur_Star_Shortcuts__c]                   NVARCHAR (1300) NULL,
    [Contract_Effective_Date__c]                 DATETIME        NULL,
    [Contract_Expiration_Date__c]                DATETIME        NULL,
    [Contract_Regional_Access__c]                NVARCHAR (255)  NULL,
    [Contract_Renewal_Date__c]                   DATETIME        NULL,
    [Contract_Source__c]                         NVARCHAR (255)  NULL,
    [Contract_Term_Status__c]                    NVARCHAR (1300) NULL,
    [Contract_Termination_Date__c]               DATETIME        NULL,
    [Contracting_Entity__c]                      NVARCHAR (255)  NULL,
    [Contractual_ARR__c]                         DECIMAL (18, 2) NULL,
    [Core_Service_Transitioned__c]               DATETIME        NULL,
    [Correction_Billing_Country__c]              NVARCHAR (1300) NULL,
    [Country_Scope__c]                           NVARCHAR (255)  NULL,
    [CreatedById]                                NCHAR (18)      NULL,
    [CreatedDate]                                DATETIME        NOT NULL,
    [Credit_Comments__c]                         NVARCHAR (255)  NULL,
    [Credit_Status__c]                           NVARCHAR (255)  NULL,
    [CRM__c]                                     NVARCHAR (255)  NULL,
    [CTE_Corporate_Upgraded__c]                  NVARCHAR (255)  NULL,
    [Curr_Booking_Method_Contract_Expiration__c] NVARCHAR (12)   NULL,
    [CurrencyIsoCode]                            NVARCHAR (3)    NULL,
    [Customer_Currency__c]                       NVARCHAR (255)  NULL,
    [Customer_Profile__c]                        NVARCHAR (255)  NULL,
    [Customer_Region__c]                         NVARCHAR (255)  NULL,
    [Customer_Since__c]                          DATETIME        NULL,
    [D_B_Employees_at_Location__c]               DECIMAL (18)    NULL,
    [D_B_Employees_Worldwide__c]                 DECIMAL (18)    NULL,
    [Data_Center__c]                             NVARCHAR (255)  NULL,
    [Date_Company_Made_Reference__c]             DATETIME        NULL,
    [DBA__c]                                     NVARCHAR (75)   NULL,
    [ddc_prospector__Sourced_from_Data_com__c]   DECIMAL (18)    NULL,
    [Description]                                NVARCHAR (MAX)  NULL,
    [DNB__c]                                     NVARCHAR (10)   NULL,
    [DNB_Not_Validated__c]                       NVARCHAR (5)    NULL,
    [DUNS_Length__c]                             DECIMAL (18)    NULL,
    [DunsParentAccount__c]                       NCHAR (18)      NULL,
    [DunsUltimateParentAccount__c]               NCHAR (18)      NULL,
    [Edition__c]                                 NVARCHAR (100)  NULL,
    [Employee_Band_Worldwide__c]                 NVARCHAR (255)  NULL,
    [Employee_Range__c]                          NVARCHAR (1300) NULL,
    [Employee_Travel_Volume__c]                  NVARCHAR (255)  NULL,
    [Employees_at_Location__c]                   DECIMAL (18)    NULL,
    [Employees_Band__c]                          NVARCHAR (255)  NULL,
    [Employees_Worldwide__c]                     DECIMAL (18)    NULL,
    [Entity_ID__c]                               NVARCHAR (45)   NULL,
    [Expense_Support_Lead__c]                    NVARCHAR (255)  NULL,
    [Fax]                                        NVARCHAR (40)   NULL,
    [Final_CD_State__c]                          NVARCHAR (1300) NULL,
    [Financial_System__c]                        NVARCHAR (255)  NULL,
    [Financial_System_Other__c]                  NVARCHAR (255)  NULL,
    [First_Character__c]                         NVARCHAR (1300) NULL,
    [Fiscal_Year_End__c]                         NVARCHAR (255)  NULL,
    [Former_Customer_Date_Stamp__c]              DATETIME        NULL,
    [Free_Trial_Days_Remaining__c]               DECIMAL (18)    NULL,
    [Free_Trial_Edition__c]                      NVARCHAR (255)  NULL,
    [Free_Trial_Expiration_date__c]              DATETIME        NULL,
    [Fulfillment_Partner_Account__c]             VARCHAR (5)     NULL,
    [GDS__c]                                     NVARCHAR (255)  NULL,
    [GE_Client_ID__c]                            DECIMAL (18)    NULL,
    [GE_Client_Status__c]                        NVARCHAR (1300) NULL,
    [GE_Client_Type__c]                          NVARCHAR (255)  NULL,
    [GEContract_Oracle_ID__c]                    NVARCHAR (1300) NULL,
    [Global_Account__c]                          VARCHAR (5)     NULL,
    [Global_Account_Named_Parent_Roll_up__c]     NVARCHAR (100)  NULL,
    [Global_Client_Exec__c]                      NCHAR (18)      NULL,
    [Global_Parent_Account__c]                   NCHAR (18)      NULL,
    [Global_Sales_Executive__c]                  NCHAR (18)      NULL,
    [Global_Ultimate_Duns_Number__c]             NVARCHAR (10)   NULL,
    [HMC_Entity__c]                              NVARCHAR (80)   NULL,
    [HMC_Entity_Test__c]                         NVARCHAR (12)   NULL,
    [HR_Solution__c]                             NVARCHAR (255)  NULL,
    [Id]                                         NCHAR (18)      NOT NULL,
    [Immediate_Parent_DUNS__c]                   NVARCHAR (25)   NULL,
    [Inc_5_000__c]                               NVARCHAR (MAX)  NULL,
    [Industry]                                   NVARCHAR (40)   NULL,
    [Industry_Sub_Type__c]                       NVARCHAR (255)  NULL,
    [infer2__Infer_Rating__c]                    NVARCHAR (1300) NULL,
    [infer2__Infer_Score__c]                     DECIMAL (18)    NULL,
    [infer2__Infer_Score_ID__c]                  NCHAR (18)      NULL,
    [International_Filers__c]                    VARCHAR (5)     NULL,
    [Invoice_Language__c]                        NVARCHAR (255)  NULL,
    [Invoice_Solution_Reseller__c]               NVARCHAR (255)  NULL,
    [IsCustomerPortal]                           VARCHAR (5)     NOT NULL,
    [jsImpacts__Added_from_Data_com__c]          DECIMAL (18)    NULL,
    [jsImpacts__Data_com_Managed__c]             DECIMAL (18)    NULL,
    [jsImpacts__Data_com_Matched__c]             NVARCHAR (1300) NULL,
    [Last_Credit_Update__c]                      DATETIME        NULL,
    [Last_NPS_Rating_0_10__c]                    DECIMAL (18)    NULL,
    [LastActivityDate]                           DATETIME        NULL,
    [LastModifiedById]                           NCHAR (18)      NULL,
    [LastModifiedDate]                           DATETIME        NOT NULL,
    [Lead_Score__c]                              NVARCHAR (50)   NULL,
    [Lead_Source__c]                             NVARCHAR (255)  NULL,
    [Legacy_Service_Model__c]                    NVARCHAR (255)  NULL,
    [Market__c]                                  NVARCHAR (255)  NULL,
    [Marketing_Awareness__c]                     NVARCHAR (255)  NULL,
    [Marketing_Tier__c]                          NVARCHAR (255)  NULL,
    [Marketing_Tier_Travel__c]                   NVARCHAR (255)  NULL,
    [marketoSyncField__c]                        VARCHAR (5)     NULL,
    [MD_Comments__c]                             NVARCHAR (255)  NULL,
    [MD_Date__c]                                 DATETIME        NULL,
    [MD_Opportunity_Status__c]                   NVARCHAR (255)  NULL,
    [MDG_C_ID__c]                                NVARCHAR (80)   NULL,
    [MDR_Territory__c]                           NVARCHAR (50)   NULL,
    [Member_ID__c]                               NVARCHAR (18)   NULL,
    [Member_Type__c]                             NVARCHAR (255)  NULL,
    [MN_Update_ID__c]                            NVARCHAR (40)   NULL,
    [MQL_Account__c]                             VARCHAR (5)     NULL,
    [Multiple_Billing_Accounts__c]               VARCHAR (5)     NULL,
    [NAICS_Code__c]                              NVARCHAR (50)   NULL,
    [NAICS_Description__c]                       NVARCHAR (255)  NULL,
    [Name]                                       NVARCHAR (255)  NOT NULL,
    [Named_Partner__c]                           NCHAR (18)      NULL,
    [New_Customer_Date_Time_Stamp__c]            DATETIME        NULL,
    [Next_FY_2nd_Account_Owner__c]               NCHAR (18)      NULL,
    [Next_FY_2nd_Acct_Owner_18_Digit_ID__c]      NVARCHAR (255)  NULL,
    [Next_FY_Account_Business_Unit__c]           NVARCHAR (255)  NULL,
    [Next_FY_Account_Division__c]                NVARCHAR (255)  NULL,
    [Next_FY_Account_Market__c]                  NVARCHAR (255)  NULL,
    [Next_FY_Account_Owner__c]                   NCHAR (18)      NULL,
    [Next_FY_Account_Region__c]                  NVARCHAR (255)  NULL,
    [Next_FY_Account_Revenue_Group__c]           NVARCHAR (255)  NULL,
    [Next_FY_Account_SAP_Region__c]              NVARCHAR (255)  NULL,
    [Next_FY_Account_Team__c]                    NVARCHAR (255)  NULL,
    [Next_FY_Account_Theater__c]                 NVARCHAR (255)  NULL,
    [Next_FY_Acct_Owner_18_Digit_ID__c]          NVARCHAR (255)  NULL,
    [Not_Engaged_Reason__c]                      NVARCHAR (255)  NULL,
    [Notes__c]                                   NVARCHAR (MAX)  NULL,
    [Notice_Address_City__c]                     NVARCHAR (80)   NULL,
    [Notice_Address_Country__c]                  NVARCHAR (255)  NULL,
    [Notice_Address_County__c]                   NVARCHAR (80)   NULL,
    [Notice_Address_State__c]                    NVARCHAR (60)   NULL,
    [Notice_Address_Street_1__c]                 NVARCHAR (140)  NULL,
    [Notice_Address_Street_2__c]                 NVARCHAR (140)  NULL,
    [Notice_Address_Zip__c]                      NVARCHAR (40)   NULL,
    [Notice_Email__c]                            NVARCHAR (80)   NULL,
    [Notice_Fax__c]                              NVARCHAR (40)   NULL,
    [Notice_First_Name__c]                       NVARCHAR (40)   NULL,
    [Notice_Last_Name__c]                        NVARCHAR (80)   NULL,
    [Notice_Telephone__c]                        NVARCHAR (40)   NULL,
    [NPS_Category__c]                            NVARCHAR (1300) NULL,
    [NPS_Service__c]                             NVARCHAR (1300) NULL,
    [Number_Card_Holders__c]                     DECIMAL (18)    NULL,
    [Number_Cards_in_Force__c]                   DECIMAL (18)    NULL,
    [Number_of_Cards_Added__c]                   DECIMAL (18)    NULL,
    [Number_of_Contacts__c]                      DECIMAL (18)    NULL,
    [Number_of_Exports__c]                       DECIMAL (18)    NULL,
    [Number_of_Travel_Configs__c]                DECIMAL (18)    NULL,
    [Number_of_Travel_Sites__c]                  DECIMAL (18)    NULL,
    [Number_of_Travelers__c]                     NVARCHAR (255)  NULL,
    [Number_of_TripIt_Users__c]                  DECIMAL (18)    NULL,
    [Number_TripIt_Pro_Users__c]                 DECIMAL (18)    NULL,
    [NumberOfEmployees]                          INT             NULL,
    [of_Accounts__c]                             DECIMAL (18)    NULL,
    [Open_Closed_Venn__c]                        NVARCHAR (1300) NULL,
    [Open_Escalation__c]                         NVARCHAR (1300) NULL,
    [Open_Escalation_Count__c]                   DECIMAL (18)    NULL,
    [Open_Pipeline_This_Year__c]                 DECIMAL (18, 2) NULL,
    [Open_Won__c]                                DECIMAL (18, 2) NULL,
    [Opportunities__c]                           DECIMAL (18)    NULL,
    [Opportunities_Lost__c]                      DECIMAL (18)    NULL,
    [Opportunities_Open__c]                      DECIMAL (18)    NULL,
    [Opportunities_Won__c]                       DECIMAL (18)    NULL,
    [Oracle_ID__c]                               NVARCHAR (45)   NULL,
    [Org_Name_Vantive__c]                        NVARCHAR (255)  NULL,
    [Original_Segment__c]                        NVARCHAR (255)  NULL,
    [Other_GE_Client_IDs__c]                     NVARCHAR (1300) NULL,
    [Outtask_ID__c]                              NVARCHAR (8)    NULL,
    [Owner_is_Active__c]                         VARCHAR (5)     NULL,
    [OwnerId]                                    NCHAR (18)      NOT NULL,
    [Ownership]                                  NVARCHAR (40)   NULL,
    [Parent_Account_Data_com_Key__c]             NVARCHAR (1300) NULL,
    [ParentId]                                   NCHAR (18)      NULL,
    [Partner_Discount__c]                        DECIMAL (18, 2) NULL,
    [Partner_Rep_1__c]                           NCHAR (18)      NULL,
    [Partner_Rep_1_Last_Updated__c]              DATETIME        NULL,
    [Partner_Rep_2__c]                           NCHAR (18)      NULL,
    [Partner_Rep_3__c]                           NCHAR (18)      NULL,
    [Payment_Method__c]                          NVARCHAR (255)  NULL,
    [Payment_Terms__c]                           NVARCHAR (255)  NULL,
    [Payment_Type__c]                            NVARCHAR (255)  NULL,
    [Payroll__c]                                 NVARCHAR (255)  NULL,
    [Phone]                                      NVARCHAR (40)   NULL,
    [Phone_inContact__c]                         NVARCHAR (1300) NULL,
    [PI_Letter_Sent_Date__c]                     DATETIME        NULL,
    [PI_Program_Date__c]                         DATETIME        NULL,
    [PO_Number__c]                               NVARCHAR (30)   NULL,
    [PO_to_be_Issued__c]                         VARCHAR (5)     NULL,
    [Power_of_one__c]                            DECIMAL (18)    NULL,
    [Pre_Production__c]                          VARCHAR (5)     NULL,
    [Preferred_SAP_Account_Contact__c]           NVARCHAR (255)  NULL,
    [Premier_Account__c]                         VARCHAR (5)     NULL,
    [Premier_Support_Coordinator__c]             NCHAR (18)      NULL,
    [Previous_Booking_Solution__c]               NVARCHAR (255)  NULL,
    [Primary_Card__c]                            NVARCHAR (255)  NULL,
    [Primary_Email_Domain__c]                    NVARCHAR (50)   NULL,
    [Primary_Sales_Account__c]                   NVARCHAR (255)  NULL,
    [Private_Equity_Partner__c]                  NVARCHAR (255)  NULL,
    [Private_Equity_Partner_Target_Lookup__c]    NCHAR (18)      NULL,
    [Pro_Enterprise_PNR_Price__c]                DECIMAL (18, 2) NULL,
    [Pro_Reseller_Price__c]                      DECIMAL (18)    NULL,
    [Probability_roll_up_Eloqua__c]              DECIMAL (18)    NULL,
    [Profile_Account_Score_APA__c]               DECIMAL (18)    NULL,
    [Profile_Account_Score_APA_Status__c]        NVARCHAR (1300) NULL,
    [Profile_Account_Score_EMEA__c]              DECIMAL (18)    NULL,
    [Profile_Account_Score_EMEA_Status__c]       NVARCHAR (1300) NULL,
    [Profile_Account_Score_Japan__c]             DECIMAL (18)    NULL,
    [Profile_Account_Score_Japan_Status__c]      NVARCHAR (1300) NULL,
    [Profile_Account_Score_NA__c]                DECIMAL (18)    NULL,
    [Profile_Account_Score_Travel__c]            DECIMAL (18)    NULL,
    [Profile_Account_Score_UK_SMB__c]            DECIMAL (18)    NULL,
    [Profile_Account_Score_UK_SMB_Status__c]     NVARCHAR (1300) NULL,
    [Program_Type__c]                            NVARCHAR (255)  NULL,
    [Promo_Code__c]                              NVARCHAR (255)  NULL,
    [Qualified_Out_Reason_Date_Stamp__c]         DATETIME        NULL,
    [Qualified_Out_Reasons__c]                   NVARCHAR (255)  NULL,
    [Questionnaires__c]                          DECIMAL (18)    NULL,
    [Rating]                                     NVARCHAR (40)   NULL,
    [Reassign_Owner_Reason__c]                   NVARCHAR (255)  NULL,
    [Receive__c]                                 NVARCHAR (255)  NULL,
    [RecordTypeId]                               NCHAR (18)      NULL,
    [Reference_Status__c]                        NVARCHAR (255)  NULL,
    [Reference_Status_Updated_by__c]             NVARCHAR (100)  NULL,
    [Referred_Revenue_ARR__c]                    DECIMAL (18)    NULL,
    [Referred_Revenue_CMMR__c]                   DECIMAL (18)    NULL,
    [Region__c]                                  NVARCHAR (255)  NULL,
    [Registered_Advisor_Partner__c]              VARCHAR (5)     NULL,
    [Registration_Date__c]                       DATETIME        NULL,
    [Reimbursement_Method__c]                    NVARCHAR (255)  NULL,
    [Remove_from_Nuturing__c]                    NVARCHAR (255)  NULL,
    [Renewal_Program__c]                         NVARCHAR (255)  NULL,
    [Renewal_Targeting__c]                       NVARCHAR (255)  NULL,
    [Report_Administrator__c]                    NCHAR (18)      NULL,
    [Report_Analytic__c]                         NVARCHAR (255)  NULL,
    [Reporting_Tier__c]                          NVARCHAR (255)  NULL,
    [Reports_Submitted__c]                       DECIMAL (18)    NULL,
    [Retain_Segmentation__c]                     VARCHAR (5)     NULL,
    [Revenue_Category__c]                        NVARCHAR (1300) NULL,
    [Revenue_Group__c]                           NVARCHAR (255)  NULL,
    [RN_Org_ID__c]                               NVARCHAR (15)   NULL,
    [rrpu__Alert_Message__c]                     NVARCHAR (255)  NULL,
    [Sales_Executive__c]                         NVARCHAR (255)  NULL,
    [SAP_Account_Executive_Name__c]              NVARCHAR (80)   NULL,
    [SAP_Account_ID__c]                          NVARCHAR (15)   NULL,
    [SAP_Account_Name__c]                        NVARCHAR (255)  NULL,
    [SAP_Account_Type__c]                        NVARCHAR (255)  NULL,
    [SAP_Business_Partner_Id__c]                 NVARCHAR (10)   NULL,
    [SAP_Buying_Product_Relationship__c]         NVARCHAR (255)  NULL,
    [SAP_Customer_ID__c]                         NVARCHAR (99)   NULL,
    [SAP_Data_Verified_Date__c]                  DATETIME        NULL,
    [SAP_Expense_Customer__c]                    NVARCHAR (255)  NULL,
    [SAP_Export_Compliance_Screening__c]         DATETIME        NULL,
    [SAP_Financial_Customer__c]                  NVARCHAR (255)  NULL,
    [SAP_Global_Group_ID__c]                     NVARCHAR (80)   NULL,
    [SAP_Global_Ultimate_Account_ID__c]          NVARCHAR (25)   NULL,
    [SAP_Global_Ultimate_Roll_Up__c]             NVARCHAR (99)   NULL,
    [SAP_Internal_Account_Classification__c]     NVARCHAR (255)  NULL,
    [SAP_Market_Region__c]                       NVARCHAR (99)   NULL,
    [SAP_Market_Unit__c]                         NVARCHAR (99)   NULL,
    [SAP_Master_Code__c]                         NVARCHAR (99)   NULL,
    [SAP_Max_Attention__c]                       NVARCHAR (255)  NULL,
    [SAP_Planning_Entity__c]                     VARCHAR (5)     NULL,
    [SAP_Planning_Entity_Account_Executive__c]   NVARCHAR (255)  NULL,
    [SAP_Planning_Entity_Account_ID__c]          NVARCHAR (55)   NULL,
    [SAP_Planning_Entity_Account_Owner__c]       NVARCHAR (255)  NULL,
    [SAP_Planning_Entity_IAC__c]                 NVARCHAR (255)  NULL,
    [SAP_Planning_Entity_Name__c]                NVARCHAR (255)  NULL,
    [SAP_Planning_Group__c]                      NVARCHAR (100)  NULL,
    [SAP_Planning_PE_Locked__c]                  NVARCHAR (255)  NULL,
    [SAP_Planning_Refresh_Date__c]               DATETIME        NULL,
    [SAP_Previous_CY_IAC__c]                     NVARCHAR (99)   NULL,
    [SAP_Previous_Year_PE_ID_Locked__c]          NVARCHAR (80)   NULL,
    [SAP_Regional_Buying_Classification__c]      NVARCHAR (80)   NULL,
    [SAP_Sales_Group__c]                         NVARCHAR (80)   NULL,
    [SAP_Sales_Office__c]                        NVARCHAR (80)   NULL,
    [SAP_Segment_Alignment__c]                   NVARCHAR (1300) NULL,
    [Secondary_SAP_Business_Partner_Id__c]       NVARCHAR (255)  NULL,
    [Segment__c]                                 NVARCHAR (255)  NULL,
    [Service_Account_Team__c]                    NCHAR (18)      NULL,
    [Service_Account_Team_Name__c]               NVARCHAR (60)   NULL,
    [Service_Account_Team_Segment__c]            NVARCHAR (255)  NULL,
    [Service_Address_City__c]                    NVARCHAR (80)   NULL,
    [Service_Address_Country__c]                 NVARCHAR (255)  NULL,
    [Service_Address_County__c]                  NVARCHAR (80)   NULL,
    [Service_Address_State__c]                   NVARCHAR (60)   NULL,
    [Service_Address_Street_1__c]                NVARCHAR (140)  NULL,
    [Service_Address_Street_2__c]                NVARCHAR (140)  NULL,
    [Service_Address_Zip__c]                     NVARCHAR (40)   NULL,
    [Service_Administration__c]                  NVARCHAR (255)  NULL,
    [Service_Email__c]                           NVARCHAR (80)   NULL,
    [Service_Fax__c]                             NVARCHAR (40)   NULL,
    [Service_First_Name__c]                      NVARCHAR (40)   NULL,
    [Service_Last_Name__c]                       NVARCHAR (80)   NULL,
    [Service_Model__c]                           NVARCHAR (255)  NULL,
    [Service_Telephone__c]                       NVARCHAR (40)   NULL,
    [ShippingCity]                               NVARCHAR (40)   NULL,
    [ShippingCountry]                            NVARCHAR (80)   NULL,
    [ShippingPostalCode]                         NVARCHAR (20)   NULL,
    [ShippingState]                              NVARCHAR (80)   NULL,
    [ShippingStreet]                             NVARCHAR (255)  NULL,
    [Sic]                                        NVARCHAR (20)   NULL,
    [SIC_Code_temp__c]                           NVARCHAR (1300) NULL,
    [SIC_Description__c]                         NCHAR (18)      NULL,
    [Site]                                       NVARCHAR (80)   NULL,
    [Size_category__c]                           NVARCHAR (1300) NULL,
    [SOSAO__SecondAccountOwner__c]               NCHAR (18)      NULL,
    [SOSAO__X2nd_Account_Owner__c]               NVARCHAR (1300) NULL,
    [Status__c]                                  NVARCHAR (255)  NULL,
    [Success_Plan_Count__c]                      DECIMAL (18)    NULL,
    [Suggested_Owner__c]                         NVARCHAR (100)  NULL,
    [Support_Status__c]                          NVARCHAR (100)  NULL,
    [SystemModstamp]                             DATETIME        NOT NULL,
    [T_Cs_Accepted__c]                           DATETIME        NULL,
    [T_E_Company_Compliance__c]                  NVARCHAR (255)  NULL,
    [T_E_Policy_Education_Frequency__c]          NVARCHAR (255)  NULL,
    [T_E_Shared_Service_Centre__c]               NVARCHAR (255)  NULL,
    [Target_Account__c]                          VARCHAR (5)     NULL,
    [Target_Account_Partner__c]                  VARCHAR (5)     NULL,
    [Target_Account_Travel__c]                   VARCHAR (5)     NULL,
    [Target_Assignment_Date__c]                  DATETIME        NULL,
    [Targeted_By__c]                             NVARCHAR (255)  NULL,
    [Tax_Exemption_Claimed__c]                   VARCHAR (5)     NULL,
    [Tax_ID_Number__c]                           NVARCHAR (20)   NULL,
    [Termination_Notice_Period__c]               NVARCHAR (255)  NULL,
    [Territory_Helper__c]                        NVARCHAR (255)  NULL,
    [Ticker_Symbol__c]                           NVARCHAR (30)   NULL,
    [TickerSymbol]                               NVARCHAR (20)   NULL,
    [Time_Management_Provider_Solution__c]       NVARCHAR (255)  NULL,
    [Time_Zone__c]                               NVARCHAR (255)  NULL,
    [Timeframe_T_E_Solution__c]                  NVARCHAR (255)  NULL,
    [TMC_Comments__c]                            NVARCHAR (255)  NULL,
    [TMC_Travel_Agency__c]                       NVARCHAR (255)  NULL,
    [TMC_Travel_Agency_2nd__c]                   NVARCHAR (255)  NULL,
    [TMC_Travel_Agency_Contract_Exp_Date__c]     DATETIME        NULL,
    [TMC_Travel_Agency_Other__c]                 NVARCHAR (200)  NULL,
    [Toll_Free__c]                               NVARCHAR (40)   NULL,
    [Toll_Free_2__c]                             NVARCHAR (40)   NULL,
    [Total_Added_Users__c]                       DECIMAL (18)    NULL,
    [Total_Air_Spend__c]                         NVARCHAR (255)  NULL,
    [Total_Possible_Users__c]                    DECIMAL (18)    NULL,
    [Total_Users_Last_Month__c]                  DECIMAL (18)    NULL,
    [ToutApp__Tout_Last_Activity__c]             DATETIME        NULL,
    [ToutApp__Tout_Last_Engagement__c]           DATETIME        NULL,
    [ToutApp__Tout_Last_Replied__c]              DATETIME        NULL,
    [Transitioned_to_Client_Development__c]      DATETIME        NULL,
    [Travel_Account_Manager__c]                  NCHAR (18)      NULL,
    [Travel_Countries_Deployed__c]               NVARCHAR (MAX)  NULL,
    [Travel_Org_Type__c]                         NVARCHAR (255)  NULL,
    [Travel_SA__c]                               NVARCHAR (255)  NULL,
    [Travel_Service_Administration__c]           NVARCHAR (255)  NULL,
    [Travel_Support_Lead__c]                     NVARCHAR (255)  NULL,
    [Travel_Volume_Month__c]                     DECIMAL (18)    NULL,
    [Travel_Volume_Month_Band__c]                NVARCHAR (255)  NULL,
    [TripIt_for_Business__c]                     NVARCHAR (255)  NULL,
    [TripIt_For_Business_Subscription_ID__c]     NVARCHAR (50)   NULL,
    [TripIt_Pro_Rate__c]                         DECIMAL (18)    NULL,
    [TRX_Trans_Based_Revenue__c]                 DECIMAL (18, 2) NULL,
    [Type]                                       NVARCHAR (40)   NULL,
    [UK_Employees__c]                            NVARCHAR (255)  NULL,
    [UK_Postal_Code__c]                          NVARCHAR (1300) NULL,
    [UK_Primary_SIC_Code__c]                     NVARCHAR (25)   NULL,
    [UK_Registration__c]                         NVARCHAR (25)   NULL,
    [UK_Subsidiaries__c]                         DECIMAL (18)    NULL,
    [Use_a_TMC_Travel_Agency__c]                 NVARCHAR (255)  NULL,
    [Use_Travel_Requests__c]                     NVARCHAR (255)  NULL,
    [User_Support_Desk__c]                       NVARCHAR (255)  NULL,
    [VAR_Reseller__c]                            NVARCHAR (100)  NULL,
    [VAT__c]                                     NVARCHAR (255)  NULL,
    [VAT_Reclaim__c]                             NVARCHAR (255)  NULL,
    [Vertical_Grouping__c]                       NVARCHAR (255)  NULL,
    [Virtual_Account_Manager__c]                 VARCHAR (5)     NULL,
    [Web_Address_3__c]                           NVARCHAR (255)  NULL,
    [Website]                                    NVARCHAR (255)  NULL,
    [Win_Rate__c]                                DECIMAL (18, 2) NULL,
    [X18_Digit_Account_ID__c]                    NVARCHAR (1300) NULL,
    [X2nd_Acc_Owner_ID__c]                       NVARCHAR (1300) NULL,
    [X2nd_Account_Owner_Region__c]               NVARCHAR (1300) NULL,
    [X2nd_Account_Owner_Role__c]                 NVARCHAR (1300) NULL,
    [X2nd_Account_Owner_Team__c]                 NVARCHAR (1300) NULL,
    [X3_Way_Match_Invoices__c]                   NVARCHAR (255)  NULL,
    [zisf__zoom_id__c]                           NVARCHAR (20)   NULL,
    [Zuora_CMRR__c]                              DECIMAL (18, 2) NULL,
    [Zuora_Status__c]                            NVARCHAR (100)  NULL,
    [DunsNumber]                                 NVARCHAR (9)    NULL,
    [Billing_City__c]                            NVARCHAR (80)   NULL,
    [Billing_Country__c]                         NVARCHAR (255)  NULL,
    [Billing_Country_DocuSign__c]                NVARCHAR (1300) NULL,
    [Billing_County__c]                          NVARCHAR (80)   NULL,
    [Billing_St__c]                              NVARCHAR (140)  NULL,
    [Billing_St_Line_2__c]                       NVARCHAR (140)  NULL,
    [Billing_State_Province__c]                  NVARCHAR (60)   NULL,
    [Billing_Zip_Postal__c]                      NVARCHAR (40)   NULL,
    [Company_Id__c]                              NVARCHAR (255)  NULL,
    [Date_of_Authorization__c]                   DATETIME        NULL,
    [Do_Not_Merge__c]                            VARCHAR (5)     NULL,
    [Implementation_Status__c]                   NVARCHAR (255)  NULL,
    [Platinum_Elite_Date__c]                     DATETIME        NULL,
    [Current_Expense_Solution__c]                NVARCHAR (255)  NULL,
    [Current_Invoice_Solution__c]                NVARCHAR (255)  NULL,
    [Expense_Report_Volume_Month__c]             NVARCHAR (255)  NULL,
    [Invoice_Volument_Month__c]                  NVARCHAR (255)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_Entity__c1]
    ON [dbo].[Account]([Entity_ID__c] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_outtask_id]
    ON [dbo].[Account]([Outtask_ID__c] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_HMC_Entity_id]
    ON [dbo].[Account]([HMC_Entity__c] ASC);


GO
CREATE NONCLUSTERED INDEX [idx_website]
    ON [dbo].[Account]([Website] ASC);


GO
CREATE NONCLUSTERED INDEX [idx_ownerid]
    ON [dbo].[Account]([OwnerId] ASC);


GO
CREATE NONCLUSTERED INDEX [NONCLUSTERED_Acct_DUNS, sysname,>]
    ON [dbo].[Account]([DunsNumber] ASC);


GO
CREATE NONCLUSTERED INDEX [NONCLUSTERED_Acct_NAME_IncDUNS >]
    ON [dbo].[Account]([Name] ASC)
    INCLUDE([DunsNumber]);


GO
CREATE NONCLUSTERED INDEX [HMC_Entity__c_Type]
    ON [dbo].[Account]([HMC_Entity__c] ASC, [Type] ASC);


GO
CREATE NONCLUSTERED INDEX [Outtask_ID__c_Type]
    ON [dbo].[Account]([Outtask_ID__c] ASC, [Type] ASC);


GO
CREATE NONCLUSTERED INDEX [Account_site_type]
    ON [dbo].[Account]([Site] ASC, [Type] ASC)
    INCLUDE([Account_Owner_ID__c], [Account_Status__c], [AccountStatus__c], [Acct_Owner_Business_Unit__c], [Billing_Contact__c], [Billing_Contact_Email__c], [Billing_Email__c], [Contract_Termination_Date__c], [Data_Center__c], [HMC_Entity__c], [Id], [Opportunities__c], [Opportunities_Won__c], [OwnerId], [RecordTypeId], [SAP_Account_ID__c], [SAP_Business_Partner_Id__c], [SAP_Planning_Entity__c], [SAP_Planning_Entity_Account_ID__c], [SAP_Planning_Entity_Name__c], [Service_Model__c], [TMC_Comments__c], [TMC_Travel_Agency__c], [Travel_Org_Type__c], [Billing_City__c]);


GO
CREATE NONCLUSTERED INDEX [Account_Type_AddressFields]
    ON [dbo].[Account]([Type] ASC)
    INCLUDE([AKA_Company_Name__c], [CreatedDate], [Customer_Since__c], [Id], [Name], [Service_Address_City__c], [Service_Address_Country__c], [Service_Address_State__c], [Service_Address_Street_1__c], [Service_Address_Street_2__c], [Service_Address_Zip__c]);

