CREATE TABLE [dbo].[BigMachines__Quote__c] (
    [Applied_Promotion__c]             NVARCHAR (255)  NULL,
    [Approval_Date__c]                 DATETIME2 (7)   NULL,
    [ARR__c]                           DECIMAL (18, 2) NULL,
    [BigMachines__Account__c]          NCHAR (18)      NULL,
    [BigMachines__Description__c]      NVARCHAR (255)  NULL,
    [BigMachines__Is_Forced_Sync__c]   VARCHAR (5)     NULL,
    [BigMachines__Is_Primary__c]       VARCHAR (5)     NULL,
    [BigMachines__Line_Items__c]       DECIMAL (18)    NULL,
    [BigMachines__Opportunity__c]      NCHAR (18)      NULL,
    [BigMachines__Prep_Sync__c]        VARCHAR (5)     NULL,
    [BigMachines__Pricebook_Id__c]     NVARCHAR (18)   NULL,
    [BigMachines__Process_Sync__c]     VARCHAR (5)     NULL,
    [BigMachines__Status__c]           NVARCHAR (80)   NULL,
    [BigMachines__Total__c]            DECIMAL (18, 2) NULL,
    [BigMachines__Transaction_Id__c]   NVARCHAR (30)   NULL,
    [Billing_Cycle__c]                 NVARCHAR (255)  NULL,
    [Billing_Geocode__c]               NVARCHAR (140)  NULL,
    [BSA_Region__c]                    NVARCHAR (255)  NULL,
    [BSA_Source__c]                    NVARCHAR (255)  NULL,
    [BSA_Type__c]                      NVARCHAR (255)  NULL,
    [CFO_Approval_Status__c]           NVARCHAR (25)   NULL,
    [Contract_Approved__c]             VARCHAR (5)     NULL,
    [Contract_Renewal_Date__c]         DATETIME2 (7)   NULL,
    [Contract_Source__c]               NVARCHAR (255)  NULL,
    [Contract_Type__c]                 NVARCHAR (255)  NULL,
    [Contracting_Entity__c]            NVARCHAR (255)  NULL,
    [Country_Scope__c]                 NVARCHAR (255)  NULL,
    [CreatedById]                      NCHAR (18)      NULL,
    [CreatedDate]                      DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                  NVARCHAR (3)    NULL,
    [Customer_Currency__c]             NVARCHAR (255)  NULL,
    [Customer_Region__c]               NVARCHAR (255)  NULL,
    [Email__c]                         NVARCHAR (80)   NULL,
    [Expiration_Date__c]               DATETIME2 (7)   NULL,
    [Ext_Net_Price_Non_Unified_USD__c] DECIMAL (18, 2) NULL,
    [Governing_Law__c]                 NVARCHAR (255)  NULL,
    [Id]                               NCHAR (18)      NOT NULL,
    [Invoice_Language__c]              NVARCHAR (255)  NULL,
    [Invoicing_First_Name__c]          NVARCHAR (80)   NULL,
    [Invoicing_Last_Name__c]           NVARCHAR (80)   NULL,
    [Is_Quote_Stuck_in_Pending__c]     VARCHAR (5)     NULL,
    [IsDeleted]                        VARCHAR (5)     NOT NULL,
    [LastActivityDate]                 DATETIME2 (7)   NULL,
    [LastModifiedById]                 NCHAR (18)      NULL,
    [LastModifiedDate]                 DATETIME2 (7)   NOT NULL,
    [Mobile_Phone__c]                  NVARCHAR (50)   NULL,
    [Monthly_Waive_Period__c]          NVARCHAR (255)  NULL,
    [Name]                             NVARCHAR (80)   NULL,
    [Next_Approver__c]                 NVARCHAR (255)  NULL,
    [Next_Bill_Date__c]                DATETIME2 (7)   NULL,
    [Notice_City__c]                   NVARCHAR (80)   NULL,
    [Notice_Country__c]                NVARCHAR (255)  NULL,
    [Notice_County__c]                 NVARCHAR (80)   NULL,
    [Notice_Email__c]                  NVARCHAR (80)   NULL,
    [Notice_Fax__c]                    NVARCHAR (40)   NULL,
    [Notice_First_Name__c]             NVARCHAR (40)   NULL,
    [Notice_Geocode__c]                NVARCHAR (140)  NULL,
    [Notice_Last_Name__c]              NVARCHAR (80)   NULL,
    [Notice_St__c]                     NVARCHAR (140)  NULL,
    [Notice_St_Line_2__c]              NVARCHAR (140)  NULL,
    [Notice_State_Province__c]         NVARCHAR (60)   NULL,
    [Notice_Telephone__c]              NVARCHAR (40)   NULL,
    [Notice_Zip_Postal__c]             NVARCHAR (40)   NULL,
    [One_Time_Fee__c]                  DECIMAL (18, 2) NULL,
    [Order_Effective_Date__c]          DATETIME2 (7)   NULL,
    [Order_Type__c]                    NVARCHAR (255)  NULL,
    [OwnerId]                          NCHAR (18)      NOT NULL,
    [Payment_Method__c]                NVARCHAR (255)  NULL,
    [Payment_Terms__c]                 NVARCHAR (255)  NULL,
    [Payment_Terms_Text__c]            NVARCHAR (25)   NULL,
    [Phone__c]                         NVARCHAR (50)   NULL,
    [PO__c]                            NVARCHAR (255)  NULL,
    [PO_to_be_Issued__c]               VARCHAR (5)     NULL,
    [Pre_Production_Waive__c]          NVARCHAR (255)  NULL,
    [Prepared_by__c]                   NVARCHAR (255)  NULL,
    [Quote_Created_Date__c]            DATETIME2 (7)   NULL,
    [Quote_Type__c]                    NVARCHAR (255)  NULL,
    [RecordTypeId]                     NCHAR (18)      NULL,
    [Revision_Number__c]               DECIMAL (18)    NULL,
    [Service_City__c]                  NVARCHAR (80)   NULL,
    [Service_Country__c]               NVARCHAR (255)  NULL,
    [Service_County__c]                NVARCHAR (80)   NULL,
    [Service_Email__c]                 NVARCHAR (80)   NULL,
    [Service_Fax__c]                   NVARCHAR (40)   NULL,
    [Service_First_Name__c]            NVARCHAR (40)   NULL,
    [Service_Geocode__c]               NVARCHAR (140)  NULL,
    [Service_Last_Name__c]             NVARCHAR (80)   NULL,
    [Service_St__c]                    NVARCHAR (140)  NULL,
    [Service_St_Line_2__c]             NVARCHAR (140)  NULL,
    [Service_State_Province__c]        NVARCHAR (60)   NULL,
    [Service_Telephone__c]             NVARCHAR (40)   NULL,
    [Service_Zip_Postal__c]            NVARCHAR (40)   NULL,
    [Set_Up_Fee__c]                    DECIMAL (18, 2) NULL,
    [Special_Terms__c]                 NVARCHAR (1000) NULL,
    [Submit_Order_Date__c]             NVARCHAR (50)   NULL,
    [Submitted_Date__c]                DATETIME2 (7)   NULL,
    [Systematized_Contract__c]         VARCHAR (5)     NULL,
    [SystemModstamp]                   DATETIME2 (7)   NOT NULL,
    [Tax_Exemption_Claimed__c]         VARCHAR (5)     NULL,
    [Term__c]                          NVARCHAR (255)  NULL,
    [Term_Notice__c]                   NVARCHAR (255)  NULL,
    [Termination_Notice_Period__c]     NVARCHAR (255)  NULL,
    [Title__c]                         NVARCHAR (255)  NULL,
    [Total_Sales_ARR__c]               DECIMAL (18, 2) NULL,
    [VAT__c]                           NVARCHAR (255)  NULL,
    CONSTRAINT [PK_BigMachines__Quote__c_Id] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100)
);

