CREATE TABLE [dbo].[Client_Disconnect__c] (
    [Account__c]                                 NCHAR (18)      NULL,
    [Account_Manager__c]                         NCHAR (18)      NULL,
    [Account_Type__c]                            NVARCHAR (255)  NULL,
    [ADP_Company_Code__c]                        NVARCHAR (30)   NULL,
    [ADP_Disconnection_Status_Code__c]           NVARCHAR (255)  NULL,
    [ADP_Percentage_of_Setup_Complete__c]        DECIMAL (18, 2) NULL,
    [Approval_Status__c]                         NVARCHAR (255)  NULL,
    [Business_Unit__c]                           NVARCHAR (1300) NULL,
    [CD_Completed_Date__c]                       DATETIME2 (7)   NULL,
    [CD_Final_Approval_Date__c]                  DATETIME2 (7)   NULL,
    [CD_Submitted_Date__c]                       DATETIME2 (7)   NULL,
    [Cliqbook_Site_Name_s__c]                    NVARCHAR (255)  NULL,
    [Comments__c]                                NVARCHAR (2000) NULL,
    [Competitor__c]                              NVARCHAR (255)  NULL,
    [Competitor_Solution_Moving_To_Other__c]     NVARCHAR (255)  NULL,
    [Concur_Travel_Site_Names__c]                NVARCHAR (255)  NULL,
    [Contains_desired_Date_of_Termination__c]    NVARCHAR (255)  NULL,
    [Contains_Service_being_Terminated__c]       NVARCHAR (255)  NULL,
    [Contract_Source__c]                         NVARCHAR (255)  NULL,
    [Conversion_to_another_TMC__c]               NVARCHAR (255)  NULL,
    [CreatedById]                                NCHAR (18)      NULL,
    [CreatedDate]                                DATETIME2 (7)   NOT NULL,
    [CTE_Premier_Are_Imports_Enabled__c]         NVARCHAR (255)  NULL,
    [CTE_Premier_Credit_Card_Imports_Enabled__c] NVARCHAR (255)  NULL,
    [CTE_Premier_Exports_Extracts_Enabled__c]    NVARCHAR (255)  NULL,
    [CurrencyIsoCode]                            NVARCHAR (3)    NULL,
    [Deactivate_Cliqbook_Travel__c]              NVARCHAR (255)  NULL,
    [Director_AM_Manager__c]                     NVARCHAR (100)  NULL,
    [Disconnect_Date__c]                         DATETIME2 (7)   NULL,
    [Disconnect_Reason__c]                       NVARCHAR (255)  NULL,
    [Disconnect_Reason_Details__c]               NVARCHAR (255)  NULL,
    [Disconnect_Status__c]                       NVARCHAR (255)  NULL,
    [Disconnecting_all_Sites__c]                 NVARCHAR (255)  NULL,
    [Does_the_client_want_a_Full_DB_Extract__c]  NVARCHAR (255)  NULL,
    [Does_the_client_want_their_Images__c]       NVARCHAR (255)  NULL,
    [Expected_Disconnect_Date__c]                DATETIME2 (7)   NULL,
    [ExpenseLink_Account_ID_s__c]                NVARCHAR (100)  NULL,
    [Id]                                         NCHAR (18)      NOT NULL,
    [Is_Client_w_in_legal_right_to_terminate__c] NVARCHAR (255)  NULL,
    [Is_Dated__c]                                NVARCHAR (255)  NULL,
    [Is_on_Company_Letterhead__c]                NVARCHAR (255)  NULL,
    [Is_Signed_by_the_Client__c]                 NVARCHAR (255)  NULL,
    [Is_there_a_site_created__c]                 NVARCHAR (255)  NULL,
    [IsDeleted]                                  VARCHAR (5)     NOT NULL,
    [Jira_ID__c]                                 NVARCHAR (255)  NULL,
    [LastActivityDate]                           DATETIME2 (7)   NULL,
    [LastModifiedById]                           NCHAR (18)      NULL,
    [LastModifiedDate]                           DATETIME2 (7)   NOT NULL,
    [Life_Cycle_Stage__c]                        NVARCHAR (255)  NULL,
    [Lost_ARR__c]                                DECIMAL (18)    NULL,
    [Name]                                       NVARCHAR (80)   NULL,
    [New_OBT__c]                                 NVARCHAR (255)  NULL,
    [New_Opportunity__c]                         NCHAR (18)      NULL,
    [New_TMC__c]                                 NVARCHAR (255)  NULL,
    [Notification_within_Contract_terms__c]      NVARCHAR (255)  NULL,
    [Oracle_ID__c]                               NVARCHAR (45)   NULL,
    [Original_Opportunity__c]                    NCHAR (18)      NULL,
    [Original_Order_Date__c]                     DATETIME2 (7)   NULL,
    [OwnerId]                                    NCHAR (18)      NOT NULL,
    [Pending_Approval_from__c]                   NVARCHAR (255)  NULL,
    [Premier_Account__c]                         VARCHAR (5)     NULL,
    [Pro_CD_Shipped_Date__c]                     DATETIME2 (7)   NULL,
    [Pro_CD_Tracking_Number__c]                  NVARCHAR (100)  NULL,
    [Pro_Company_ID__c]                          NVARCHAR (100)  NULL,
    [Pro_Did_they_order_the_CD__c]               NVARCHAR (255)  NULL,
    [Pro_Is_the_cd_billable__c]                  NVARCHAR (255)  NULL,
    [Pro_Oracle_Billing_ID__c]                   NVARCHAR (100)  NULL,
    [Pro_RN_Ticket_Reference_Number__c]          NVARCHAR (100)  NULL,
    [Production_Entity_ID_for_CTE_Premier__c]    NVARCHAR (80)   NULL,
    [RecordTypeId]                               NCHAR (18)      NULL,
    [Region__c]                                  NVARCHAR (1300) NULL,
    [Requestor__c]                               NCHAR (18)      NULL,
    [Retained_Revenue__c]                        DECIMAL (18, 2) NULL,
    [Segment__c]                                 NVARCHAR (1300) NULL,
    [Service_Model__c]                           NVARCHAR (255)  NULL,
    [Service_Type__c]                            NTEXT           NULL,
    [Service_Type_Disconnect_Date__c]            DATETIME2 (7)   NULL,
    [Sub_Status__c]                              NVARCHAR (255)  NULL,
    [SystemModstamp]                             DATETIME2 (7)   NOT NULL,
    [Termination_Notice_Date__c]                 DATETIME2 (7)   NULL,
    [Termination_Notice_or_Agreement__c]         NVARCHAR (255)  NULL,
    [TMC_Account__c]                             NVARCHAR (255)  NULL,
    [Total_Lost_Revenue__c]                      DECIMAL (18)    NULL,
    [Verification_from_Concur_Legal__c]          NVARCHAR (255)  NULL,
    [View_Only_End_Date__c]                      DATETIME2 (7)   NULL,
    [View_Only_Start_Date__c]                    DATETIME2 (7)   NULL,
    [View_Only_Status_Complete__c]               NVARCHAR (255)  NULL,
    [What_did_we_do_to_try_to_save_them__c]      NVARCHAR (255)  NULL,
    [Company_Acquiring_Disconnect_Client__c]     NCHAR (18)      NULL,
    [Specific_Feature__c]                        NVARCHAR (255)  NULL,
    [Disconnect_Sub_Reason__c]                   NVARCHAR (255)  NULL,
    CONSTRAINT [PK_Client_Disconnect__c_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);

