CREATE TABLE [dbo].[Contact_6DF2F9A6-EBAC-4FE3-8596-F4766396FC4B] (
    [Id]                                  NCHAR (18)      NOT NULL,
    [Account_Manager__c]                  NVARCHAR (1300) NULL,
    [Account_Owner__c]                    NVARCHAR (150)  NULL,
    [Account_Type__c]                     NVARCHAR (1300) NULL,
    [AccountId]                           NCHAR (18)      NULL,
    [Active_Concur_Star__c]               VARCHAR (5)     NULL,
    [Activities_Since_Most_Recent_MQL__c] DECIMAL (18)    NULL,
    [Analyst_Reference_Contact__c]        VARCHAR (5)     NULL,
    [Are_you_a_Ceridian_customer__c]      VARCHAR (5)     NULL,
    [Assigned_Account_MDR__c]             NVARCHAR (1300) NULL,
    [AssistantName]                       NVARCHAR (40)   NULL,
    [AssistantPhone]                      NVARCHAR (40)   NULL,
    [Billing_City__c]                     NVARCHAR (80)   NULL,
    [Billing_Country__c]                  NVARCHAR (255)  NULL,
    [Billing_St__c]                       NVARCHAR (140)  NULL,
    [Billing_St_Line_2__c]                NVARCHAR (140)  NULL,
    [Billing_State_Province__c]           NVARCHAR (80)   NULL,
    [Billing_Zip_Postal__c]               NVARCHAR (20)   NULL,
    [Breeze_CID__c]                       NVARCHAR (100)  NULL,
    [Breeze_Last_CID__c]                  NVARCHAR (100)  NULL,
    [Breeze_Last_Lead_Source__c]          NVARCHAR (100)  NULL,
    [Breeze_Lead_Source__c]               NVARCHAR (100)  NULL,
    [Buying_Role__c]                      NVARCHAR (255)  NULL,
    [Case_Study_Available__c]             VARCHAR (5)     NULL,
    [Case_Study_Willing__c]               VARCHAR (5)     NULL,
    [Certified__c]                        NVARCHAR (255)  NULL,
    [CleanStatus]                         NVARCHAR (40)   NULL,
    [Closed_Case_Survey_Opt_In__c]        VARCHAR (5)     NULL,
    [Closed_Explanation__c]               NVARCHAR (255)  NULL,
    [Closed_Not_Won_Reason__c]            NVARCHAR (255)  NULL,
    [Cold_Call_Target__c]                 VARCHAR (5)     NULL,
    [Company__c]                          NVARCHAR (1300) NULL,
    [Competitive_Loss_Explanation__c]     NVARCHAR (255)  NULL,
    [Contact_Filter__c]                   NVARCHAR (100)  NULL,
    [Contact_Status__c]                   NVARCHAR (255)  NULL,
    [Contact_Title__c]                    NVARCHAR (255)  NULL,
    [Corp_NPS_Completed__c]               DECIMAL (18)    NULL,
    [Count_Contacts__c]                   DECIMAL (18)    NULL,
    [Created_by_Role__c]                  NVARCHAR (1300) NULL,
    [CreatedById]                         NCHAR (18)      NULL,
    [CreatedDate]                         DATETIME2 (7)   NOT NULL,
    [CRM__c]                              NVARCHAR (1300) NULL,
    [Date_Stamp_Closed_Not_Won__c]        DATETIME2 (7)   NULL,
    [Date_Stamp_Closed_Won__c]            DATETIME2 (7)   NULL,
    [Date_Stamp_Closing__c]               DATETIME2 (7)   NULL,
    [Date_Stamp_Demo_Proposal__c]         DATETIME2 (7)   NULL,
    [Date_Stamp_Discovery__c]             DATETIME2 (7)   NULL,
    [Date_Stamp_Inquiry__c]               DATETIME2 (7)   NULL,
    [Date_Stamp_MDR_Working__c]           DATETIME2 (7)   NULL,
    [Date_Stamp_Most_Recent_MQL__c]       DATETIME2 (7)   NULL,
    [Date_Stamp_MQL__c]                   DATETIME2 (7)   NULL,
    [Date_Stamp_Recycle__c]               DATETIME2 (7)   NULL,
    [Date_Stamp_Sales__c]                 DATETIME2 (7)   NULL,
    [Date_Stamp_Sales_Working__c]         DATETIME2 (7)   NULL,
    [Date_Stamp_Suspect__c]               DATETIME2 (7)   NULL,
    [Date_Stamp_Trash__c]                 DATETIME2 (7)   NULL,
    [Date_Stamp_VOC__c]                   DATETIME2 (7)   NULL,
    [Department]                          NVARCHAR (80)   NULL,
    [Do_Not_Mail__c]                      VARCHAR (5)     NULL,
    [Do_not_Solicit__c]                   VARCHAR (5)     NULL,
    [DoNotCall]                           VARCHAR (5)     NOT NULL,
    [Email]                               NVARCHAR (80)   NULL,
    [ET_Subscriber_Key__c]                NVARCHAR (1300) NULL,
    [FirstName]                           NVARCHAR (40)   NULL,
    [Functional_Role__c]                  NVARCHAR (255)  NULL,
    [HasOptedOutOfEmail]                  VARCHAR (5)     NOT NULL,
    [HasOptedOutOfFax]                    VARCHAR (5)     NOT NULL,
    [HomePhone]                           NVARCHAR (40)   NULL,
    [int_level__c]                        NVARCHAR (255)  NULL,
    [int_score__c]                        DECIMAL (18)    NULL,
    [Is_Service_Authorized__c]            VARCHAR (5)     NULL,
    [IsDeleted]                           VARCHAR (5)     NOT NULL,
    [Last_Activity_Date_Since_MQL__c]     DATETIME2 (7)   NULL,
    [Last_NPS_Completed_Date__c]          DATETIME2 (7)   NULL,
    [Last_NPS_Score__c]                   DECIMAL (18)    NULL,
    [Last_NPS_Sent_Date__c]               DATETIME2 (7)   NULL,
    [last_scored__c]                      DATETIME2 (7)   NULL,
    [LastActivityDate]                    DATETIME2 (7)   NULL,
    [LastModifiedById]                    NCHAR (18)      NULL,
    [LastModifiedDate]                    DATETIME2 (7)   NOT NULL,
    [LastName]                            NVARCHAR (80)   NOT NULL,
    [lead_score__c]                       NVARCHAR (255)  NULL,
    [LeadSource]                          NVARCHAR (40)   NULL,
    [LinkedIn_User_Group_Join_Date__c]    DATETIME2 (7)   NULL,
    [MasterRecordId]                      NCHAR (18)      NULL,
    [MD_Comments__c]                      NVARCHAR (1300) NULL,
    [MDR_Working_Nurture_Removal__c]      NVARCHAR (255)  NULL,
    [Media_Use__c]                        VARCHAR (5)     NULL,
    [Member_ID__c]                        NVARCHAR (18)   NULL,
    [Member_Type__c]                      NVARCHAR (255)  NULL,
    [Name]                                NVARCHAR (121)  NOT NULL,
    [NPS_Contact__c]                      VARCHAR (5)     NULL,
    [NPS_Frequency__c]                    NVARCHAR (255)  NULL,
    [NPS_Opt_Out__c]                      VARCHAR (5)     NULL,
    [Opportunities_Account__c]            DECIMAL (18)    NULL,
    [Opportunities_Open_Account__c]       DECIMAL (18)    NULL,
    [Original_CID__c]                     NVARCHAR (100)  NULL,
    [Original_PID__c]                     NVARCHAR (100)  NULL,
    [OwnerId]                             NCHAR (18)      NOT NULL,
    [Phone]                               NVARCHAR (40)   NULL,
    [PortalUserType__c]                   NVARCHAR (255)  NULL,
    [Preferred_Contact_Method__c]         NVARCHAR (255)  NULL,
    [Press_Reference__c]                  VARCHAR (5)     NULL,
    [Primary_Buyer_Expense__c]            VARCHAR (5)     NULL,
    [Primary_Buyer_Invoice__c]            VARCHAR (5)     NULL,
    [Primary_Buyer_Travel__c]             VARCHAR (5)     NULL,
    [Product_Updates_Notifications__c]    VARCHAR (5)     NULL,
    CONSTRAINT [pk_Contact_6DF2F9A6-EBAC-4FE3-8596-F4766396FC4B] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (DATA_COMPRESSION = PAGE)
);

