CREATE TABLE [dbo].[Credit_Memo__c] (
    [Approval_Level__c]                NVARCHAR (255)  NULL,
    [Approved_level__c]                NVARCHAR (255)  NULL,
    [Billing_ID__c]                    NVARCHAR (20)   NULL,
    [Billing_Processor__c]             NCHAR (18)      NULL,
    [Billing_System__c]                NVARCHAR (255)  NULL,
    [Business_Unit__c]                 NVARCHAR (255)  NULL,
    [Client_Name__c]                   NCHAR (18)      NULL,
    [CM_Accounting_Completion_Date__c] DATETIME        NULL,
    [CM_Adjustment__c]                 VARCHAR (5)     NOT NULL,
    [CM_Final_Approval_Date__c]        DATETIME        NULL,
    [CM_Process_Name__c]               NVARCHAR (255)  NULL,
    [CM_Processed_Date__c]             DATETIME        NULL,
    [CM_Submitted_Date__c]             DATETIME        NULL,
    [CreatedById]                      NCHAR (18)      NULL,
    [CreatedDate]                      DATETIME        NOT NULL,
    [Credit_Amount__c]                 DECIMAL (18, 2) NULL,
    [Credit_Reason_Category__c]        NVARCHAR (255)  NULL,
    [Credit_Reason_Code__c]            NVARCHAR (255)  NULL,
    [Credit_Reason_Description__c]     NVARCHAR (MAX)  NULL,
    [CurrencyIsoCode]                  NVARCHAR (3)    NULL,
    [GL_Date__c]                       DATETIME        NULL,
    [Id]                               NCHAR (18)      NOT NULL,
    [IsDeleted]                        VARCHAR (5)     NOT NULL,
    [LastActivityDate]                 DATETIME        NULL,
    [LastModifiedById]                 NCHAR (18)      NULL,
    [LastModifiedDate]                 DATETIME        NOT NULL,
    [Name]                             NVARCHAR (80)   NULL,
    [New_Invoice_Amount__c]            DECIMAL (18, 2) NULL,
    [New_Invoice_Currency_Type__c]     NVARCHAR (255)  NULL,
    [New_Invoice_Number__c]            NVARCHAR (20)   NULL,
    [Overall_Status__c]                NVARCHAR (255)  NULL,
    [Owner__c]                         NCHAR (18)      NULL,
    [Rebill__c]                        NVARCHAR (255)  NULL,
    [Service_Model__c]                 NVARCHAR (255)  NULL,
    [Sub_Status__c]                    NVARCHAR (255)  NULL,
    [Submitted_By__c]                  NVARCHAR (255)  NULL,
    [Submitted_By_Role__c]             NVARCHAR (255)  NULL,
    [SystemModstamp]                   DATETIME        NOT NULL,
    [Sub_Credit_Reason_Code__c]        NVARCHAR (255)  NULL,
    CONSTRAINT [PK_Credit_Memo__c] PRIMARY KEY CLUSTERED ([Id] ASC)
);

