CREATE TABLE [dbo].[DandBCompany] (
    [CompanyCurrencyIsoCode]       NVARCHAR (255)  NULL,
    [CountryAccessCode]            NVARCHAR (4)    NULL,
    [CurrencyCode]                 NVARCHAR (255)  NULL,
    [CurrencyIsoCode]              NVARCHAR (3)    NULL,
    [Description]                  NTEXT           NULL,
    [DomesticUltimateBusinessName] NVARCHAR (255)  NULL,
    [DomesticUltimateDunsNumber]   NVARCHAR (9)    NULL,
    [DunsNumber]                   NVARCHAR (9)    NULL,
    [EmployeesHere]                DECIMAL (18)    NULL,
    [EmployeesHereReliability]     NVARCHAR (255)  NULL,
    [EmployeesTotal]               DECIMAL (18)    NULL,
    [EmployeesTotalReliability]    NVARCHAR (255)  NULL,
    [Fax]                          NVARCHAR (40)   NULL,
    [GeoCodeAccuracy]              NVARCHAR (255)  NULL,
    [GlobalUltimateBusinessName]   NVARCHAR (255)  NULL,
    [GlobalUltimateDunsNumber]     NVARCHAR (9)    NULL,
    [GlobalUltimateTotalEmployees] DECIMAL (18)    NULL,
    [Id]                           NCHAR (18)      NOT NULL,
    [IncludedInSnP500]             NVARCHAR (10)   NULL,
    [Latitude]                     NVARCHAR (11)   NULL,
    [LegalStatus]                  NVARCHAR (255)  NULL,
    [LocationStatus]               NVARCHAR (255)  NULL,
    [Longitude]                    NVARCHAR (11)   NULL,
    [MailingCity]                  NVARCHAR (40)   NULL,
    [MailingCountry]               NVARCHAR (80)   NULL,
    [MailingGeocodeAccuracy]       NVARCHAR (255)  NULL,
    [MailingPostalCode]            NVARCHAR (20)   NULL,
    [MailingState]                 NVARCHAR (80)   NULL,
    [MailingStreet]                NVARCHAR (255)  NULL,
    [MarketingSegmentationCluster] NVARCHAR (255)  NULL,
    [Name]                         NVARCHAR (255)  NULL,
    [NationalId]                   NVARCHAR (255)  NULL,
    [NationalIdType]               NVARCHAR (255)  NULL,
    [OutOfBusiness]                NVARCHAR (255)  NULL,
    [OwnOrRent]                    NVARCHAR (255)  NULL,
    [ParentOrHqBusinessName]       NVARCHAR (255)  NULL,
    [ParentOrHqDunsNumber]         NVARCHAR (9)    NULL,
    [Phone]                        NVARCHAR (40)   NULL,
    [PrimaryNaics]                 NVARCHAR (6)    NULL,
    [PrimaryNaicsDesc]             NVARCHAR (120)  NULL,
    [PrimarySic]                   NVARCHAR (4)    NULL,
    [PrimarySic8]                  NVARCHAR (8)    NULL,
    [PrimarySic8Desc]              NVARCHAR (80)   NULL,
    [PrimarySicDesc]               NVARCHAR (80)   NULL,
    [PriorYearEmployees]           INT             NULL,
    [PriorYearRevenue]             DECIMAL (18)    NULL,
    [PublicIndicator]              NVARCHAR (255)  NULL,
    [SalesVolume]                  DECIMAL (18)    NULL,
    [SalesVolumeReliability]       NVARCHAR (255)  NULL,
    [SmallBusiness]                NVARCHAR (255)  NULL,
    [StockExchange]                NVARCHAR (16)   NULL,
    [StockSymbol]                  NVARCHAR (6)    NULL,
    [Subsidiary]                   NVARCHAR (255)  NULL,
    [SystemModstamp]               DATETIME        NOT NULL,
    [TradeStyle1]                  NVARCHAR (255)  NULL,
    [URL]                          NVARCHAR (255)  NULL,
    [UsTaxId]                      NVARCHAR (9)    NULL,
    [YearStarted]                  NVARCHAR (4)    NULL,
    [SalesTurnoverGrowthRate]      DECIMAL (18, 6) NULL,
    CONSTRAINT [PK_DandBCompany_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
    ON [dbo].[DandBCompany]([DunsNumber] ASC)
    INCLUDE([Name]);

