CREATE TABLE [dbo].[Invoice__c] (
    [CM_Number__c]             NVARCHAR (20)   NULL,
    [Consulting_Manager__c]    NCHAR (18)      NULL,
    [CreatedById]              NCHAR (18)      NULL,
    [CreatedDate]              DATETIME        NOT NULL,
    [Credit_Amount__c]         DECIMAL (18, 2) NULL,
    [Credit_Entire_Invoice__c] NVARCHAR (255)  NULL,
    [Credit_for_Expenses__c]   NVARCHAR (255)  NULL,
    [Credit_for_Labor__c]      NVARCHAR (255)  NULL,
    [Credit_Memo__c]           NCHAR (18)      NOT NULL,
    [CurrencyIsoCode]          NVARCHAR (3)    NULL,
    [Id]                       NCHAR (18)      NOT NULL,
    [Invoice_Amount__c]        DECIMAL (18, 2) NULL,
    [Invoice_Date__c]          DATETIME        NULL,
    [Invoice_Number__c]        NVARCHAR (20)   NULL,
    [Invoice_Type__c]          NVARCHAR (255)  NULL,
    [IsDeleted]                VARCHAR (5)     NOT NULL,
    [LastActivityDate]         DATETIME        NULL,
    [LastModifiedById]         NCHAR (18)      NULL,
    [LastModifiedDate]         DATETIME        NOT NULL,
    [Name]                     NVARCHAR (80)   NULL,
    [Project_Manager__c]       NCHAR (18)      NULL,
    [Project_Name__c]          NVARCHAR (255)  NULL,
    [Rebill__c]                VARCHAR (5)     NOT NULL,
    [Rebill_Invoice_Amount__c] DECIMAL (18, 2) NULL,
    [Rebill_Invoice_Number__c] NVARCHAR (20)   NULL,
    [RecordTypeId]             NCHAR (18)      NULL,
    [Service_Description__c]   NVARCHAR (MAX)  NULL,
    [Setup_Fee__c]             NVARCHAR (255)  NULL,
    [SystemModstamp]           DATETIME        NOT NULL,
    CONSTRAINT [PK_Invoice__c] PRIMARY KEY CLUSTERED ([Id] ASC)
);

