CREATE TABLE [dbo].[Lead_B5CF926F-E8C7-4FC0-9C84-F178B60CA5BE] (
    [Id]                                          NCHAR (18)       NOT NULL,
    [Aberdeen_Report_Link__c]                     NVARCHAR (255)   NULL,
    [Account_Site__c]                             NVARCHAR (80)    NULL,
    [Account_Status__c]                           NVARCHAR (255)   NULL,
    [Active_Users__c]                             DECIMAL (18)     NULL,
    [Actual_Expense_Report_Volume_Month__c]       NVARCHAR (25)    NULL,
    [Admin_Last_Login__c]                         DATETIME2 (7)    NULL,
    [Age_Inquiry__c]                              DECIMAL (18)     NULL,
    [Age_MQL__c]                                  DECIMAL (18)     NULL,
    [Age_Recycle__c]                              DECIMAL (18)     NULL,
    [Age_Suspect__c]                              DECIMAL (18)     NULL,
    [Age_Trash__c]                                DECIMAL (18)     NULL,
    [Amex_Business_Unit_ID__c]                    NVARCHAR (18)    NULL,
    [Amex_Rep_Channel__c]                         NVARCHAR (255)   NULL,
    [Amex_Rep_Country__c]                         NVARCHAR (255)   NULL,
    [Amex_Rep_Position__c]                        NVARCHAR (255)   NULL,
    [Amex_Rep_Region__c]                          NVARCHAR (255)   NULL,
    [Amex_Rep_VP_Leader__c]                       NVARCHAR (100)   NULL,
    [Amexco_Client_ID__c]                         NVARCHAR (40)    NULL,
    [Amexco_Prospect_ID__c]                       NVARCHAR (40)    NULL,
    [Annual_Meetings__c]                          NVARCHAR (255)   NULL,
    [Annual_Revenue__c]                           DECIMAL (18, 2)  NULL,
    [Annual_T_E_Spend__c]                         NVARCHAR (255)   NULL,
    [AnnualRevenue]                               DECIMAL (18)     NULL,
    [App_Center_Partner__c]                       NVARCHAR (100)   NULL,
    [Assigned_Profiler__c]                        NCHAR (18)       NULL,
    [Billing_City2__c]                            NVARCHAR (40)    NULL,
    [Billing_City__c]                             NVARCHAR (80)    NULL,
    [Billing_Country2__c]                         NVARCHAR (40)    NULL,
    [Billing_Country__c]                          NVARCHAR (255)   NULL,
    [Billing_St2__c]                              NVARCHAR (140)   NULL,
    [Billing_St__c]                               NVARCHAR (140)   NULL,
    [Billing_St_Line_2__c]                        NVARCHAR (140)   NULL,
    [Billing_State_Province2__c]                  NVARCHAR (40)    NULL,
    [Billing_State_Province__c]                   NVARCHAR (60)    NULL,
    [Billing_Zip_Postal2__c]                      NVARCHAR (20)    NULL,
    [Billing_Zip_Postal__c]                       NVARCHAR (20)    NULL,
    [Brand_Awareness__c]                          NVARCHAR (255)   NULL,
    [Breeze_Account_Stage__c]                     NVARCHAR (255)   NULL,
    [Breeze_Channel__c]                           NVARCHAR (255)   NULL,
    [Breeze_CID__c]                               NVARCHAR (100)   NULL,
    [Breeze_CID_Account__c]                       NVARCHAR (100)   NULL,
    [Breeze_Last_CID__c]                          NVARCHAR (100)   NULL,
    [Breeze_Last_Lead_Source__c]                  NVARCHAR (100)   NULL,
    [Breeze_Lead_Source__c]                       NVARCHAR (100)   NULL,
    [Breeze_Lead_Source_Account__c]               NVARCHAR (100)   NULL,
    [Breeze_Only_Referral__c]                     NVARCHAR (5)     NULL,
    [Breeze_Purchased__c]                         NVARCHAR (255)   NULL,
    [Breeze_Referral_Received__c]                 NCHAR (18)       NULL,
    [Breeze_Referral_Sent__c]                     NCHAR (18)       NULL,
    [Breeze_Representative__c]                    NCHAR (18)       NULL,
    [Breeze_Survey_Received__c]                   DATETIME2 (7)    NULL,
    [Breeze_Survey_Sent__c]                       DATETIME2 (7)    NULL,
    [Breeze_Team__c]                              NVARCHAR (255)   NULL,
    [BRNSHRK__Lead_Count__c]                      DECIMAL (18)     NULL,
    [BRNSHRK__Lead_Full_Name__c]                  NVARCHAR (1300)  NULL,
    [BUMS__c]                                     NVARCHAR (1300)  NULL,
    [Business_Need__c]                            NVARCHAR (255)   NULL,
    [Business_Unit__c]                            NVARCHAR (255)   NULL,
    [Buying_Horizon__c]                           NVARCHAR (255)   NULL,
    [cas__FirstAttempt__c]                        DATETIME2 (7)    NULL,
    [cas__LastAttempt__c]                         DATETIME2 (7)    NULL,
    [cas__NumberAttempts__c]                      DECIMAL (18)     NULL,
    [cas__NumberConnects__c]                      DECIMAL (18)     NULL,
    [City]                                        NVARCHAR (40)    NULL,
    [CleanStatus]                                 NVARCHAR (40)    NULL,
    [Client_Start_Link__c]                        NVARCHAR (1300)  NULL,
    [Comment_s__c]                                NTEXT            NULL,
    [Company]                                     NVARCHAR (255)   NOT NULL,
    [Company_Created_Date__c]                     DATETIME2 (7)    NULL,
    [Company_Launched_Y_N__c]                     NVARCHAR (255)   NULL,
    [CompanyDunsNumber]                           NVARCHAR (9)     NULL,
    [Connect_and_Sell_Status__c]                  NVARCHAR (255)   NULL,
    [Contact_Partner_Rep_Before_Calling__c]       NVARCHAR (255)   NULL,
    [Control_Costs__c]                            VARCHAR (5)      NULL,
    [Converted_By__c]                             NCHAR (18)       NULL,
    [ConvertedAccountId]                          NCHAR (18)       NULL,
    [ConvertedContactId]                          NCHAR (18)       NULL,
    [ConvertedDate]                               DATETIME2 (7)    NULL,
    [ConvertedOpportunityId]                      NCHAR (18)       NULL,
    [Country]                                     NVARCHAR (80)    NULL,
    [CreatedById]                                 NCHAR (18)       NULL,
    [CreatedDate]                                 DATETIME2 (7)    NOT NULL,
    [CRM__c]                                      NVARCHAR (255)   NULL,
    [CUID__c]                                     NVARCHAR (40)    NULL,
    [Currency__c]                                 NVARCHAR (255)   NULL,
    [CurrencyIsoCode]                             NVARCHAR (3)     NULL,
    [Current_Amex_Customer__c]                    NVARCHAR (255)   NULL,
    [Current_Booking_Process__c]                  NVARCHAR (255)   NULL,
    [Current_Booking_Solution__c]                 NVARCHAR (255)   NULL,
    [Current_Concur_Platform__c]                  NVARCHAR (255)   NULL,
    [Current_Expense_Process__c]                  NVARCHAR (255)   NULL,
    [Current_Expense_Solution__c]                 NVARCHAR (50)    NULL,
    [Current_Invoice_Process__c]                  NVARCHAR (255)   NULL,
    [Current_Invoice_Solution__c]                 NVARCHAR (255)   NULL,
    [Current_Purchase_Process__c]                 NVARCHAR (255)   NULL,
    [Current_Solutions_Supported__c]              NTEXT            NULL,
    [Current_T_E_Audit__c]                        NVARCHAR (255)   NULL,
    [Current_T_E_Solutions_Integrated__c]         NVARCHAR (255)   NULL,
    [Customer_Business_Sponsor__c]                NVARCHAR (100)   NULL,
    [Customer_Currency__c]                        NVARCHAR (3)     NULL,
    [Customer_Program_Manager_Project_Manager__c] NVARCHAR (100)   NULL,
    [Customer_SAP_CRM_BP_ID__c]                   NVARCHAR (255)   NULL,
    [DandbCompanyId]                              NCHAR (18)       NULL,
    [Data_Source__c]                              NVARCHAR (255)   NULL,
    [Date_Profiled__c]                            DATETIME2 (7)    NULL,
    [Date_Stamp_Advisor_Platinum__c]              DATETIME2 (7)    NULL,
    [Date_Stamp_Inquiry__c]                       DATETIME2 (7)    NULL,
    [Date_Stamp_MQL__c]                           DATETIME2 (7)    NULL,
    [Date_Stamp_MQL_Bridge__c]                    DATETIME2 (7)    NULL,
    [Date_Stamp_MQL_ToOpp__c]                     DATETIME2 (7)    NULL,
    [Date_Stamp_Partner_Referral__c]              DATETIME2 (7)    NULL,
    [Date_Stamp_Recycle__c]                       DATETIME2 (7)    NULL,
    [Date_Stamp_Suspect__c]                       DATETIME2 (7)    NULL,
    [Date_Stamp_Trash__c]                         DATETIME2 (7)    NULL,
    [DBA__c]                                      NVARCHAR (75)    NULL,
    [ddc_prospector__Sourced_from_Data_com__c]    NVARCHAR (1300)  NULL,
    [DDCAutoCleanLog__c]                          NTEXT            NULL,
    [DDCAutoCleanTimestamp__c]                    DATETIME2 (7)    NULL,
    [Description]                                 NTEXT            NULL,
    [Distributor__c]                              NVARCHAR (255)   NULL,
    [Do_Not_Mail__c]                              VARCHAR (5)      NULL,
    [DoNotCall]                                   VARCHAR (5)      NOT NULL,
    [Eloqua_Email__c]                             NVARCHAR (80)    NULL,
    [Eloqua_Lead_Rating__c]                       NVARCHAR (255)   NULL,
    [Eloqua_PCI_Id__c]                            NVARCHAR (255)   NULL,
    [Email]                                       NVARCHAR (80)    NULL,
    [Email_Opt_In__c]                             VARCHAR (5)      NULL,
    [EmailBouncedDate]                            DATETIME2 (7)    NULL,
    [EmailBouncedReason]                          NVARCHAR (255)   NULL,
    [Employee_ID_Code__c]                         NVARCHAR (100)   NULL,
    [Employee_Travel_Volume_Trips_per_year__c]    NVARCHAR (255)   NULL,
    [EmployeeBand__c]                             NVARCHAR (255)   NULL,
    [Employees_at_Location__c]                    DECIMAL (18)     NULL,
    [Employees_Worldwide__c]                      DECIMAL (18)     NULL,
    [Entity_ID__c]                                NVARCHAR (45)    NULL,
    [Expected_Opportunity_Close_Date__c]          DATETIME2 (7)    NULL,
    [Expected_Revenue_Quarter__c]                 DECIMAL (18, 2)  NULL,
    [Expense_Report_Filers__c]                    NVARCHAR (255)   NULL,
    [Expense_Report_Volume_Month__c]              NVARCHAR (255)   NULL,
    [Fax]                                         NVARCHAR (40)    NULL,
    [Financial_System_lead__c]                    NVARCHAR (255)   NULL,
    [Financial_System_Other__c]                   NVARCHAR (255)   NULL,
    [First_Character__c]                          NVARCHAR (1300)  NULL,
    [FirstName]                                   NVARCHAR (40)    NULL,
    [Formal_Corporate_Expense_Policy__c]          NVARCHAR (255)   NULL,
    [Free_Trial_Days_Remaining__c]                DECIMAL (18)     NULL,
    [Free_Trial_Edition__c]                       NVARCHAR (255)   NULL,
    [Free_Trial_Expiration_date__c]               DATETIME2 (7)    NULL,
    [Functional_Role__c]                          NVARCHAR (255)   NULL,
    [Functional_Role_Other__c]                    NVARCHAR (255)   NULL,
    [Gain_Visibility_into_T_E_Spend_Data__c]      VARCHAR (5)      NULL,
    [GCC_LOA_Print_Date__c]                       DATETIME2 (7)    NULL,
    [GeocodeAccuracy]                             NVARCHAR (40)    NULL,
    [Get_Started_Now__c]                          NVARCHAR (255)   NULL,
    [Global_Parent_Account__c]                    NCHAR (18)       NULL,
    [Global_Parent_DUNS__c]                       NVARCHAR (25)    NULL,
    [Government_Contact__c]                       NVARCHAR (255)   NULL,
    [HasOptedOutOfEmail]                          VARCHAR (5)      NOT NULL,
    [HasOptedOutOfFax]                            VARCHAR (5)      NOT NULL,
    [How_Pay_Expense_Reports__c]                  NVARCHAR (50)    NULL,
    [I_m_Interested_in_the_following_Solution__c] NTEXT            NULL,
    [Immediate_Parent_DUNS__c]                    NVARCHAR (25)    NULL,
    [Implementation_Plan__c]                      NVARCHAR (90)    NULL,
    [Industry]                                    NVARCHAR (40)    NULL,
    [infer2__Infer_Converted_to_Opp__c]           VARCHAR (5)      NULL,
    [infer2__Infer_Good_Lead__c]                  VARCHAR (5)      NULL,
    [infer2__Infer_Is_Open__c]                    VARCHAR (5)      NULL,
    [infer2__Infer_Lead_Age__c]                   DECIMAL (18)     NULL,
    [infer2__Infer_Lead_Created_Date__c]          DATETIME2 (7)    NULL,
    [infer2__Infer_Rating__c]                     NVARCHAR (1300)  NULL,
    [infer2__Infer_Score__c]                      DECIMAL (18)     NULL,
    [infer2__Infer_Score_ID__c]                   NCHAR (18)       NULL,
    [Infer_Rating__c]                             NVARCHAR (1300)  NULL,
    [Infer_Score__c]                              NVARCHAR (255)   NULL,
    [Infer_Score_Mirror__c]                       DECIMAL (18)     NULL,
    [int_level__c]                                NVARCHAR (255)   NULL,
    [int_score__c]                                DECIMAL (18)     NULL,
    [Interest_in_T_E_Demo__c]                     NVARCHAR (255)   NULL,
    [interest_meter__c]                           NVARCHAR (1300)  NULL,
    [Interested_in_Audit__c]                      VARCHAR (5)      NULL,
    [Interested_in_Expense__c]                    VARCHAR (5)      NULL,
    [Interested_in_Intelligence__c]               VARCHAR (5)      NULL,
    [Interested_in_Invoice__c]                    VARCHAR (5)      NULL,
    [Interested_in_Meeting__c]                    VARCHAR (5)      NULL,
    [Interested_in_Pay__c]                        VARCHAR (5)      NULL,
    [Interested_in_Travel__c]                     VARCHAR (5)      NULL,
    [Invoice_Volument_Month__c]                   NVARCHAR (255)   NULL,
    [IsConverted]                                 VARCHAR (5)      NOT NULL,
    [IsDeleted]                                   VARCHAR (5)      NOT NULL,
    [IsUnreadByOwner]                             VARCHAR (5)      NOT NULL,
    [Jigsaw]                                      NVARCHAR (20)    NULL,
    [JigsawContactId]                             NVARCHAR (20)    NULL,
    [jsImpacts__Added_from_Data_com__c]           NVARCHAR (1300)  NULL,
    [jsImpacts__Data_com_do_not_auto_update__c]   VARCHAR (5)      NULL,
    [jsImpacts__Data_com_managed__c]              DECIMAL (18)     NULL,
    [jsImpacts__Imported_from_Jigsaw__c]          DECIMAL (18)     NULL,
    [Just_Looking__c]                             VARCHAR (5)      NULL,
    [Language__c]                                 NVARCHAR (255)   NULL,
    [LastActivityDate]                            DATETIME2 (7)    NULL,
    [LastModifiedById]                            NCHAR (18)       NULL,
    [LastModifiedDate]                            DATETIME2 (7)    NOT NULL,
    [LastName]                                    NVARCHAR (80)    NOT NULL,
    [LastReferencedDate]                          DATETIME2 (7)    NULL,
    [LastTransferDate]                            DATETIME2 (7)    NULL,
    [LastViewedDate]                              DATETIME2 (7)    NULL,
    [Latitude]                                    DECIMAL (18, 15) NULL,
    [Lattice_Last_Score_Date__c]                  DATETIME2 (7)    NULL,
    [Lattice_Rating__c]                           NVARCHAR (1300)  NULL,
    CONSTRAINT [pk_Lead_B5CF926F-E8C7-4FC0-9C84-F178B60CA5BE] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (DATA_COMPRESSION = PAGE)
);

