CREATE TABLE [dbo].[OpportunityLineItem] (
    [Account_ID__c]                              NVARCHAR (1300) NULL,
    [Action__c]                                  NVARCHAR (255)  NULL,
    [Additional_Sales_Credit__c]                 DECIMAL (18)    NULL,
    [Adjustment_to_ARR__c]                       DECIMAL (18, 2) NULL,
    [ARR__c]                                     DECIMAL (18, 2) NULL,
    [ARR_by_Product__c]                          DECIMAL (18, 2) NULL,
    [Asset_Begin_Date__c]                        DATETIME2 (7)   NULL,
    [Asset_ID__c]                                NVARCHAR (50)   NULL,
    [Base_Trans_Billing_Cycle__c]                DECIMAL (18)    NULL,
    [Base_Trans_Fee_Billing_Cycle__c]            DECIMAL (18, 2) NULL,
    [Base_Trans_Fee_Billing_Cycle_Not_BMI__c]    DECIMAL (18, 2) NULL,
    [Base_Transactions_per_Billing_Cycle__c]     DECIMAL (18)    NULL,
    [BigMachines__Origin_Quote__c]               NCHAR (18)      NULL,
    [BigMachines__Synchronization_Id__c]         NVARCHAR (255)  NULL,
    [BMI_Existing_ARR__c]                        DECIMAL (18, 2) NULL,
    [BMI_Net_New_ARR__c]                         DECIMAL (18, 2) NULL,
    [BMI_Total_ARR__c]                           DECIMAL (18, 2) NULL,
    [Bundle_ID__c]                               NVARCHAR (35)   NULL,
    [Bundled_with_another_product__c]            VARCHAR (5)     NULL,
    [Business_Unit__c]                           NVARCHAR (255)  NULL,
    [Configuration_APA__c]                       NVARCHAR (255)  NULL,
    [Configuration_EMEA__c]                      NTEXT           NULL,
    [Configuration_NA__c]                        NTEXT           NULL,
    [Configuration_SMB__c]                       NTEXT           NULL,
    [Converted_to_Asset__c]                      VARCHAR (5)     NULL,
    [Core_Offering__c]                           NVARCHAR (100)  NULL,
    [CreatedById]                                NCHAR (18)      NULL,
    [CreatedDate]                                DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                            NVARCHAR (3)    NOT NULL,
    [Customer_Currency_Rev_Rec_Monthly__c]       DECIMAL (18, 2) NULL,
    [Description]                                NVARCHAR (255)  NULL,
    [Discount__c]                                DECIMAL (18, 2) NULL,
    [Extended_List_Price_Monthly__c]             DECIMAL (18, 2) NULL,
    [Extended_Net_Price__c]                      DECIMAL (18, 2) NULL,
    [Factored_Addition_Sales_Credit__c]          DECIMAL (18, 2) NULL,
    [Factored_Sales_Credit_Calculation__c]       DECIMAL (18, 2) NULL,
    [Gelco_Line_Item_ID__c]                      NVARCHAR (25)   NULL,
    [Govt_Product_Type__c]                       NVARCHAR (255)  NULL,
    [HasQuantitySchedule]                        VARCHAR (5)     NOT NULL,
    [HasRevenueSchedule]                         VARCHAR (5)     NOT NULL,
    [HasSchedule]                                VARCHAR (5)     NOT NULL,
    [Id]                                         NCHAR (18)      NOT NULL,
    [Implementation_Method__c]                   NVARCHAR (100)  NULL,
    [Incremental_Transaction_Fee_per_Increme__c] DECIMAL (18, 2) NULL,
    [Initial_Term_Date__c]                       DATETIME2 (7)   NULL,
    [Is_part_of_package__c]                      VARCHAR (5)     NULL,
    [IsDeleted]                                  VARCHAR (5)     NOT NULL,
    [Item_Type__c]                               NVARCHAR (255)  NULL,
    [LastModifiedById]                           NCHAR (18)      NULL,
    [LastModifiedDate]                           DATETIME2 (7)   NOT NULL,
    [License_Fee__c]                             DECIMAL (18, 2) NULL,
    [List_Price_Monthly__c]                      DECIMAL (18, 2) NULL,
    [ListPrice]                                  DECIMAL (18, 2) NULL,
    [Maintenance_Fee__c]                         DECIMAL (18)    NULL,
    [Maturity_Sales_Credit_Calc__c]              DECIMAL (18, 2) NULL,
    [Meeting_Transaction_Fee__c]                 DECIMAL (18, 2) NULL,
    [MN_PI_ID__c]                                NVARCHAR (30)   NULL,
    [MN_PO_ID__c]                                NVARCHAR (30)   NULL,
    [MN_Subscription_ID__c]                      NVARCHAR (30)   NULL,
    [Monthly_Base_Transaction_Fee__c]            DECIMAL (18, 2) NULL,
    [Monthly_Transactions__c]                    DECIMAL (18)    NULL,
    [Net_Price__c]                               DECIMAL (18, 2) NULL,
    [Number_of_Committed_Trnxs__c]               DECIMAL (18)    NULL,
    [Number_of_Committed_Trnxs_Billing_Cycle__c] DECIMAL (18)    NULL,
    [Number_of_Funding_Accounts__c]              NVARCHAR (255)  NULL,
    [Opportunity_Product_ID__c]                  NVARCHAR (1300) NULL,
    [Opportunity_Type__c]                        NVARCHAR (255)  NULL,
    [OpportunityId]                              NCHAR (18)      NOT NULL,
    [Package__c]                                 NVARCHAR (30)   NULL,
    [Parent_Doc_ID__c]                           NVARCHAR (25)   NULL,
    [PO_Category__c]                             NVARCHAR (255)  NULL,
    [Pre_Production_System_Fee_per_Month__c]     DECIMAL (18, 2) NULL,
    [PricebookEntryId]                           NCHAR (18)      NULL,
    [Promo_Code__c]                              NVARCHAR (255)  NULL,
    [Promo_Label__c]                             NVARCHAR (100)  NULL,
    [Promotion_Test_Offer_1__c]                  NCHAR (18)      NULL,
    [Promotion_Test_Offer_2__c]                  NCHAR (18)      NULL,
    [pse__Added_To_Project__c]                   VARCHAR (5)     NULL,
    [pse__IsServicesProductLine__c]              VARCHAR (5)     NULL,
    [Quantity]                                   DECIMAL (18, 2) NOT NULL,
    [Quote_Number__c]                            NVARCHAR (1300) NULL,
    [Ramp_Plan_Set__c]                           NCHAR (18)      NULL,
    [Ref_Contract_ID_for_Invoices__c]            NVARCHAR (25)   NULL,
    [Ref_Contract_ID_for_Invoices_MN__c]         NVARCHAR (255)  NULL,
    [Ref_Contract_ID_for_Reports__c]             NVARCHAR (255)  NULL,
    [Ref_Contract_ID_for_Reports_MN__c]          NVARCHAR (255)  NULL,
    [Sales_Commissions__c]                       NCHAR (18)      NULL,
    [Sales_Credit__c]                            DECIMAL (18)    NULL,
    [Sales_Credit_Calculation__c]                DECIMAL (18, 2) NULL,
    [Service_Acct_ID__c]                         NVARCHAR (255)  NULL,
    [ServiceDate]                                DATETIME2 (7)   NULL,
    [Setup_Fee__c]                               DECIMAL (18, 2) NULL,
    [SortOrder]                                  INT             NULL,
    [SystemModstamp]                             DATETIME2 (7)   NOT NULL,
    [TotalPrice]                                 DECIMAL (18, 2) NULL,
    [Travel_Base_Fee_per_Billing_Cycle__c]       DECIMAL (18, 2) NULL,
    [Travel_Transaction_Fee__c]                  DECIMAL (18, 2) NULL,
    [UnitPrice]                                  DECIMAL (18, 2) NULL,
    [Usage_End_Date__c]                          DATETIME2 (7)   NULL,
    [Marketing_Name__c]                          NVARCHAR (1300) NULL,
    [Promotion_Test_Offer_3__c]                  NCHAR (18)      NULL,
    [Promotion_Test_Offer_4__c]                  NCHAR (18)      NULL,
    [Promotion_Test_Offer_5__c]                  NCHAR (18)      NULL,
    [No_of_Ramps_on_this_Product__c]             DECIMAL (18)    NULL,
    CONSTRAINT [PK_OpportunityLineItem] PRIMARY KEY CLUSTERED ([Id] ASC)
);

