CREATE TABLE [dbo].[Opportunity] (
    [Accepted_Date__c]                                DATETIME2 (7)   NULL,
    [Account_ID__c]                                   NVARCHAR (1300) NULL,
    [Account_Number__c]                               NVARCHAR (15)   NULL,
    [Account_Profile_Score__c]                        DECIMAL (18)    NULL,
    [AccountId]                                       NCHAR (18)      NULL,
    [Accounting_Approved_Date__c]                     DATETIME2 (7)   NULL,
    [Actual_Close_Date__c]                            DATETIME2 (7)   NULL,
    [Actual_Recurring_Billing_Start_Date__c]          DATETIME2 (7)   NULL,
    [Actual_Start_Date__c]                            DATETIME2 (7)   NULL,
    [Additional_EL_Stages__c]                         NVARCHAR (255)  NULL,
    [Additional_EL_Types__c]                          NVARCHAR (255)  NULL,
    [ADP_Partner_Role__c]                             NVARCHAR (255)  NULL,
    [Age_Closed_Not_Won__c]                           DECIMAL (18)    NULL,
    [Age_Closed_Won__c]                               DECIMAL (18)    NULL,
    [Age_Closing__c]                                  DECIMAL (18)    NULL,
    [Age_Demo_Proposal__c]                            DECIMAL (18)    NULL,
    [Age_Discovery__c]                                DECIMAL (18)    NULL,
    [Age_MDR_Working__c]                              DECIMAL (18)    NULL,
    [Age_MDR_Working_Formula__c]                      DECIMAL (18)    NULL,
    [Age_MDR_Working_Today__c]                        DECIMAL (18)    NULL,
    [Age_Sales_Qualified_SQL__c]                      DECIMAL (18)    NULL,
    [Age_Sales_Qualified_SQL_Today__c]                DECIMAL (18)    NULL,
    [Age_Sales_Working__c]                            DECIMAL (18)    NULL,
    [Age_Sales_Working_Today__c]                      DECIMAL (18)    NULL,
    [Age_VOC__c]                                      DECIMAL (18)    NULL,
    [Agreement_Number__c]                             NVARCHAR (80)   NULL,
    [AIC_Assigned_Date__c]                            DATETIME2 (7)   NULL,
    [Amount]                                          DECIMAL (18, 2) NULL,
    [Annual_Maintenance_of_Training_Site__c]          DECIMAL (18)    NULL,
    [Annual_Receipts_Qty__c]                          DECIMAL (18)    NULL,
    [Annual_Transactions__c]                          DECIMAL (18)    NULL,
    [Approval_Rejection_Date__c]                      DATETIME2 (7)   NULL,
    [Approval_Status__c]                              NVARCHAR (255)  NULL,
    [Approved_Indirect_Travel_Deal__c]                VARCHAR (5)     NULL,
    [Asset_Serial_Number__c]                          NVARCHAR (80)   NULL,
    [Asset_Status__c]                                 NVARCHAR (255)  NULL,
    [Audited__c]                                      VARCHAR (5)     NULL,
    [Base_Fees_Billed_in_Arrears__c]                  VARCHAR (5)     NULL,
    [BD_Rep__c]                                       NCHAR (18)      NULL,
    [BigMachines__Line_Items__c]                      DECIMAL (18)    NULL,
    [Billing_Cycle__c]                                NVARCHAR (255)  NULL,
    [BMI_Actual_Sent_Date__c]                         DATETIME2 (7)   NULL,
    [BMI_Could_Not_Be_Used__c]                        VARCHAR (5)     NULL,
    [BMI_Existing_ARR__c]                             DECIMAL (18, 2) NULL,
    [BMI_Net_New_ARR__c]                              DECIMAL (18, 2) NULL,
    [BMI_Survey_Completed_Date__c]                    DATETIME2 (7)   NULL,
    [BMI_Survey_Contact__c]                           NVARCHAR (1300) NULL,
    [BMI_Survey_Scheduled_Send_Date__c]               DATETIME2 (7)   NULL,
    [BMI_Survey_URL__c]                               NVARCHAR (255)  NULL,
    [BMI_Total_ARR__c]                                DECIMAL (18, 2) NULL,
    [BMW_Best_ARR__c]                                 DECIMAL (18)    NULL,
    [BMW_Best_Sales_Credit__c]                        DECIMAL (18)    NULL,
    [BMW_Most_Likely_ARR__c]                          DECIMAL (18)    NULL,
    [BMW_Most_Likely_Sales_Credit__c]                 DECIMAL (18)    NULL,
    [BMW_Worst_ARR__c]                                DECIMAL (18)    NULL,
    [BMW_Worst_Sales_Credit__c]                       DECIMAL (18)    NULL,
    [BSA_Region__c]                                   NVARCHAR (255)  NULL,
    [BSA_Source__c]                                   NVARCHAR (255)  NULL,
    [BSA_Type__c]                                     NVARCHAR (255)  NULL,
    [BU_Global_Split__c]                              NVARCHAR (255)  NULL,
    [CampaignId]                                      NCHAR (18)      NULL,
    [Cashing_Date__c]                                 DATETIME2 (7)   NULL,
    [Client_Dev_Expansion__c]                         VARCHAR (5)     NULL,
    [Client_Dev_Split__c]                             VARCHAR (5)     NULL,
    [Client_Executive__c]                             NCHAR (18)      NULL,
    [Client_Readiness_Call_Attempt_Date__c]           DATETIME2 (7)   NULL,
    [Client_Readiness_Call_Complete_Date__c]          DATETIME2 (7)   NULL,
    [Client_Services_PM__c]                           NVARCHAR (255)  NULL,
    [CLO_Approved_Date__c]                            DATETIME2 (7)   NULL,
    [CloseDate]                                       DATETIME2 (7)   NOT NULL,
    [ConcurConnect__AccruedUnApprovedExpenses__c]     DECIMAL (18, 2) NULL,
    [ConcurConnect__AccruedUnApprovedExpenseTotal__c] DECIMAL (18, 2) NULL,
    [ConcurConnect__FinalExpense__c]                  DECIMAL (18, 2) NULL,
    [ConcurConnect__FinalExpenseTotal__c]             DECIMAL (18, 2) NULL,
    [contact_required__c]                             DECIMAL (18)    NULL,
    [Contract_Action__c]                              NVARCHAR (255)  NULL,
    [Contract_Activated_Date__c]                      DATETIME2 (7)   NULL,
    [Contract_Admin_Approved_Date__c]                 DATETIME2 (7)   NULL,
    [Contract_Approved__c]                            VARCHAR (5)     NULL,
    [Contract_Approved_Date__c]                       DATETIME2 (7)   NULL,
    [Contract_Automation__c]                          NVARCHAR (255)  NULL,
    [Contract_Renewal_Date__c]                        DATETIME2 (7)   NULL,
    [Contract_Renewal_Year__c]                        NVARCHAR (255)  NULL,
    [contract_request_flag__c]                        VARCHAR (5)     NULL,
    [contract_review_flag__c]                         VARCHAR (5)     NULL,
    [Contract_Source__c]                              NVARCHAR (255)  NULL,
    [Contract_Submitted_Date__c]                      DATETIME2 (7)   NULL,
    [Contract_Type__c]                                NVARCHAR (255)  NULL,
    [Contract_Validated__c]                           VARCHAR (5)     NULL,
    [Contract_Validation_1_Approved_Date__c]          DATETIME2 (7)   NULL,
    [Contracted_Monthly_Discount__c]                  DECIMAL (18, 2) NULL,
    [Contracted_Set_up_Discount__c]                   DECIMAL (18, 2) NULL,
    [Contracting_Entity__c]                           NVARCHAR (255)  NULL,
    [Conversion__c]                                   VARCHAR (5)     NULL,
    [Conversion_Platform__c]                          NVARCHAR (255)  NULL,
    [Conversion_Referral_Source__c]                   NCHAR (18)      NULL,
    [Core_Solution__c]                                NVARCHAR (255)  NULL,
    [Corporate_Card__c]                               NVARCHAR (255)  NULL,
    [Country_Scope__c]                                NVARCHAR (255)  NULL,
    [Created_by_Role__c]                              NVARCHAR (1300) NULL,
    [Created_Date_Stamp__c]                           DATETIME2 (7)   NULL,
    [Created_Month__c]                                NVARCHAR (1300) NULL,
    [CreatedById]                                     NCHAR (18)      NULL,
    [CreatedDate]                                     DATETIME2 (7)   NOT NULL,
    [Currency_Exchange_Rate__c]                       DECIMAL (18, 6) NULL,
    [CurrencyIsoCode]                                 NVARCHAR (3)    NULL,
    [Current_Contract_Value__c]                       DECIMAL (18)    NULL,
    [CustomAmount__c]                                 DECIMAL (18)    NULL,
    [Customer_Currency__c]                            NVARCHAR (255)  NULL,
    [Customer_Currency_Rev_Rec__c]                    DECIMAL (18, 2) NULL,
    [Customer_Region__c]                              NVARCHAR (255)  NULL,
    [Daily_Uploads_Fee__c]                            DECIMAL (18)    NULL,
    [Date_Stamp_Closed_Not_Won__c]                    DATETIME2 (7)   NULL,
    [Date_Stamp_Closed_Won__c]                        DATETIME2 (7)   NULL,
    [Date_Stamp_Closing__c]                           DATETIME2 (7)   NULL,
    [Date_Stamp_Demo_Proposal__c]                     DATETIME2 (7)   NULL,
    [Date_Stamp_Discovery__c]                         DATETIME2 (7)   NULL,
    [Date_Stamp_MDR_Working__c]                       DATETIME2 (7)   NULL,
    [Date_Stamp_MQL__c]                               DATETIME2 (7)   NULL,
    [Date_Stamp_Sales_Qualified_SQL__c]               DATETIME2 (7)   NULL,
    [Date_Stamp_Sales_Working__c]                     DATETIME2 (7)   NULL,
    [Date_Stamp_VOC__c]                               DATETIME2 (7)   NULL,
    [Date_Time_Stamp_Sales_Qualified_SQL__c]          DATETIME2 (7)   NULL,
    [Days_from_Contract_to_Submittal__c]              DECIMAL (18)    NULL,
    [Days_from_Submittal_to_Approval__c]              DECIMAL (18)    NULL,
    [Delay_Date__c]                                   DATETIME2 (7)   NULL,
    [Description]                                     NTEXT           NULL,
    [Development_Done_Date__c]                        DATETIME2 (7)   NULL,
    [Direct_to_ADP__c]                                DATETIME2 (7)   NULL,
    [Document_Created_Date__c]                        DATETIME2 (7)   NULL,
    [Edition__c]                                      NVARCHAR (255)  NULL,
    [Estimated_Value_EV__c]                           DECIMAL (18)    NULL,
    [Existing_Annual_Recurring__c]                    DECIMAL (18, 2) NULL,
    [Existing_Monthly_Recurring__c]                   DECIMAL (18, 2) NULL,
    [Existing_Partner_Rep__c]                         NVARCHAR (50)   NULL,
    [Existing_TMC_Agency_Referring_Partner__c]        NVARCHAR (50)   NULL,
    [ExpectedRevenue]                                 DECIMAL (18, 2) NULL,
    [Factored__c]                                     DECIMAL (18, 2) NULL,
    [Factored_Monthly_Transactions__c]                DECIMAL (18, 2) NULL,
    [Final_Month_Closed__c]                           NVARCHAR (1300) NULL,
    [First_Recurring_Invoice_Date__c]                 DATETIME2 (7)   NULL,
    [Fiscal]                                          NVARCHAR (6)    NULL,
    [FiscalQuarter]                                   INT             NULL,
    [FiscalYear]                                      INT             NULL,
    [Forcasted_Mthly_Recur_USD__c]                    DECIMAL (18, 2) NULL,
    [Forecast_Amount__c]                              DECIMAL (18, 2) NULL,
    [ForecastCategory]                                NVARCHAR (40)   NOT NULL,
    [ForecastCategoryName]                            NVARCHAR (40)   NULL,
    [Forecasted_1X_USD__c]                            DECIMAL (18, 2) NULL,
    [Forecasted_Amount_Stamp_Closed_Not_Won__c]       DECIMAL (18, 2) NULL,
    [Forecasted_Amount_Stamp_Closed_Won__c]           DECIMAL (18, 2) NULL,
    [Forecasted_Amount_Stamp_Closing__c]              DECIMAL (18, 2) NULL,
    [Forecasted_Amount_Stamp_Demo_Proposal__c]        DECIMAL (18, 2) NULL,
    [Forecasted_Amount_Stamp_Discovery__c]            DECIMAL (18, 2) NULL,
    [Forecasted_Amount_Stamp_MDR_Working__c]          DECIMAL (18, 2) NULL,
    [Forecasted_Amount_Stamp_Sales_Qualified__c]      DECIMAL (18, 2) NULL,
    [Forecasted_Amount_Stamp_Sales_Working__c]        DECIMAL (18, 2) NULL,
    [Forecasted_Amount_Stamp_VOC__c]                  DECIMAL (18, 2) NULL,
    [Forecasted_AOV_USD__c]                           DECIMAL (18, 2) NULL,
    [Forecasted_AROV_USD__c]                          DECIMAL (18, 2) NULL,
    [formula_ActCloseToSystemAvail__c]                DECIMAL (18)    NULL,
    [formula_DaysInImplementation__c]                 DECIMAL (18)    NULL,
    [formula_ImpBeginToFirstCash__c]                  DECIMAL (18)    NULL,
    [formula_ImpBeginToSystemAvail__c]                DECIMAL (18)    NULL,
    [formula_ImpBeginToTurnover__c]                   DECIMAL (18)    NULL,
    [formula_SystemAvailToFirstCash__c]               DECIMAL (18)    NULL,
    [Fullfillment__c]                                 NVARCHAR (255)  NULL,
    [GE_ARR__c]                                       DECIMAL (18, 2) NULL,
    [GE_Client_Size__c]                               NVARCHAR (1300) NULL,
    [GE_Contract__c]                                  NCHAR (18)      NULL,
    [GE_Products_ARR__c]                              DECIMAL (18, 2) NULL,
    [Gelco_Opportunity_ID__c]                         NVARCHAR (18)   NULL,
    [Governing_Law__c]                                NVARCHAR (255)  NULL,
    [GTM_License_Info__c]                             NVARCHAR (100)  NULL,
    [HasOpportunityLineItem]                          VARCHAR (5)     NOT NULL,
    [Hold_over_deal__c]                               VARCHAR (5)     NULL,
    [Id]                                              NCHAR (18)      NOT NULL,
    [ID_18_Char__c]                                   NVARCHAR (1300) NULL,
    [Imp_Begin_Date__c]                               DATETIME2 (7)   NULL,
    [Imp_Language_Reqs__c]                            NTEXT           NULL,
    [Implementation_Delay_Reason__c]                  NVARCHAR (255)  NULL,
    [Implementation_Invoice_Total__c]                 DECIMAL (18, 2) NULL,
    [Implementation_Reason__c]                        NVARCHAR (255)  NULL,
    [Indirect_Travel_Deal__c]                         VARCHAR (5)     NULL,
    [Installation__c]                                 NVARCHAR (255)  NULL,
    [INSTRUCTIONS_TIPS__c]                            NVARCHAR (1000) NULL,
    [International_Country__c]                        NVARCHAR (255)  NULL,
    [Invoice_Language__c]                             NVARCHAR (255)  NULL,
    [Invoicing_First_Name__c]                         NVARCHAR (80)   NULL,
    [Invoicing_Last_Name__c]                          NVARCHAR (80)   NULL,
    [IPC_Assigned_Date__c]                            DATETIME2 (7)   NULL,
    [Is_Running_Test__c]                              VARCHAR (5)     NULL,
    [IsClosed]                                        VARCHAR (5)     NOT NULL,
    [IsDeleted]                                       VARCHAR (5)     NOT NULL,
    [IsPrivate]                                       VARCHAR (5)     NOT NULL,
    [IsSplit]                                         VARCHAR (5)     NOT NULL,
    [IsWon]                                           VARCHAR (5)     NOT NULL,
    [jsImpacts__Added_from_Data_com__c]               NVARCHAR (1300) NULL,
    [Last_Next_Step__c]                               NTEXT           NULL,
    [LastActivityDate]                                DATETIME2 (7)   NULL,
    [LastModifiedById]                                NCHAR (18)      NULL,
    [LastModifiedDate]                                DATETIME2 (7)   NOT NULL,
    [Lead_Score_DG_Bridge__c]                         NVARCHAR (10)   NULL,
    [LeadSource]                                      NVARCHAR (40)   NULL,
    [Market_Dev__c]                                   VARCHAR (5)     NULL,
    [Master_Terms__c]                                 NVARCHAR (255)  NULL,
    [Maturity_Factor_Amount__c]                       DECIMAL (18, 2) NULL,
    [Maturity_Forecast_Amount__c]                     DECIMAL (18, 2) NULL,
    [MaturityAnalysis_FlagY2__c]                      DECIMAL (18)    NULL,
    [MaturityAnalysis_FlagY__c]                       DECIMAL (18)    NULL,
    [MD_Appointment_Date__c]                          DATETIME2 (7)   NULL,
    [MDR_Expected_SQL_Date__c]                        DATETIME2 (7)   NULL,
    [MDR_Working_Cycle__c]                            DECIMAL (18)    NULL,
    [Mileage_Verification_Tool__c]                    DECIMAL (18)    NULL,
    [Monthly_per_Credit_Card_Fee__c]                  DECIMAL (18, 2) NULL,
    [Monthly_per_User_Fee__c]                         DECIMAL (18, 2) NULL,
    [Monthly_Receipts_Qty__c]                         DECIMAL (18)    NULL,
    [Monthly_Waive_Period__c]                         NVARCHAR (255)  NULL,
    [Multiplier__c]                                   DECIMAL (18)    NULL,
    [NAICS__c]                                        NVARCHAR (1300) NULL,
    [NAICS_Description__c]                            NVARCHAR (1300) NULL,
    [Name]                                            NVARCHAR (120)  NOT NULL,
    [NAS_Date__c]                                     DATETIME2 (7)   NULL,
    [NCU_Services_Ordered__c]                         NTEXT           NULL,
    [Net_New_Annual_Recurring__c]                     DECIMAL (18, 2) NULL,
    [Netherlands_Approved_Date__c]                    DATETIME2 (7)   NULL,
    [New_Contract_Value__c]                           DECIMAL (18)    NULL,
    [New_Pricing_Effective_Date__c]                   DATETIME2 (7)   NULL,
    [Next_Step_Modified_Date__c]                      DATETIME2 (7)   NULL,
    [NextStep]                                        NVARCHAR (255)  NULL,
    [No_of_Additional_Client_ID_s_Required__c]        DECIMAL (18)    NULL,
    [No_of_Claimants_per_Month__c]                    DECIMAL (18)    NULL,
    [No_of_Credit_Cards_per_Month__c]                 DECIMAL (18)    NULL,
    [No_of_Receipts_per_User_per_Month__c]            DECIMAL (18, 2) NULL,
    [No_Of_Training_Days_Implementation__c]           DECIMAL (18)    NULL,
    [Non_Standard_Recurring_Billing__c]               VARCHAR (5)     NULL,
    [Not_Eligible_for_Commission_Quota_Credit__c]     VARCHAR (5)     NULL,
    [Notes_for_Contract_Creator__c]                   NVARCHAR (2000) NULL,
    [of_Opportunities__c]                             DECIMAL (18)    NULL,
    [Opportunity_Accepted_Fiscal_Period__c]           NVARCHAR (1300) NULL,
    [Opportunity_Creation_Fiscal_Period__c]           NVARCHAR (1300) NULL,
    [Opportunity_Lead__c]                             NVARCHAR (255)  NULL,
    [Opportunity_Owner_ID__c]                         NVARCHAR (1300) NULL,
    [Opportunity_Trend__c]                            NVARCHAR (255)  NULL,
    [Oppty_Area__c]                                   NVARCHAR (50)   NULL,
    [Oppty_Business_Unit__c]                          NVARCHAR (50)   NULL,
    [Oppty_Division__c]                               NVARCHAR (50)   NULL,
    [Oppty_Market__c]                                 NVARCHAR (50)   NULL,
    [Oppty_Region__c]                                 NVARCHAR (50)   NULL,
    [Oppty_Revenue_Group__c]                          NVARCHAR (50)   NULL,
    [Oppty_Segment__c]                                NVARCHAR (50)   NULL,
    [Oppty_Team__c]                                   NVARCHAR (50)   NULL,
    [Oppty_Theater__c]                                NVARCHAR (50)   NULL,
    [Optional_Subsequent_Client_ID_Fee__c]            DECIMAL (18)    NULL,
    [Optional_Subsequent_Client_ID_Fee_NUM__c]        DECIMAL (18, 2) NULL,
    [Order_Effective_Date__c]                         DATETIME2 (7)   NULL,
    [Order_Type__c]                                   NVARCHAR (255)  NULL,
    [Original_CID__c]                                 NVARCHAR (100)  NULL,
    [Original_PID__c]                                 NVARCHAR (100)  NULL,
    [OwnerId]                                         NCHAR (18)      NOT NULL,
    [P11D_Tool_Service_Fee__c]                        DECIMAL (18)    NULL,
    [Partner_Involvement__c]                          NVARCHAR (50)   NULL,
    [Payment_Administration_Fee__c]                   DECIMAL (18)    NULL,
    [Payment_Method__c]                               NVARCHAR (255)  NULL,
    [Payment_Terms_net__c]                            NVARCHAR (255)  NULL,
    [PCI_Create_Date__c]                              DATETIME2 (7)   NULL,
    [PCI_Records__c]                                  DECIMAL (18)    NULL,
    [PCI_Referring_Partner__c]                        NVARCHAR (150)  NULL,
    [per_CC_Fee_NUM__c]                               DECIMAL (18, 2) NULL,
    [per_day_Training_Fee__c]                         DECIMAL (18)    NULL,
    [per_day_Training_FeeNUM__c]                      DECIMAL (18, 2) NULL,
    [per_Receipt_Fee__c]                              DECIMAL (18, 2) NULL,
    [Per_Training_Site_Fee__c]                        DECIMAL (18)    NULL,
    [per_Training_Site_Fee_Num__c]                    DECIMAL (18, 2) NULL,
    [PO_Number__c]                                    NVARCHAR (30)   NULL,
    [PO_to_be_Issued__c]                              VARCHAR (5)     NULL,
    [Pre_Production_Waive__c]                         NVARCHAR (255)  NULL,
    [Prepaid_Training_Total__c]                       DECIMAL (18, 2) NULL,
    [Pricebook2Id]                                    NCHAR (18)      NULL,
    [Probability]                                     DECIMAL (18)    NULL,
    [Probability_Age_0__c]                            DECIMAL (18)    NULL,
    [Probability_Age_10__c]                           DECIMAL (18)    NULL,
    [Probability_Age_25__c]                           DECIMAL (18)    NULL,
    [Probability_Age_50__c]                           DECIMAL (18)    NULL,
    [Probability_Age_75__c]                           DECIMAL (18)    NULL,
    [Probability_Age_90__c]                           DECIMAL (18)    NULL,
    [Prod_Site_Available__c]                          DATETIME2 (7)   NULL,
    [pse__Group__c]                                   NCHAR (18)      NULL,
    [pse__Is_Change_Request__c]                       VARCHAR (5)     NULL,
    [pse__Is_Services_Opportunity__c]                 VARCHAR (5)     NULL,
    [pse__IsParentOpportunityServices__c]             VARCHAR (5)     NULL,
    [pse__Parent_Opportunity__c]                      NCHAR (18)      NULL,
    [pse__Practice__c]                                NCHAR (18)      NULL,
    [pse__Pre_Billed_Amount__c]                       DECIMAL (18, 2) NULL,
    [pse__PreBilledAmount__c]                         DECIMAL (18)    NULL,
    [pse__Primary_Project__c]                         NCHAR (18)      NULL,
    [pse__Region__c]                                  NCHAR (18)      NULL,
    [pse__Services_Attached_From_Products__c]         DECIMAL (18, 2) NULL,
    [pse__Services_Attached_Percent_From_Products__c] DECIMAL (18, 2) NULL,
    [Q1_BMI_Sales_Productivity__c]                    NVARCHAR (255)  NULL,
    [Q2_BMI_Personal_Productivity__c]                 NVARCHAR (255)  NULL,
    [Q3_BMI_Performance__c]                           NVARCHAR (255)  NULL,
    [Q4_BMI_Lovability__c]                            NTEXT           NULL,
    [Q5_BMI_Comments__c]                              NTEXT           NULL,
    [Quality__c]                                      NVARCHAR (255)  NULL,
    [Quote_Created_Date__c]                           DATETIME2 (7)   NULL,
    [Quote_Number__c]                                 NVARCHAR (80)   NULL,
    [Quote_Provided_By__c]                            NVARCHAR (255)  NULL,
    [Quote_Status__c]                                 NVARCHAR (80)   NULL,
    [Reason_Lost_Explanation__c]                      NVARCHAR (255)  NULL,
    [Reason_Lost_Won__c]                              NVARCHAR (255)  NULL,
    [Reason_Why_Invoice_Product_Not_Sold__c]          NTEXT           NULL,
    [Reason_Why_Standard_Product_Not_Sold__c]         NTEXT           NULL,
    [RecordTypeId]                                    NCHAR (18)      NULL,
    [Recurring_Billing_Start_Date__c]                 DATETIME2 (7)   NULL,
    [Referral_Type__c]                                NVARCHAR (255)  NULL,
    [Remote_Link_Hourly_Training_Fee__c]              DECIMAL (18, 2) NULL,
    [Remote_Link_Hourly_Training_Fee_NUM__c]          DECIMAL (18, 2) NULL,
    [Repricing_Type__c]                               NVARCHAR (255)  NULL,
    [Request_Contract__c]                             VARCHAR (5)     NULL,
    [Request_Credit_Check__c]                         VARCHAR (5)     NULL,
    [Revenue_Comments__c]                             NTEXT           NULL,
    [Review_Contract__c]                              VARCHAR (5)     NULL,
    [Revision_Number__c]                              DECIMAL (18)    NULL,
    [RFP_tick_box__c]                                 VARCHAR (5)     NULL,
    [Roll_up_Additional_Sales_Credit__c]              DECIMAL (18, 2) NULL,
    [Roll_up_Opportunity_ARR__c]                      DECIMAL (18, 2) NULL,
    [Roll_up_Sales_Credit_Calculation__c]             DECIMAL (18, 2) NULL,
    [Roll_Up_Setup_Fee__c]                            DECIMAL (18, 2) NULL,
    [rrpu__Alert_Message__c]                          NVARCHAR (255)  NULL,
    [RSE_Opp_Status__c]                               NVARCHAR (255)  NULL,
    [Sales_Commission_Count__c]                       DECIMAL (18)    NULL,
    [Sales_Working_Cycle__c]                          DECIMAL (18)    NULL,
    [Sent_Referral_Notification__c]                   VARCHAR (5)     NULL,
    [Setup_Fee__c]                                    DECIMAL (18)    NULL,
    [Setup_Fee_NUM__c]                                DECIMAL (18, 2) NULL,
    [SFDC_Partner_Involvement__c]                     NVARCHAR (50)   NULL,
    [SFDC_PCI_Create_Date__c]                         DATETIME2 (7)   NULL,
    [SFDC_Referring_Partner__c]                       NVARCHAR (100)  NULL,
    [SLX_Opportunity_ID__c]                           NVARCHAR (25)   NULL,
    [Special_Terms__c]                                NTEXT           NULL,
    [Split_Opportunity__c]                            VARCHAR (5)     NULL,
    [Stage_Change_Date__c]                            DATETIME2 (7)   NULL,
    [StageName]                                       NVARCHAR (40)   NOT NULL,
    [Status__c]                                       NVARCHAR (255)  NULL,
    [Sub_Agency__c]                                   NCHAR (18)      NULL,
    [Submit_Order_Date__c]                            NVARCHAR (50)   NULL,
    [System_Availability_Date__c]                     DATETIME2 (7)   NULL,
    [Systematized_Contract__c]                        VARCHAR (5)     NULL,
    [SystemModstamp]                                  DATETIME2 (7)   NOT NULL,
    [Target_Development_Start_Date__c]                DATETIME2 (7)   NULL,
    [Target_Profile_Complete_Date__c]                 DATETIME2 (7)   NULL,
    [Target_Start_Date__c]                            DATETIME2 (7)   NULL,
    [Tax_Exemption_Claimed__c]                        VARCHAR (5)     NULL,
    [Term_no_of_months__c]                            NVARCHAR (255)  NULL,
    [Term_Notice__c]                                  NVARCHAR (255)  NULL,
    [Tier_Change__c]                                  VARCHAR (5)     NULL,
    [Timeframe__c]                                    NVARCHAR (255)  NULL,
    [TotalOpportunityQuantity]                        DECIMAL (18, 2) NULL,
    [Trainer_Assigned__c]                             NVARCHAR (255)  NULL,
    [Training_Complete_Date__c]                       DATETIME2 (7)   NULL,
    [Training_Request_Date__c]                        DATETIME2 (7)   NULL,
    [Training_Site_Required__c]                       VARCHAR (5)     NULL,
    [Training_Type__c]                                NVARCHAR (255)  NULL,
    [Trial_Expiration__c]                             DATETIME2 (7)   NULL,
    [Turn_Over_To_Call_Center_Date__c]                DATETIME2 (7)   NULL,
    [Type]                                            NVARCHAR (40)   NULL,
    [Type_of_Add_On__c]                               NVARCHAR (255)  NULL,
    [Unit_Credit__c]                                  NVARCHAR (255)  NULL,
    [Upgrade_Initiative__c]                           VARCHAR (5)     NULL,
    [Usage_End_Date__c]                               DATETIME2 (7)   NULL,
    [VAT__c]                                          NVARCHAR (255)  NULL,
    [Web_Lead_Source__c]                              NVARCHAR (255)  NULL,
    [Why_was_BMI_not_used__c]                         NVARCHAR (255)  NULL,
    [Win_Loss_Review__c]                              NTEXT           NULL,
    [Xactly_Order_Type__c]                            NVARCHAR (255)  NULL,
    [Specialist__c]                                   NCHAR (18)      NULL,
    [Private_Equity_Partner__c]                       NVARCHAR (255)  NULL,
    [Competitors__c]                                  NCHAR (18)      NULL,
    [Oppty_CE_Division__c]                            NVARCHAR (50)   NULL,
    [Oppty_CE_Region__c]                              NVARCHAR (50)   NULL,
    [Price_Increase__c]                               DECIMAL (18, 2) NULL,
    [Assigned_Account_MDR__c]                         NCHAR (18)      NULL,
    [PCI_Status_Date__c]                              DATETIME        NULL,
    [PCI_Category__c]                                 NVARCHAR (255)  NULL,
    [Date_Stamp_Channel_Pipeline__c]                  DATETIME        NULL,
    [infer2__Infer_Score__c]                          DECIMAL (18)    NULL,
    [ARR_Disputes__c]                                 NVARCHAR (255)  NULL,
    [Sales_Arr_Modified__c]                           VARCHAR (5)     NULL,
    [Implementation_Partner__c]                       NCHAR (18)      NULL,
    [Created_By_Revenue_Group__c]                     NVARCHAR (1300) NULL,
    [Is_Contract_Renewal__c]                          VARCHAR (5)     NULL,
    [Is_Core_Changed__c]                              VARCHAR (5)     NULL,
    [Is_Edition_Changed__c]                           VARCHAR (5)     NULL,
    [Is_Executive_Overview__c]                        VARCHAR (5)     NULL,
    [SAP_Accepted_Referrals__c]                       DECIMAL (18)    NULL,
    [SAP_APJ_Active_Engagement__c]                    VARCHAR (5)     NULL,
    [Top_Competitor__c]                               NCHAR (18)      NULL,
    [Top_Competitor_ID__c]                            NVARCHAR (1300) NULL,
    [Travel_Config_Id__c]                             NVARCHAR (50)   NULL,
    [Travel_Config_Name__c]                           NVARCHAR (255)  NULL,
    [Travel_Only_Contract__c]                         VARCHAR (5)     NULL,
    [Created_By_Owner_Region__c]                      NVARCHAR (50)   NULL,
    [Created_By_Owner_Team__c]                        NVARCHAR (50)   NULL,
    [Created_By_Owner_Revenue_Group_Original__c]      NVARCHAR (100)  NULL,
    [Created_By_Owner_Team_Original__c]               NVARCHAR (100)  NULL,
    [Created_By_Owner_Bus_Unit_Original__c]           NVARCHAR (100)  NULL,
    [Account_Level__c]                                NVARCHAR (255)  NULL,
    [Date_Stamp_MQL_1__c]                             DATETIME        NULL,
    [SQL_Opportunity_MDR__c]                          NVARCHAR (80)   NULL,
    [Age_MQL_Days__c]                                 DECIMAL (18)    NULL,
    [Date_Stamp_MDR_Working_Date_Stamp_MQL__c]        DECIMAL (18)    NULL,
    [IsMerged_MQL__c]                                 VARCHAR (5)     NULL,
    [Contact_Id__c]                                   NVARCHAR (20)   NULL,
    [Interest_Score__c]                               DECIMAL (18)    NULL,
    [Qualification_Score__c]                          DECIMAL (18)    NULL,
    [Recycle_Trash_Reason__c]                         NVARCHAR (255)  NULL,
    [Master_Opportunity__c]                           NVARCHAR (18)   NULL,
    [Fulfillment_Partner__c]                          NCHAR (18)      NULL,
    [Fulfillment_Partner_Actual_Name__c]              NVARCHAR (1300) NULL,
    [Fulfillment_Partner_Name__c]                     NVARCHAR (255)  NULL,
    [Date_Stamp_MDR_Accepted__c]                      DATETIME        NULL,
    [GCO_Comp_Eligibility_upon_Close__c]              NVARCHAR (255)  NULL,
    [GCO_Matched_V2__c]                               NVARCHAR (1300) NULL,
    [GCO_Override__c]                                 VARCHAR (5)     NULL,
    [GCO_Override_Reason__c]                          NVARCHAR (255)  NULL,
    [Roll_up_Core_Invoice_Opportunity_ARR__c]         DECIMAL (18, 2) NULL,
    [PreSales_SC__c]                                  NCHAR (18)      NULL,
    [Business_Model__c]                               NVARCHAR (255)  NULL,
    [Company_Attributes__c]                           NVARCHAR (255)  NULL,
    [Customer_Priority__c]                            NVARCHAR (255)  NULL,
    [Product_Service_Attributes__c]                   NVARCHAR (255)  NULL,
    [Distribution_Channel__c]                         NVARCHAR (1300) NULL,
    [Primary_Referring_Partner_Sub_Category__c]       NVARCHAR (255)  NULL,
    [Next_FY_Oppty_SAP_Region__c]                     NVARCHAR (255)  NULL,
    [Oppty_Override_SAP_Region__c]                    NVARCHAR (255)  NULL,
    [Oppty_SAP_Region__c]                             NVARCHAR (50)   NULL,
    [Next_FY_Oppty_Market__c]                         NVARCHAR (255)  NULL,
    [Next_FY_Oppty_Business_Unit__c]                  NVARCHAR (255)  NULL,
    [Next_FY_Oppty_Division__c]                       NVARCHAR (255)  NULL,
    [Next_FY_Oppty_Owner__c]                          NCHAR (18)      NULL,
    [Next_FY_Oppty_Region__c]                         NVARCHAR (255)  NULL,
    [Next_FY_Oppty_Revenue_Group__c]                  NVARCHAR (255)  NULL,
    [Next_FY_Oppty_Team__c]                           NVARCHAR (255)  NULL,
    [Next_FY_Oppty_Theater__c]                        NVARCHAR (255)  NULL,
    CONSTRAINT [PK_opportunity_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [opportunity_n1]
    ON [dbo].[Opportunity]([Account_ID__c] ASC);


GO
CREATE NONCLUSTERED INDEX [NONCLUSTERED_DateStampFields]
    ON [dbo].[Opportunity]([Date_Stamp_Sales_Working__c] ASC, [Date_Stamp_Sales_Qualified_SQL__c] ASC, [Date_Stamp_VOC__c] ASC)
    INCLUDE([Account_ID__c], [Date_Stamp_Closed_Won__c], [Date_Stamp_Closing__c]);


GO
CREATE NONCLUSTERED INDEX [Oppty_StageName]
    ON [dbo].[Opportunity]([StageName] ASC)
    INCLUDE([Account_ID__c]);


GO
CREATE NONCLUSTERED INDEX [Travel_Config_Id__c]
    ON [dbo].[Opportunity]([Travel_Config_Id__c] ASC);

