CREATE TABLE [dbo].[Partner_Enablement__c] (
    [Access_to_Pro_Sandbox__c]       DATETIME2 (7)  NULL,
    [Account__c]                     NCHAR (18)     NULL,
    [App_Cert_Form_Recd__c]          DATETIME2 (7)  NULL,
    [App_Cert_Walkthrough__c]        DATETIME2 (7)  NULL,
    [App_Scope_Doc_Recd__c]          DATETIME2 (7)  NULL,
    [Application__c]                 NVARCHAR (100) NULL,
    [Cert_Complete__c]               DATETIME2 (7)  NULL,
    [Comments__c]                    NTEXT          NULL,
    [CreatedById]                    NCHAR (18)     NULL,
    [CreatedDate]                    DATETIME2 (7)  NOT NULL,
    [CurrencyIsoCode]                NVARCHAR (3)   NULL,
    [End_to_End_Testing_Complete__c] DATETIME2 (7)  NULL,
    [Id]                             NCHAR (18)     NOT NULL,
    [IsDeleted]                      VARCHAR (5)    NOT NULL,
    [KO_with_Partner__c]             DATETIME2 (7)  NULL,
    [KO_with_Prospective_Partner__c] DATETIME2 (7)  NULL,
    [LastActivityDate]               DATETIME2 (7)  NULL,
    [LastModifiedById]               NCHAR (18)     NULL,
    [LastModifiedDate]               DATETIME2 (7)  NOT NULL,
    [Name]                           NVARCHAR (80)  NULL,
    [SystemModstamp]                 DATETIME2 (7)  NOT NULL,
    [App_Category__c]                NVARCHAR (MAX) NULL,
    [Deployment_Type__c]             NVARCHAR (255) NULL,
    [Certification_Target_Date__c]   DATETIME       NULL,
    [Service_Offerings__c]           NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Partner_Enablement__c_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);

