CREATE TABLE [dbo].[Partner_Customer_Involvement__c] (
    [Active_Partner__c]                     NVARCHAR (255)  NULL,
    [Active_Partner_Rep__c]                 NVARCHAR (50)   NULL,
    [Amex_Rep_Channel__c]                   NVARCHAR (255)  NULL,
    [Amex_Rep_Country__c]                   NVARCHAR (255)  NULL,
    [Amex_Rep_Position__c]                  NVARCHAR (255)  NULL,
    [Amex_Rep_Region__c]                    NVARCHAR (255)  NULL,
    [Amex_Rep_VP_Leader__c]                 NVARCHAR (100)  NULL,
    [Amexco_Client_ID__c]                   NVARCHAR (40)   NULL,
    [Amexco_Prospect_ID__c]                 NVARCHAR (40)   NULL,
    [AVP__c]                                NVARCHAR (55)   NULL,
    [BD_Rep__c]                             NCHAR (18)      NULL,
    [Breeze_Only_Referral__c]               NVARCHAR (5)    NULL,
    [Comments__c]                           NTEXT           NULL,
    [Company__c]                            NVARCHAR (100)  NULL,
    [Compensation__c]                       NTEXT           NULL,
    [Contact_Partner_Rep_Before_Calling__c] NVARCHAR (255)  NULL,
    [CreatedById]                           NCHAR (18)      NULL,
    [CreatedDate]                           DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                       NVARCHAR (3)    NULL,
    [Current_Amex_Customer__c]              NVARCHAR (255)  NULL,
    [DVP__c]                                NVARCHAR (255)  NULL,
    [Email_2__c]                            NVARCHAR (80)   NULL,
    [Employee_ID_Code__c]                   NVARCHAR (100)  NULL,
    [Id]                                    NCHAR (18)      NOT NULL,
    [IsDeleted]                             VARCHAR (5)     NOT NULL,
    [LastActivityDate]                      DATETIME2 (7)   NULL,
    [LastModifiedById]                      NCHAR (18)      NULL,
    [LastModifiedDate]                      DATETIME2 (7)   NOT NULL,
    [Name]                                  NVARCHAR (80)   NULL,
    [Name_2__c]                             NVARCHAR (51)   NULL,
    [Name__c]                               NVARCHAR (50)   NULL,
    [of_Employees__c]                       NVARCHAR (255)  NULL,
    [of_Referrals__c]                       DECIMAL (18)    NULL,
    [Offered_Kickoff_Date__c]               DATETIME2 (7)   NULL,
    [Opportunity__c]                        NCHAR (18)      NULL,
    [Opportunity_Lead_Source__c]            NCHAR (18)      NULL,
    [Partner_Rep__c]                        NVARCHAR (50)   NULL,
    [Partner_Rep_E_Mail__c]                 NVARCHAR (80)   NULL,
    [Partner_Rep_Phone__c]                  NVARCHAR (40)   NULL,
    [Partner_Segment__c]                    NVARCHAR (255)  NULL,
    [Phone_Number_2__c]                     NVARCHAR (40)   NULL,
    [Phone_Number__c]                       NVARCHAR (40)   NULL,
    [Prospect_Email__c]                     NVARCHAR (80)   NULL,
    [RecordTypeId]                          NCHAR (18)      NULL,
    [Referral_Age__c]                       DECIMAL (18)    NULL,
    [Referral_Date__c]                      DATETIME2 (7)   NULL,
    [Referral_Fiscal_Period__c]             NVARCHAR (1300) NULL,
    [Referral_Product_Interest__c]          NVARCHAR (255)  NULL,
    [Referral_Response_Time__c]             DECIMAL (18, 2) NULL,
    [Referral_Status__c]                    NVARCHAR (255)  NULL,
    [Referring_Customer__c]                 NCHAR (18)      NULL,
    [Referring_Partner__c]                  NVARCHAR (255)  NULL,
    [Referring_Partner_Category__c]         NVARCHAR (255)  NULL,
    [Rejection_Reason__c]                   NVARCHAR (255)  NULL,
    [RSE_Comments__c]                       NVARCHAR (400)  NULL,
    [Status_Date__c]                        DATETIME2 (7)   NULL,
    [SystemModstamp]                        DATETIME2 (7)   NOT NULL,
    [Title__c]                              NVARCHAR (100)  NULL,
    [Type__c]                               NVARCHAR (255)  NULL,
    [Date_Stamp_SFDC_Channel_Pipeline__c]   DATETIME        NULL,
    [Referring_Partner_Category_Formula__c] VARCHAR (1300)  NULL,
    [Date_Stamp_Channel_Pipeline__c]        DATETIME        NULL,
    [Advisor_Channel_Sales_Manager__c]      NVARCHAR (100)  NULL,
    [Advisor_Sales_Owner__c]                NVARCHAR (100)  NULL,
    [Referring_Company__c]                  NCHAR (18)      NULL,
    [PCI_Date_Stamp_Channel_Pipeline__c]    DATETIME        NULL,
    [Partner_Involvement_Concept__c]        NVARCHAR (1300) NULL,
    [Primary_PCI__c]                        VARCHAR (5)     NULL,
    [App_Center_Partner__c]                 NVARCHAR (100)  NULL,
    [App_Center_Partner_Rep__c]             NVARCHAR (100)  NULL,
    [Eloqua_PCI_Id__c]                      NVARCHAR (255)  NULL,
    [Referring_Concur_Rep__c]               NVARCHAR (100)  NULL,
    [Partner_Involvement_Override__c]       NVARCHAR (255)  NULL,
    [Distributor__c]                        NVARCHAR (255)  NULL,
    [Referring_Partner_Sub_Category__c]     NVARCHAR (255)  NULL,
    CONSTRAINT [PK_Partner_Customer_Involvement__c_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);

