CREATE TABLE [dbo].[pse__proj__c] (
    [Account_ID__c]                                    NVARCHAR (1300) NULL,
    [Activate_Schedule_Applicable_Jobs__c]             NVARCHAR (255)  NULL,
    [Actual_Imp_Cycle__c]                              DECIMAL (18)    NULL,
    [Additional_Info_For_Account_Management__c]        NVARCHAR (255)  NULL,
    [Additional_Info_For_Payment_Cycle__c]             NVARCHAR (255)  NULL,
    [Additional_Info_Regarding_Reference__c]           NVARCHAR (255)  NULL,
    [Additional_Projects_Included__c]                  NVARCHAR (255)  NULL,
    [ADP_Client_Code__c]                               NVARCHAR (20)   NULL,
    [Agreement_Number__c]                              NVARCHAR (1300) NULL,
    [Allow_Billable_Expenses__c]                       VARCHAR (5)     NULL,
    [Allow_Fixed_Price_Billing__c]                     VARCHAR (5)     NULL,
    [Allow_T_M_Billing__c]                             VARCHAR (5)     NULL,
    [AMEX_Biz_Travel_ID__c]                            NVARCHAR (20)   NULL,
    [Amexco_Client_ID__c]                              NVARCHAR (20)   NULL,
    [Approval_Status__c]                               NVARCHAR (255)  NULL,
    [Approver_Comments2__c]                            NTEXT           NULL,
    [Approver_Comments__c]                             NVARCHAR (255)  NULL,
    [Apttus_Agreement_Number__c]                       NVARCHAR (25)   NULL,
    [ARR__c]                                           DECIMAL (18)    NULL,
    [Attendee_Call_Scheduled__c]                       DATETIME2 (7)   NULL,
    [Attendees_Functional_Knowledge_Transfer__c]       NVARCHAR (255)  NULL,
    [Audit_On_Boarding_Team_Lead__c]                   NCHAR (18)      NULL,
    [Audit_Order_Notification_Received_Date__c]        DATETIME2 (7)   NULL,
    [Audit_Service_Requirements__c]                    NTEXT           NULL,
    [Audit_Service_Requirements_CP_Std__c]             NTEXT           NULL,
    [Audit_Setup_Completed_Date__c]                    DATETIME2 (7)   NULL,
    [Audit_Team_Lead1__c]                              NCHAR (18)      NULL,
    [Audit_Team_Lead2__c]                              NCHAR (18)      NULL,
    [Audit_Workbench_Setup_Completed_Date__c]          DATETIME2 (7)   NULL,
    [Audit_Workflow_Setup__c]                          NVARCHAR (255)  NULL,
    [BI_Training_Attendees__c]                         NVARCHAR (255)  NULL,
    [Billing_Address_Ref__c]                           NVARCHAR (50)   NULL,
    [Billing_Contact_Ref__c]                           NVARCHAR (50)   NULL,
    [Billing_Trigger__c]                               NVARCHAR (255)  NULL,
    [Booking_Date_Load__c]                             DATETIME2 (7)   NULL,
    [Business_Unit__c]                                 NVARCHAR (1300) NULL,
    [Calculated_ARR_Renewal_Date__c]                   DATETIME2 (7)   NULL,
    [Call_1_Conducted__c]                              DATETIME2 (7)   NULL,
    [Call_1_Scheduled__c]                              DATETIME2 (7)   NULL,
    [Call_2_Conducted__c]                              DATETIME2 (7)   NULL,
    [Call_3_Conducted__c]                              DATETIME2 (7)   NULL,
    [Card_Feeds_Utilization_Count__c]                  NVARCHAR (3)    NULL,
    [Card_Feeds_Utilization_Notes__c]                  NVARCHAR (255)  NULL,
    [Cash_Advance_Utilization__c]                      NVARCHAR (255)  NULL,
    [CEM_Call_Completed_Date__c]                       DATETIME2 (7)   NULL,
    [Certified__c]                                     NTEXT           NULL,
    [CIA_Complete__c]                                  DATETIME2 (7)   NULL,
    [CIA_Expense_Types_Complete_Date_Expense__c]       DATETIME2 (7)   NULL,
    [CIA_Questionnaire_Complete_Date_Expense__c]       DATETIME2 (7)   NULL,
    [Client_acknowledges_Inv_Mgmt_Deployed__c]         NVARCHAR (255)  NULL,
    [Client_Candidate_For_Reference_Program__c]        NVARCHAR (255)  NULL,
    [Client_Data_Portal_Link__c]                       NVARCHAR (255)  NULL,
    [Client_Engagement_Completed_Date__c]              DATETIME2 (7)   NULL,
    [Client_Engagement_Manager__c]                     NCHAR (18)      NULL,
    [Client_Engagement_Mgr_Start_Date__c]              DATETIME2 (7)   NULL,
    [Client_interested_In_Other_Services__c]           NTEXT           NULL,
    [Client_Project_Lead__c]                           NCHAR (18)      NULL,
    [Client_Support_Manager__c]                        NCHAR (18)      NULL,
    [CLIN__c]                                          NVARCHAR (255)  NULL,
    [Comments_for_Prodcution_Handoff__c]               NTEXT           NULL,
    [Concur_Pay__c]                                    NTEXT           NULL,
    [Conduct_Design_Session__c]                        DATETIME2 (7)   NULL,
    [Conduct_Expense_Administration_Training__c]       DATETIME2 (7)   NULL,
    [Conduct_Expense_Service_Training__c]              DATETIME2 (7)   NULL,
    [Conduct_Extract_Training__c]                      DATETIME2 (7)   NULL,
    [Conduct_Imports_Training__c]                      DATETIME2 (7)   NULL,
    [Conduct_Initial_Tech_Call__c]                     DATETIME2 (7)   NULL,
    [Configuration_Call__c]                            DATETIME2 (7)   NULL,
    [Configuration_Call_Scheduled__c]                  DATETIME2 (7)   NULL,
    [Configuration_Sign_off__c]                        DATETIME2 (7)   NULL,
    [Configure_Concur_Reservation__c]                  DATETIME2 (7)   NULL,
    [Configure_Extracts__c]                            NTEXT           NULL,
    [Configure_Imports__c]                             NTEXT           NULL,
    [Configure_Reporting__c]                           NVARCHAR (255)  NULL,
    [Confirm_Client_Completed_Training__c]             NVARCHAR (255)  NULL,
    [Confirm_Extract_And_Frequency__c]                 NTEXT           NULL,
    [Confirm_Imports_And_Frequency__c]                 NTEXT           NULL,
    [Confirm_Webinar_Type__c]                          NVARCHAR (255)  NULL,
    [Contract_Audit_Transaction_Amount__c]             NVARCHAR (255)  NULL,
    [Contract_Number__c]                               NVARCHAR (20)   NULL,
    [Core_Service_Project__c]                          NVARCHAR (1300) NULL,
    [CreatedById]                                      NCHAR (18)      NULL,
    [CreatedDate]                                      DATETIME2 (7)   NOT NULL,
    [Credit_Card_Feed_Initiated__c]                    DATETIME2 (7)   NULL,
    [CS_Assigned__c]                                   DATETIME2 (7)   NULL,
    [CurrencyIsoCode]                                  NVARCHAR (3)    NULL,
    [Date_CS_Webinar_Attendance__c]                    DATETIME2 (7)   NULL,
    [Date_Submitted__c]                                DATETIME2 (7)   NULL,
    [Days_to_Assign__c]                                DECIMAL (18)    NULL,
    [Days_To_CB_Setup_Complete__c]                     DECIMAL (18)    NULL,
    [Days_to_Configure__c]                             DECIMAL (18)    NULL,
    [Days_to_Implement__c]                             DECIMAL (18)    NULL,
    [Days_to_Implementation__c]                        DECIMAL (18)    NULL,
    [Days_To_Kickoff__c]                               DECIMAL (18, 2) NULL,
    [Days_to_Transition__c]                            DECIMAL (18)    NULL,
    [Deal_Type__c]                                     NVARCHAR (255)  NULL,
    [Demo_Attendees__c]                                NVARCHAR (255)  NULL,
    [Deployed_Country_ies__c]                          NTEXT           NULL,
    [Deployment_Method__c]                             NVARCHAR (255)  NULL,
    [Deployment_Type__c]                               NVARCHAR (255)  NULL,
    [Design_Specialist__c]                             NCHAR (18)      NULL,
    [DW_EXP_Archive_job_Scheduled_Successful__c]       NVARCHAR (255)  NULL,
    [DW_TRVL_Archive_job_Scheduled_Successful__c]      NVARCHAR (255)  NULL,
    [Effective_Contract_Date__c]                       DATETIME2 (7)   NULL,
    [Effective_Contract_Date_Load__c]                  DATETIME2 (7)   NULL,
    [Effective_Contract_Datex__c]                      DATETIME2 (7)   NULL,
    [Email_to_AS_Connector__c]                         DATETIME2 (7)   NULL,
    [Email_to_Cliqbook_Team__c]                        DATETIME2 (7)   NULL,
    [Email_to_Product_Teams__c]                        DATETIME2 (7)   NULL,
    [Email_to_User_Support_Desk__c]                    DATETIME2 (7)   NULL,
    [Enable_Audit_Service__c]                          NVARCHAR (255)  NULL,
    [Enable_Expense_Pay__c]                            NVARCHAR (255)  NULL,
    [Enable_HTTPS_upload_download__c]                  NVARCHAR (255)  NULL,
    [Enable_Imaging__c]                                NVARCHAR (255)  NULL,
    [Enter_password_preferences_from_CIA__c]           NVARCHAR (255)  NULL,
    [Enterprise_Services_Ops_Contact__c]               NCHAR (18)      NULL,
    [Entity_Build_Required__c]                         NVARCHAR (255)  NULL,
    [Entity_Spin_Up__c]                                NVARCHAR (255)  NULL,
    [Entity_Template__c]                               NVARCHAR (255)  NULL,
    [Environment_Comments__c]                          NVARCHAR (255)  NULL,
    [Environment_Type__c]                              NVARCHAR (255)  NULL,
    [Est_Imp_Cycle__c]                                 DECIMAL (18)    NULL,
    [Estimated_Prod_Site__c]                           DATETIME2 (7)   NULL,
    [Estimated_Production_Preparation_Date__c]         DATETIME2 (7)   NULL,
    [Ever_Rejected__c]                                 NVARCHAR (10)   NULL,
    [Expense_Pay_Setup_PreProd__c]                     NVARCHAR (255)  NULL,
    [Final_Submit_Date__c]                             DATETIME2 (7)   NULL,
    [First_Deliverable_Received__c]                    DATETIME2 (7)   NULL,
    [FTP_PGP_Call_Scheduled__c]                        DATETIME2 (7)   NULL,
    [FTP_Utilization__c]                               NVARCHAR (255)  NULL,
    [Functional_Consultant__c]                         NCHAR (18)      NULL,
    [Global_Project__c]                                VARCHAR (5)     NULL,
    [Id]                                               NCHAR (18)      NOT NULL,
    [ID_in_Source_System__c]                           NVARCHAR (80)   NULL,
    [Imp_Method_Load__c]                               NVARCHAR (255)  NULL,
    [Imp_Survey_Actual_Sent_Date__c]                   DATETIME2 (7)   NULL,
    [Imp_Survey_Completed_Date__c]                     DATETIME2 (7)   NULL,
    [Imp_Survey_Contact__c]                            NCHAR (18)      NULL,
    [Imp_Survey_Reminder_Sent_Date__c]                 DATETIME2 (7)   NULL,
    [Imp_Survey_Scheduled_Send_Date__c]                DATETIME2 (7)   NULL,
    [Imp_Survey_Send_Override_Date__c]                 DATETIME2 (7)   NULL,
    [Imp_Survey_URL__c]                                NVARCHAR (255)  NULL,
    [Implementation_Details_Comments__c]               NTEXT           NULL,
    [Implementation_Level__c]                          NVARCHAR (255)  NULL,
    [Implementation_Method__c]                         NVARCHAR (1300) NULL,
    [Implementation_Notes__c]                          NVARCHAR (255)  NULL,
    [Implementation_Status__c]                         NVARCHAR (255)  NULL,
    [Implementation_Type__c]                           NVARCHAR (255)  NULL,
    [Initial_Config__c]                                DATETIME2 (7)   NULL,
    [Initial_Contact__c]                               DATETIME2 (7)   NULL,
    [Initial_Est_Impl_Cycle__c]                        DECIMAL (18)    NULL,
    [Initial_Prod_Site_Available__c]                   DATETIME2 (7)   NULL,
    [Initiate_Disconnect_Date__c]                      DATETIME2 (7)   NULL,
    [Initiate_Transition_to_CS__c]                     DATETIME2 (7)   NULL,
    [Integrated_Travel__c]                             NVARCHAR (255)  NULL,
    [Intro_to_CS_Email_Sent_to_Client__c]              DATETIME2 (7)   NULL,
    [Introduction_Email_Sent_Date__c]                  DATETIME2 (7)   NULL,
    [Invoice_Pay_Setup_PreProd__c]                     NVARCHAR (255)  NULL,
    [IPM_Completed_Extract_Training__c]                NVARCHAR (255)  NULL,
    [IPM_Completed_Imports_Training__c]                NVARCHAR (255)  NULL,
    [Is_ARR__c]                                        VARCHAR (5)     NULL,
    [IsDeleted]                                        VARCHAR (5)     NOT NULL,
    [ISM__c]                                           NCHAR (18)      NULL,
    [ISM_Assigned__c]                                  DATETIME2 (7)   NULL,
    [Kickoff_Call_Held_On__c]                          DATETIME2 (7)   NULL,
    [Kickoff_Call_Scheduled__c]                        DATETIME2 (7)   NULL,
    [LastActivityDate]                                 DATETIME2 (7)   NULL,
    [LastModifiedById]                                 NCHAR (18)      NULL,
    [LastModifiedDate]                                 DATETIME2 (7)   NOT NULL,
    [Link_to_Validation_Checklist__c]                  NVARCHAR (255)  NULL,
    [List_of_Countries__c]                             NVARCHAR (500)  NULL,
    [List_Webinar_Attendees__c]                        NVARCHAR (255)  NULL,
    [Login_Domain__c]                                  NVARCHAR (50)   NULL,
    [Login_ID__c]                                      NVARCHAR (50)   NULL,
    [Login_ID_Source__c]                               NVARCHAR (255)  NULL,
    [Managed_Intelligence_Notes__c]                    NVARCHAR (255)  NULL,
    [Market__c]                                        NVARCHAR (1300) NULL,
    [Name]                                             NVARCHAR (80)   NULL,
    [New_Signature_Date__c]                            DATETIME2 (7)   NULL,
    [Next_Scheduled_Contact__c]                        DATETIME2 (7)   NULL,
    [of_Rejections__c]                                 DECIMAL (18)    NULL,
    [of_Reports_Sold__c]                               DECIMAL (18)    NULL,
    [On_Hold_Stall_Date__c]                            DATETIME2 (7)   NULL,
    [On_Hold_Stall_Reason__c]                          NVARCHAR (255)  NULL,
    [On_Hold_Stall_Status__c]                          NVARCHAR (255)  NULL,
    [On_Hold_Stall_Until__c]                           DATETIME2 (7)   NULL,
    [ONP_Zone__c]                                      NVARCHAR (255)  NULL,
    [Oracle_Instance__c]                               NVARCHAR (10)   NULL,
    [Other__c]                                         NCHAR (18)      NULL,
    [Outtask_Company_Id__c]                            NVARCHAR (50)   NULL,
    [OwnerId]                                          NCHAR (18)      NOT NULL,
    [Partner_E_mail__c]                                NVARCHAR (80)   NULL,
    [Partner_Salesperso__c]                            NVARCHAR (40)   NULL,
    [Password_Policy_Information__c]                   NVARCHAR (255)  NULL,
    [Payment_Cycles_Scheduled_And_Completed__c]        NTEXT           NULL,
    [Percentage_of_Audit__c]                           NVARCHAR (10)   NULL,
    [PM_Assigned__c]                                   DATETIME2 (7)   NULL,
    [PO_Number__c]                                     NVARCHAR (20)   NULL,
    [Policies_Utilization_Count__c]                    NVARCHAR (3)    NULL,
    [Policy_Audit_Review_Call_Scheduled_Date__c]       DATETIME2 (7)   NULL,
    [Primary_Credit_Card__c]                           NVARCHAR (255)  NULL,
    [Probability__c]                                   NVARCHAR (255)  NULL,
    [Probability_Notes__c]                             NVARCHAR (255)  NULL,
    [Process_Call__c]                                  DATETIME2 (7)   NULL,
    [Process_Memento__c]                               NTEXT           NULL,
    [Prod_Site__c]                                     DATETIME2 (7)   NULL,
    [Production_Entity_ID__c]                          NVARCHAR (30)   NULL,
    [Production_Preparation_Method__c]                 NVARCHAR (255)  NULL,
    [Project_Lead_E_mail__c]                           NVARCHAR (60)   NULL,
    [Project_Lead_First_Name__c]                       NVARCHAR (50)   NULL,
    [Project_Lead_Last_Name__c]                        NVARCHAR (50)   NULL,
    [Project_Lead_Phone__c]                            NVARCHAR (50)   NULL,
    [Project_Tax_Type__c]                              NVARCHAR (255)  NULL,
    [Project_Template__c]                              NCHAR (18)      NULL,
    [Project_Template_Type__c]                         NVARCHAR (255)  NULL,
    [Promo_Code__c]                                    NVARCHAR (20)   NULL,
    [Promo_Description__c]                             NVARCHAR (160)  NULL,
    [Promo_End__c]                                     DATETIME2 (7)   NULL,
    [Promo_Start__c]                                   DATETIME2 (7)   NULL,
    [pse__Account__c]                                  NCHAR (18)      NULL,
    [pse__Action_Count_Billing_Eligible_Records__c]    VARCHAR (5)     NULL,
    [pse__Action_Update_Current_Time_Period__c]        VARCHAR (5)     NULL,
    [pse__Allow_Expenses_Without_Assignment__c]        VARCHAR (5)     NULL,
    [pse__Allow_Self_Staffing__c]                      VARCHAR (5)     NULL,
    [pse__Allow_Timecards_Without_Assignment__c]       VARCHAR (5)     NULL,
    [pse__Batch_Sequence__c]                           NVARCHAR (30)   NULL,
    [pse__Billable_Expense_Fee_Flat__c]                DECIMAL (18, 2) NULL,
    [pse__Billable_Expense_Fee_Percentage__c]          DECIMAL (18, 2) NULL,
    [pse__Billable_External_Hours__c]                  DECIMAL (18, 2) NULL,
    [pse__Billable_Internal_Hours__c]                  DECIMAL (18, 2) NULL,
    [pse__Billed__c]                                   DECIMAL (18, 2) NULL,
    [pse__Billing_Eligible_Budgets__c]                 DECIMAL (18)    NULL,
    [pse__Billing_Eligible_Expenses__c]                DECIMAL (18)    NULL,
    [pse__Billing_Eligible_Last_Updated__c]            DATETIME2 (7)   NULL,
    [pse__Billing_Eligible_Milestones__c]              DECIMAL (18)    NULL,
    [pse__Billing_Eligible_Misc_Adjustments__c]        DECIMAL (18)    NULL,
    [pse__Billing_Eligible_Timecard_Splits__c]         DECIMAL (18)    NULL,
    [pse__Billing_Type__c]                             NVARCHAR (255)  NULL,
    [pse__Billings__c]                                 DECIMAL (18, 2) NULL,
    [pse__Bookings__c]                                 DECIMAL (18, 2) NULL,
    [pse__Closed_for_Expense_Entry__c]                 VARCHAR (5)     NULL,
    [pse__Closed_for_Time_Entry__c]                    VARCHAR (5)     NULL,
    [pse__Credited_Non_Billable_Internal_Hours__c]     DECIMAL (18, 2) NULL,
    [pse__Current_Time_Period__c]                      NCHAR (18)      NULL,
    [pse__Current_Time_Period_End_Date__c]             DATETIME2 (7)   NULL,
    [pse__Daily_Timecard_Notes_Required__c]            VARCHAR (5)     NULL,
    [pse__End_Date__c]                                 DATETIME2 (7)   NULL,
    [pse__Exclude_from_Backlog__c]                     VARCHAR (5)     NULL,
    [pse__Exclude_From_Billing__c]                     VARCHAR (5)     NULL,
    [pse__Exclude_from_Project_Planner__c]             VARCHAR (5)     NULL,
    [pse__Excluded_Hours__c]                           DECIMAL (18, 2) NULL,
    [pse__Expense_Budget__c]                           DECIMAL (18, 2) NULL,
    [pse__Expense_Costs__c]                            DECIMAL (18, 2) NULL,
    [pse__Expense_Notes__c]                            NVARCHAR (255)  NULL,
    [pse__External_Costs__c]                           DECIMAL (18, 2) NULL,
    [pse__Group__c]                                    NCHAR (18)      NULL,
    [pse__Hierarchy_Depth__c]                          DECIMAL (18)    NULL,
    [pse__Inactive_Project_Backlog__c]                 DECIMAL (18, 2) NULL,
    [pse__Include_In_Forecasting__c]                   VARCHAR (5)     NULL,
    [pse__Internal_Budget__c]                          DECIMAL (18, 2) NULL,
    [pse__Internal_Costs__c]                           DECIMAL (18, 2) NULL,
    [pse__Invoiced__c]                                 DECIMAL (18, 2) NULL,
    [pse__Is_Active__c]                                VARCHAR (5)     NULL,
    [pse__Is_Billable__c]                              VARCHAR (5)     NULL,
    [pse__Is_Template__c]                              VARCHAR (5)     NULL,
    [pse__Location__c]                                 NTEXT           NULL,
    [pse__Margin__c]                                   DECIMAL (18, 2) NULL,
    [pse__Master_Project__c]                           NCHAR (18)      NULL,
    [pse__Non_Billable_External_Hours__c]              DECIMAL (18, 2) NULL,
    [pse__Non_Billable_Internal_Hours__c]              DECIMAL (18, 2) NULL,
    [pse__Notes__c]                                    NVARCHAR (255)  NULL,
    [pse__Opportunity__c]                              NCHAR (18)      NULL,
    [pse__Opportunity_Owner__c]                        NCHAR (18)      NULL,
    [pse__Other_Costs__c]                              DECIMAL (18, 2) NULL,
    [pse__Parent_Project__c]                           NCHAR (18)      NULL,
    [pse__Pass_Through_Billings__c]                    DECIMAL (18, 2) NULL,
    [pse__Planned_Hours__c]                            DECIMAL (18, 2) NULL,
    [pse__Practice__c]                                 NCHAR (18)      NULL,
    [pse__Pre_Bill_Type__c]                            NVARCHAR (255)  NULL,
    [pse__Pre_Billed__c]                               DECIMAL (18, 2) NULL,
    [pse__Project_ID__c]                               NVARCHAR (30)   NULL,
    [pse__Project_ID_Chain__c]                         NVARCHAR (255)  NULL,
    [pse__Project_Manager__c]                          NCHAR (18)      NULL,
    [pse__Project_Name_Chain__c]                       NVARCHAR (255)  NULL,
    [pse__Project_Phase__c]                            NVARCHAR (255)  NULL,
    [pse__Project_Status__c]                           NVARCHAR (255)  NULL,
    [pse__Project_Status_Notes__c]                     NVARCHAR (255)  NULL,
    [pse__Project_Type__c]                             NVARCHAR (255)  NULL,
    [pse__Region__c]                                   NCHAR (18)      NULL,
    [pse__Revenue__c]                                  DECIMAL (18, 2) NULL,
    [pse__Scheduled_Backlog_Calculated_Date__c]        DATETIME2 (7)   NULL,
    [pse__Scheduled_Backlog_End_Date__c]               DATETIME2 (7)   NULL,
    [pse__Scheduled_Milestone__c]                      DECIMAL (18, 2) NULL,
    [pse__Scheduled_Time__c]                           DECIMAL (18, 2) NULL,
    [pse__Share_with_Project_Manager__c]               VARCHAR (5)     NULL,
    [pse__Share_with_Project_Resources__c]             VARCHAR (5)     NULL,
    [pse__Stage__c]                                    NVARCHAR (255)  NULL,
    [pse__Start_Date__c]                               DATETIME2 (7)   NULL,
    [pse__Tasks_Total_Points__c]                       DECIMAL (18, 2) NULL,
    [pse__Tasks_Total_Points_Complete__c]              DECIMAL (18, 2) NULL,
    [pse__Time_Credited__c]                            VARCHAR (5)     NULL,
    [pse__Time_Excluded__c]                            VARCHAR (5)     NULL,
    [pse__Total_Assigned_Hours__c]                     DECIMAL (18, 2) NULL,
    [pse__Total_Costs__c]                              DECIMAL (18, 2) NULL,
    [pse__Total_Number_of_Tasks__c]                    DECIMAL (18)    NULL,
    [pse__Total_Projected_Revenue_From_Assignments__c] DECIMAL (18, 2) NULL,
    [pse__Unscheduled_Backlog__c]                      DECIMAL (18, 2) NULL,
    [Purge_Simpex_Comments__c]                         NTEXT           NULL,
    [Readiness_Complete__c]                            VARCHAR (5)     NULL,
    [Readiness_Consultant__c]                          NCHAR (18)      NULL,
    [Ready_to_Staff__c]                                VARCHAR (5)     NULL,
    [Receive_Comp_Checklist_Client_Ver_Prod__c]        DATETIME2 (7)   NULL,
    [RecordTypeId]                                     NCHAR (18)      NULL,
    [Referring_Partner__c]                             NVARCHAR (25)   NULL,
    [Reimb_Pay_DR_Feed_Jobs_Scheduled__c]              NVARCHAR (255)  NULL,
    [Rejection_Date__c]                                DATETIME2 (7)   NULL,
    [Request_a_Travel_PM__c]                           NVARCHAR (255)  NULL,
    [Requirements__c]                                  DATETIME2 (7)   NULL,
    [RightNow_ID__c]                                   NVARCHAR (20)   NULL,
    [RN_Project_GUID__c]                               NVARCHAR (20)   NULL,
    [S2S_Received__c]                                  DATETIME2 (7)   NULL,
    [Sales_Channel__c]                                 NVARCHAR (30)   NULL,
    [Sales_to_Service__c]                              NCHAR (18)      NULL,
    [Sales_to_Service_Date__c]                         DATETIME2 (7)   NULL,
    [Schedule_Expense_Service_Training__c]             DATETIME2 (7)   NULL,
    [Schedule_Extract_Training__c]                     DATETIME2 (7)   NULL,
    [Schedule_Imports_Training__c]                     DATETIME2 (7)   NULL,
    [Schedule_Internal_Site_Review__c]                 DATETIME2 (7)   NULL,
    [Schedule_Purge_Simpex_with_TC__c]                 DATETIME2 (7)   NULL,
    [Send_Audit_Form_to_Concur_Audit__c]               DATETIME2 (7)   NULL,
    [Send_Configuration_Confirm_Checklist__c]          DATETIME2 (7)   NULL,
    [Service__c]                                       NVARCHAR (255)  NULL,
    [Service_Administrator__c]                         NCHAR (18)      NULL,
    [Service_Model__c]                                 NVARCHAR (1300) NULL,
    [Setup_Template_Users_Run_User_Sync_Job__c]        NVARCHAR (255)  NULL,
    [Ship_To_Address_Ref__c]                           NVARCHAR (50)   NULL,
    [Site_Name__c]                                     NVARCHAR (80)   NULL,
    [SKU_Template_Mapping_Name__c]                     NVARCHAR (510)  NULL,
    [Sp_Oracle_ID__c]                                  NVARCHAR (20)   NULL,
    [Staffing_Notification_Email_Address__c]           NVARCHAR (80)   NULL,
    [STS_Manager__c]                                   NCHAR (18)      NULL,
    [STS_Project_Phase__c]                             NVARCHAR (255)  NULL,
    [SystemModstamp]                                   DATETIME2 (7)   NOT NULL,
    [T_C_Need_For__c]                                  NVARCHAR (255)  NULL,
    [Technical_Consultant__c]                          NCHAR (18)      NULL,
    [Technical_KT_SAE_Conducted__c]                    DATETIME2 (7)   NULL,
    [Technical_KT_SAE_Scheduled__c]                    DATETIME2 (7)   NULL,
    [Technical_KT_System_Imports_Conducted__c]         DATETIME2 (7)   NULL,
    [Technical_KT_System_Imports_Scheduled__c]         DATETIME2 (7)   NULL,
    [term__c]                                          DECIMAL (18)    NULL,
    [Test_Entity_ID__c]                                NVARCHAR (30)   NULL,
    [Time_Entry_Type__c]                               NVARCHAR (255)  NULL,
    [TMC__c]                                           NVARCHAR (255)  NULL,
    [TMC_info_confirmed__c]                            NVARCHAR (255)  NULL,
    [Tools_Call__c]                                    DATETIME2 (7)   NULL,
    [Topics_Expense_Administration_Training__c]        NTEXT           NULL,
    [Total_of_Employees__c]                            DECIMAL (18)    NULL,
    [Training__c]                                      DATETIME2 (7)   NULL,
    [Training_Portal_Link__c]                          NVARCHAR (255)  NULL,
    [Training_Portal_Utilization__c]                   NVARCHAR (255)  NULL,
    [Transition_to_CS__c]                              DATETIME2 (7)   NULL,
    [Travel_Concur_Reservation_Call__c]                DATETIME2 (7)   NULL,
    [Travel_Details__c]                                NVARCHAR (255)  NULL,
    [Travel_Site_Configured__c]                        DATETIME2 (7)   NULL,
    [Travel_Training_Call__c]                          DATETIME2 (7)   NULL,
    [Treasury_Manager_Contact_1__c]                    NCHAR (18)      NULL,
    [Treasury_Manager_Contact_2__c]                    NCHAR (18)      NULL,
    [Unified_Pricing__c]                               VARCHAR (5)     NULL,
    [update_manual__c]                                 DECIMAL (18)    NULL,
    [Update_Production_Site_Release_Date__c]           DATETIME2 (7)   NULL,
    [update_SMB__c]                                    DECIMAL (18)    NULL,
    [Validation_Checklist_Returned__c]                 DATETIME2 (7)   NULL,
    [VAT_Utilization__c]                               NVARCHAR (255)  NULL,
    [VAT_Utilization_Countries__c]                     NTEXT           NULL,
    [Verify_Receipt_of_Config_Checklist__c]            DATETIME2 (7)   NULL,
    [Welcome_Email__c]                                 DATETIME2 (7)   NULL,
    [Welcome_Letter_Sent__c]                           DATETIME2 (7)   NULL,
    [Workflows_Utilization_Count__c]                   NVARCHAR (3)    NULL,
    [Publish_to_Metranet__c]                           VARCHAR (5)     NULL,
    [MN_Subscription_ID__c]                            NVARCHAR (30)   NULL,
    [Base_Trans_Billing_Cycle__c]                      DECIMAL (18)    NULL,
    [Fair_Value_Setup_Fee__c]                          DECIMAL (18, 2) NULL,
    [IC_Welcome_Letter_Sent__c]                        DATETIME        NULL,
    [Opportunity_Type__c]                              NVARCHAR (1300) NULL,
    [Sales_Segment__c]                                 NVARCHAR (1300) NULL,
    [Service_Account_Team__c]                          NCHAR (18)      NULL,
    [Customer_Enablement_Specialist__c]                NCHAR (18)      NULL,
    [Opportunity_Product_Id__c]                        NVARCHAR (18)   NULL,
    [Customer_Success_Partner__c]                      NCHAR (18)      NULL,
    [Implementation_Partner_Lookup__c]                 NCHAR (18)      NULL,
    [Partner_Engagement_Type__c]                       NVARCHAR (255)  NULL,
    [Project_Setup_Complete_Date__c]                   DATETIME        NULL,
    [Standard_Edition_Candidate__c]                    NVARCHAR (255)  NULL,
    CONSTRAINT [PK_pse__proj__c_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);

