CREATE TABLE [dbo].[SKU_Template_Mapping__c] (
    [Active__c]                            VARCHAR (5)    NULL,
    [Blocks_Handling__c]                   NVARCHAR (255) NULL,
    [Business_Unit__c]                     NVARCHAR (255) NULL,
    [Core_Service_Transitioned__c]         VARCHAR (5)    NULL,
    [CreatedById]                          NCHAR (18)     NULL,
    [CreatedDate]                          DATETIME2 (7)  NOT NULL,
    [CurrencyIsoCode]                      NVARCHAR (3)   NULL,
    [Education_Government__c]              NVARCHAR (255) NULL,
    [Employee_Count_Lower_Limit__c]        DECIMAL (18)   NULL,
    [Employee_Count_Upper_Limit__c]        DECIMAL (18)   NULL,
    [Id]                                   NCHAR (18)     NOT NULL,
    [Implementation_Method__c]             NVARCHAR (255) NULL,
    [Invoice_Ordered__c]                   NVARCHAR (255) NULL,
    [IsDeleted]                            VARCHAR (5)    NOT NULL,
    [LastModifiedById]                     NCHAR (18)     NULL,
    [LastModifiedDate]                     DATETIME2 (7)  NOT NULL,
    [Market__c]                            NVARCHAR (255) NULL,
    [Marketing_Name_Text__c]               NVARCHAR (255) NULL,
    [Name]                                 NVARCHAR (80)  NULL,
    [Name__c]                              NVARCHAR (60)  NULL,
    [Notes__c]                             NVARCHAR (255) NULL,
    [OwnerId]                              NCHAR (18)     NOT NULL,
    [Practice_2__c]                        NVARCHAR (40)  NULL,
    [Practice__c]                          NVARCHAR (40)  NULL,
    [Project_2_Overriding_Service_Name__c] NVARCHAR (60)  NULL,
    [Project_Template_2__c]                NCHAR (18)     NULL,
    [Project_Template__c]                  NCHAR (18)     NULL,
    [Region__c]                            NVARCHAR (255) NULL,
    [Segment__c]                           NVARCHAR (255) NULL,
    [Service_Short_Code__c]                NVARCHAR (20)  NULL,
    [SKU__c]                               NVARCHAR (255) NULL,
    [SystemModstamp]                       DATETIME2 (7)  NOT NULL,
    CONSTRAINT [PK_SKU_Template_Mapping__c_Id] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100)
);

