CREATE TABLE [dbo].[user] (
    [AboutMe]                                            NVARCHAR (1000) NULL,
    [AccountId]                                          NCHAR (18)      NULL,
    [Alias]                                              NVARCHAR (8)    NOT NULL,
    [Assignment_Group_Active__c]                         VARCHAR (5)     NULL,
    [BigMachines__Access_Type__c]                        NVARCHAR (255)  NULL,
    [BigMachines__Association_to_Organization__c]        NVARCHAR (255)  NULL,
    [BigMachines__Bulk_Synchronization__c]               VARCHAR (5)     NULL,
    [BigMachines__Currency_Preference__c]                NVARCHAR (255)  NULL,
    [BigMachines__Date_Time_Format__c]                   NVARCHAR (255)  NULL,
    [BigMachines__Delegated_Approver__c]                 NCHAR (18)      NULL,
    [BigMachines__Language_Preference__c]                NVARCHAR (255)  NULL,
    [BigMachines__Number_Format__c]                      NVARCHAR (255)  NULL,
    [BigMachines__Provisioned__c]                        VARCHAR (5)     NULL,
    [BigMachines__Time_Zone__c]                          NVARCHAR (255)  NULL,
    [BigMachines__Unit_System__c]                        NVARCHAR (255)  NULL,
    [BigMachines__User_Groups__c]                        NTEXT           NULL,
    [Breeze_Representative__c]                           VARCHAR (5)     NULL,
    [Breeze_Team__c]                                     NVARCHAR (255)  NULL,
    [CallCenterId]                                       NCHAR (18)      NULL,
    [CAP_Duration_Minutes__c]                            NVARCHAR (100)  NULL,
    [CAP_Reviews_left_to_Nominate__c]                    DECIMAL (18)    NULL,
    [CAP_Reviews_Nominated__c]                           DECIMAL (18)    NULL,
    [CAP_Reviews_Required__c]                            DECIMAL (18)    NULL,
    [City]                                               NVARCHAR (40)   NULL,
    [CommunityNickname]                                  NVARCHAR (40)   NOT NULL,
    [CompanyName]                                        NVARCHAR (80)   NULL,
    [ContactId]                                          NCHAR (18)      NULL,
    [Country]                                            NVARCHAR (80)   NULL,
    [CreatedById]                                        NCHAR (18)      NULL,
    [CreatedDate]                                        DATETIME2 (7)   NOT NULL,
    [CurrencyIsoCode]                                    NVARCHAR (3)    NOT NULL,
    [DefaultCurrencyIsoCode]                             NVARCHAR (3)    NULL,
    [DefaultGroupNotificationFrequency]                  NVARCHAR (40)   NOT NULL,
    [DelegatedApproverId]                                NCHAR (18)      NULL,
    [Department]                                         NVARCHAR (80)   NULL,
    [DigestFrequency]                                    NVARCHAR (40)   NOT NULL,
    [Division]                                           NVARCHAR (80)   NULL,
    [dsfs__DSProSFUsername__c]                           NVARCHAR (50)   NULL,
    [Email]                                              NVARCHAR (128)  NOT NULL,
    [EmailEncodingKey]                                   NVARCHAR (40)   NOT NULL,
    [EmployeeNumber]                                     NVARCHAR (20)   NULL,
    [Expense__c]                                         NVARCHAR (5)    NULL,
    [Extension]                                          NVARCHAR (40)   NULL,
    [Fax]                                                NVARCHAR (40)   NULL,
    [FederationIdentifier]                               NVARCHAR (512)  NULL,
    [FirstName]                                          NVARCHAR (40)   NULL,
    [ForecastEnabled]                                    VARCHAR (5)     NOT NULL,
    [FullPhotoUrl]                                       NVARCHAR (1024) NULL,
    [Hire_Rehire_Date__c]                                DATETIME2 (7)   NULL,
    [HR_Employee_ID__c]                                  NVARCHAR (20)   NULL,
    [Id]                                                 NCHAR (18)      NOT NULL,
    [IsActive]                                           VARCHAR (5)     NOT NULL,
    [IsPortalEnabled]                                    VARCHAR (5)     NOT NULL,
    [IsPortalSelfRegistered]                             VARCHAR (5)     NOT NULL,
    [JigsawImportLimitOverride]                          INT             NULL,
    [LanguageLocaleKey]                                  NVARCHAR (40)   NOT NULL,
    [LastLoginDate]                                      DATETIME2 (7)   NULL,
    [LastModifiedById]                                   NCHAR (18)      NULL,
    [LastModifiedDate]                                   DATETIME2 (7)   NOT NULL,
    [LastName]                                           NVARCHAR (80)   NOT NULL,
    [LastPasswordChangeDate]                             DATETIME2 (7)   NULL,
    [LocaleSidKey]                                       NVARCHAR (40)   NOT NULL,
    [Manager__c]                                         NVARCHAR (1300) NULL,
    [ManagerId]                                          NCHAR (18)      NULL,
    [MobilePhone]                                        NVARCHAR (40)   NULL,
    [Name]                                               NVARCHAR (121)  NOT NULL,
    [Notes_and_Comments__c]                              NTEXT           NULL,
    [OfflinePdaTrialExpirationDate]                      DATETIME2 (7)   NULL,
    [OfflineTrialExpirationDate]                         DATETIME2 (7)   NULL,
    [Owner_Division__c]                                  NVARCHAR (255)  NULL,
    [Owner_Record_Business_Unit__c]                      NVARCHAR (255)  NULL,
    [Owner_Record_Market__c]                             NVARCHAR (255)  NULL,
    [Owner_Record_Region__c]                             NVARCHAR (255)  NULL,
    [Owner_Record_Revenue_Group__c]                      NVARCHAR (255)  NULL,
    [Owner_Record_Segment__c]                            NVARCHAR (255)  NULL,
    [Owner_Team__c]                                      NVARCHAR (255)  NULL,
    [Owner_Theater__c]                                   NVARCHAR (255)  NULL,
    [Phone]                                              NVARCHAR (40)   NULL,
    [PortalRole]                                         NVARCHAR (40)   NULL,
    [PostalCode]                                         NVARCHAR (20)   NULL,
    [ProductType__c]                                     NVARCHAR (10)   NULL,
    [ProfileId]                                          NCHAR (18)      NOT NULL,
    [ReceivesAdminInfoEmails]                            VARCHAR (5)     NOT NULL,
    [ReceivesInfoEmails]                                 VARCHAR (5)     NOT NULL,
    [RN_Account_ID__c]                                   NVARCHAR (100)  NULL,
    [SmallPhotoUrl]                                      NVARCHAR (1024) NULL,
    [SOSAO__Allow_2nd_Owner_Change__c]                   VARCHAR (5)     NULL,
    [SSO_Profile_Debug__c]                               NVARCHAR (255)  NULL,
    [State]                                              NVARCHAR (80)   NULL,
    [Street]                                             NVARCHAR (255)  NULL,
    [SystemModstamp]                                     DATETIME2 (7)   NOT NULL,
    [Termination_Date__c]                                DATETIME2 (7)   NULL,
    [TimeZoneSidKey]                                     NVARCHAR (40)   NOT NULL,
    [Title]                                              NVARCHAR (80)   NULL,
    [TP_Duration__c]                                     NVARCHAR (100)  NULL,
    [Travel__c]                                          NVARCHAR (5)    NULL,
    [Username]                                           NVARCHAR (80)   NOT NULL,
    [UserPermissionsAvantgoUser]                         VARCHAR (5)     NOT NULL,
    [UserPermissionsCallCenterAutoLogin]                 VARCHAR (5)     NOT NULL,
    [UserPermissionsChatterAnswersUser]                  VARCHAR (5)     NOT NULL,
    [UserPermissionsInteractionUser]                     VARCHAR (5)     NOT NULL,
    [UserPermissionsJigsawProspectingUser]               VARCHAR (5)     NOT NULL,
    [UserPermissionsKnowledgeUser]                       VARCHAR (5)     NOT NULL,
    [UserPermissionsLiveAgentUser]                       VARCHAR (5)     NOT NULL,
    [UserPermissionsMarketingUser]                       VARCHAR (5)     NOT NULL,
    [UserPermissionsMobileUser]                          VARCHAR (5)     NOT NULL,
    [UserPermissionsOfflineUser]                         VARCHAR (5)     NOT NULL,
    [UserPermissionsSFContentUser]                       VARCHAR (5)     NOT NULL,
    [UserPermissionsSupportUser]                         VARCHAR (5)     NOT NULL,
    [UserPreferencesActivityRemindersPopup]              VARCHAR (5)     NOT NULL,
    [UserPreferencesApexPagesDeveloperMode]              VARCHAR (5)     NOT NULL,
    [UserPreferencesContentEmailAsAndWhen]               VARCHAR (5)     NOT NULL,
    [UserPreferencesContentNoEmail]                      VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableAllFeedsEmail]                VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableBookmarkEmail]                VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableChangeCommentEmail]           VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableFileShareNotificationsForApi] VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableFollowersEmail]               VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableLaterCommentEmail]            VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableLikeEmail]                    VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableMentionsPostEmail]            VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableMessageEmail]                 VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableProfilePostEmail]             VARCHAR (5)     NOT NULL,
    [UserPreferencesDisableSharePostEmail]               VARCHAR (5)     NOT NULL,
    [UserPreferencesDisCommentAfterLikeEmail]            VARCHAR (5)     NOT NULL,
    [UserPreferencesDisMentionsCommentEmail]             VARCHAR (5)     NOT NULL,
    [UserPreferencesDisProfPostCommentEmail]             VARCHAR (5)     NOT NULL,
    [UserPreferencesEnableAutoSubForFeeds]               VARCHAR (5)     NOT NULL,
    [UserPreferencesEventRemindersCheckboxDefault]       VARCHAR (5)     NOT NULL,
    [UserPreferencesHideCSNDesktopTask]                  VARCHAR (5)     NOT NULL,
    [UserPreferencesHideCSNGetChatterMobileTask]         VARCHAR (5)     NOT NULL,
    [UserPreferencesJigsawListUser]                      VARCHAR (5)     NOT NULL,
    [UserPreferencesReminderSoundOff]                    VARCHAR (5)     NOT NULL,
    [UserPreferencesShowCityToExternalUsers]             VARCHAR (5)     NOT NULL,
    [UserPreferencesShowCountryToExternalUsers]          VARCHAR (5)     NOT NULL,
    [UserPreferencesShowEmailToExternalUsers]            VARCHAR (5)     NOT NULL,
    [UserPreferencesShowFaxToExternalUsers]              VARCHAR (5)     NOT NULL,
    [UserPreferencesShowManagerToExternalUsers]          VARCHAR (5)     NOT NULL,
    [UserPreferencesShowMobilePhoneToExternalUsers]      VARCHAR (5)     NOT NULL,
    [UserPreferencesShowPostalCodeToExternalUsers]       VARCHAR (5)     NOT NULL,
    [UserPreferencesShowStateToExternalUsers]            VARCHAR (5)     NOT NULL,
    [UserPreferencesShowStreetAddressToExternalUsers]    VARCHAR (5)     NOT NULL,
    [UserPreferencesShowTitleToExternalUsers]            VARCHAR (5)     NOT NULL,
    [UserPreferencesShowWorkPhoneToExternalUsers]        VARCHAR (5)     NOT NULL,
    [UserPreferencesTaskRemindersCheckboxDefault]        VARCHAR (5)     NOT NULL,
    [UserRoleId]                                         NCHAR (18)      NULL,
    [UserType]                                           NVARCHAR (40)   NULL,
    [BigMachines__Login__c]                              NVARCHAR (1300) NULL,
    [BigMachines__Partner_Organization__c]               NVARCHAR (1300) NULL,
    [Owner_Record_Phone_c__c]                            NVARCHAR (1300) NULL,
    [User_ID__c]                                         NVARCHAR (1300) NULL,
    [User_License_Type__c]                               NVARCHAR (1300) NULL,
    [X2nd_Level_Manager__c]                              NVARCHAR (1300) NULL,
    [X3rd_Level_Manager__c]                              NVARCHAR (1300) NULL,
    [X4th_Level_Manager__c]                              NVARCHAR (1300) NULL,
    [X5th_Level_Manager__c]                              NVARCHAR (1300) NULL,
    [X6th_Level_Manager__c]                              NVARCHAR (1300) NULL,
    [X7th_Level_Manager__c]                              NVARCHAR (1300) NULL,
    [X8th_Level_Manager__c]                              NVARCHAR (1300) NULL,
    [SAP_Employee_ID__c]                                 NVARCHAR (10)   NULL,
    [Title_Acronym__c]                                   NVARCHAR (255)  NULL,
    [Gainsight_License_Holder__c]                        NVARCHAR (255)  NULL,
    [Owner_SAP_Region__c]                                NVARCHAR (255)  NULL,
    [Next_FY_Owner_SAP_Region__c]                        NVARCHAR (255)  NULL,
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC)
);

