CREATE TABLE [CONCUR\MinalC].[Table_Outtask_Analysis_SFDC_Accts_cleanUp] (
    [MatchAnalysis]                     VARCHAR (20)   NULL,
    [MatchAnalysisComments]             VARCHAR (1000) NULL,
    [MetranetCustomerStatus]            VARCHAR (8)    NULL,
    [OUTTASK_company_id]                FLOAT (53)     NULL,
    [OUTTASK_company_name]              NVARCHAR (255) NULL,
    [OUTTASK_SFDC_18_digitID]           VARCHAR (30)   NULL,
    [OUTTASK_city]                      NVARCHAR (255) NULL,
    [OUTTASK_Entity_id]                 NVARCHAR (255) NULL,
    [SFDC_Account_Id]                   NCHAR (18)     NULL,
    [SFDC_Account_Name]                 NVARCHAR (255) NULL,
    [Entity_ID__c]                      NVARCHAR (45)  NULL,
    [HMC_Entity__c]                     NVARCHAR (80)  NULL,
    [Outtask_ID__c]                     NVARCHAR (8)   NULL,
    [NameMatchValue]                    INT            NULL,
    [Type]                              NVARCHAR (40)  NULL,
    [business_login]                    NVARCHAR (255) NULL,
    [Billing_Country__c]                NVARCHAR (255) NULL,
    [Billing_City__c]                   NVARCHAR (80)  NULL,
    [DunsNumber]                        VARCHAR (9)    NULL,
    [Global_Ultimate_Duns_Number__c]    NVARCHAR (10)  NULL,
    [SAP_Planning_Entity_Account_ID__c] NVARCHAR (55)  NULL,
    [SAP_Account_ID__c]                 NVARCHAR (15)  NULL,
    [Opportunities__c]                  DECIMAL (18)   NULL,
    [Opportunities_Won__c]              DECIMAL (18)   NULL,
    [SAP_Business_Partner_Id__c]        NVARCHAR (10)  NULL,
    [Site]                              NVARCHAR (80)  NULL,
    [Travel_Org_Type__c]                NVARCHAR (255) NULL,
    [rrpu__Alert_Message__c]            NVARCHAR (255) NULL,
    [Travel Config Id]                  NVARCHAR (255) NULL,
    [Travel Config Name]                NVARCHAR (255) NULL,
    [Opportunity Name]                  NVARCHAR (255) NULL,
    [IndirectAccount_ID]                NVARCHAR (255) NULL,
    [SFDC_IndirectAccount_Name]         NVARCHAR (255) NULL,
    [SFDC_IndirectAccount_CompanyId]    NVARCHAR (255) NULL,
    [SFDC_IndirectAccount_AgencyId]     NVARCHAR (255) NULL,
    [SFDC_IndirectAccount_TravelAgency] NVARCHAR (255) NULL,
    [SFDC_TravelAgencyAccount_ID]       NVARCHAR (255) NULL,
    [SFDC_IndirectAccount_18ID]         VARCHAR (18)   NULL
);

