CREATE TABLE [CONCUR\MinalC].[Table_Outtask_NameMatch4_WONOpp_BillingAcct_ServiceAcctMatch] (
    [company_id]                        NVARCHAR (8)   NULL,
    [SAMatch_company_id]                NVARCHAR (8)   NULL,
    [MatchSecBus_CBMasterAcct]          CHAR (1)       NULL,
    [SAMatch_business_id_acc]           NVARCHAR (128) NULL,
    [SAMatch_secondary_business_id_acc] NVARCHAR (128) NULL,
    [SAMatch_MN_Service_acct_id]        NVARCHAR (128) NULL,
    [SAMatch_MN_Bus_Login]              NVARCHAR (255) NULL,
    [SAMatch_MN_Sec_Bus_Login]          NVARCHAR (255) NULL,
    [SAMatch_SFDCName]                  NVARCHAR (255) NULL,
    [company_name]                      NVARCHAR (255) NULL,
    [SAMatch_SFDC_WONOpportunities]     DECIMAL (18)   NULL,
    [SAMatch_NameMatchValue]            INT            NULL,
    [SAMatch_FreeTrialEntityID]         NVARCHAR (45)  NULL,
    [SAMatch_HMCEntityID]               NVARCHAR (80)  NULL,
    [SAMatch_OuttaskId]                 NVARCHAR (8)   NULL,
    [SAMatch_SFDC_AcctType]             NVARCHAR (40)  NULL,
    [SAMatch_SFDC_BillingCountry]       NVARCHAR (255) NULL,
    [SAMatch_SAPAccountID]              NVARCHAR (15)  NULL,
    [SAMatch_PlanningEntityAccountID]   NVARCHAR (55)  NULL,
    [SAMatch_GlobalUltimateDunsNumber]  NVARCHAR (10)  NULL,
    [SAMatch_SFDCsite]                  NVARCHAR (80)  NULL,
    [SAMatch_SFDCWebsite]               NVARCHAR (255) NULL,
    [SAMatch_SFDCTravel_org]            NVARCHAR (255) NULL,
    [address]                           NVARCHAR (255) NULL,
    [city]                              NVARCHAR (255) NULL,
    [state]                             NVARCHAR (255) NULL,
    [zip_code]                          NVARCHAR (255) NULL,
    [salesforce_account_id]             NVARCHAR (255) NULL,
    [entity_id]                         NVARCHAR (255) NULL,
    [salesforce_account_18digitid]      NVARCHAR (255) NULL
);

