CREATE TABLE [CONCUR\MinalC].[Table_Outtask_NameMatch4_WONOpp_BillingAcct_MatchSecBusiness] (
    [company_id]                          NVARCHAR (8)   NULL,
    [company_name]                        NVARCHAR (255) NULL,
    [address]                             NVARCHAR (255) NULL,
    [city]                                NVARCHAR (255) NULL,
    [state]                               NVARCHAR (255) NULL,
    [zip_code]                            NVARCHAR (255) NULL,
    [salesforce_account_id]               NVARCHAR (255) NULL,
    [entity_id]                           NVARCHAR (255) NULL,
    [salesforce_account_18digitid]        NVARCHAR (255) NULL,
    [MatchSecBus_CB_SFAID]                NVARCHAR (255) NULL,
    [MatchSecBus_CBMasterAcct]            CHAR (1)       NULL,
    [MatchSecBus_SFDCName]                NVARCHAR (255) NULL,
    [MatchSecBus_NameMatchValue]          INT            NULL,
    [MatchSecBus_WONOpportunities]        DECIMAL (18)   NULL,
    [MatchSecBus_CBCompanyID]             NVARCHAR (255) NULL,
    [MatchSecBus_FreeTrialEntityID]       NVARCHAR (45)  NULL,
    [MatchSecBus_HMCEntityID]             NVARCHAR (80)  NULL,
    [MatchSecBus_OuttaskID]               NVARCHAR (8)   NULL,
    [MatchSecBus_SFDC_AcctType]           NVARCHAR (40)  NULL,
    [MatchSecBus_SFDC_BillingCountry]     NVARCHAR (255) NULL,
    [MatchSecBus_SFDC_BillingCity]        NVARCHAR (80)  NULL,
    [MatchSecBus_SFDC_DUNS]               VARCHAR (9)    NULL,
    [MatchSecBus_SFDC_TotalOpportunities] DECIMAL (18)   NULL,
    [MatchSecBus_SFDCsite]                NVARCHAR (80)  NULL,
    [MatchSecBus_SFDCWebsite]             NVARCHAR (255) NULL,
    [MatchSecBus_SFDCTravel_org]          NVARCHAR (255) NULL
);

