CREATE TABLE [dbo].[dm_pc_xref_minal] (
    [Provider Contract]                    FLOAT (53)     NULL,
    [Contract Item]                        FLOAT (53)     NULL,
    [Cont#Account]                         FLOAT (53)     NULL,
    [Business Partner]                     FLOAT (53)     NULL,
    [Reference ID]                         NVARCHAR (255) NULL,
    [Created On]                           DATETIME       NULL,
    [Time]                                 DATETIME       NULL,
    [Created By]                           NVARCHAR (255) NULL,
    [Chngd On]                             DATETIME       NULL,
    [Changed At]                           DATETIME       NULL,
    [Changed by]                           NVARCHAR (255) NULL,
    [Contract Item ID]                     NVARCHAR (255) NULL,
    [Valid From]                           DATETIME       NULL,
    [Local Time]                           FLOAT (53)     NULL,
    [Valid To]                             DATETIME       NULL,
    [Local Time1]                          FLOAT (53)     NULL,
    [Reversal]                             DATETIME       NULL,
    [Higher-Level Prov#Ctr# Item ID]       FLOAT (53)     NULL,
    [Contract Item Text]                   NVARCHAR (255) NULL,
    [Prepaid Account]                      NVARCHAR (255) NULL,
    [SOrg#]                                FLOAT (53)     NULL,
    [DChl]                                 FLOAT (53)     NULL,
    [Dv]                                   NVARCHAR (255) NULL,
    [SlsArea1]                             NVARCHAR (255) NULL,
    [SlsArea2]                             NVARCHAR (255) NULL,
    [CoCd]                                 FLOAT (53)     NULL,
    [Profit Ctr]                           FLOAT (53)     NULL,
    [Segment]                              NVARCHAR (255) NULL,
    [StdDivis#]                            FLOAT (53)     NULL,
    [BusA]                                 NVARCHAR (255) NULL,
    [Product]                              FLOAT (53)     NULL,
    [Billing Cycle]                        NVARCHAR (255) NULL,
    [Specified Day]                        FLOAT (53)     NULL,
    [Original Period Start]                DATETIME       NULL,
    [Valid To1]                            DATETIME       NULL,
    [Schedlng]                             NVARCHAR (255) NULL,
    [Group of IDs]                         FLOAT (53)     NULL,
    [Master Agreement]                     NVARCHAR (255) NULL,
    [Custom Product or Product Range]      NVARCHAR (255) NULL,
    [Recipient of Service]                 FLOAT (53)     NULL,
    [Partner Settlement Rule]              NVARCHAR (255) NULL,
    [Sharing Contract]                     NVARCHAR (255) NULL,
    [Order]                                NVARCHAR (255) NULL,
    [WBS Element]                          FLOAT (53)     NULL,
    [Sold-To Party]                        NVARCHAR (255) NULL,
    [Invoice Recipient]                    NVARCHAR (255) NULL,
    [PayT]                                 NVARCHAR (255) NULL,
    [AInd]                                 NVARCHAR (255) NULL,
    [Mandate Reference]                    NVARCHAR (255) NULL,
    [ID]                                   NVARCHAR (255) NULL,
    [Rating Area]                          NVARCHAR (255) NULL,
    [Relevant for Revenue Accounting]      NVARCHAR (255) NULL,
    [Reference Type]                       NVARCHAR (255) NULL,
    [Product ID of the Sales Package]      NVARCHAR (255) NULL,
    [Transaction Price]                    FLOAT (53)     NULL,
    [Crcy]                                 NVARCHAR (255) NULL,
    [Time Unit for Recurrence Period]      NVARCHAR (255) NULL,
    [Length of Recurrence Period]          FLOAT (53)     NULL,
    [Standalone Selling Price]             FLOAT (53)     NULL,
    [Crcy1]                                NVARCHAR (255) NULL,
    [Time Unit for Recurrence Period1]     NVARCHAR (255) NULL,
    [Length of Recurrence Period1]         FLOAT (53)     NULL,
    [End of Contract Duration]             DATETIME       NULL,
    [Local Time2]                          FLOAT (53)     NULL,
    [Change Reason]                        NVARCHAR (255) NULL,
    [ID1]                                  NVARCHAR (255) NULL,
    [Migration Package ID]                 NVARCHAR (255) NULL,
    [Total Amount]                         FLOAT (53)     NULL,
    [Total Amount1]                        FLOAT (53)     NULL,
    [ADRSR]                                FLOAT (53)     NULL,
    [Jurisdict# code]                      FLOAT (53)     NULL,
    [Delivery Country]                     NVARCHAR (255) NULL,
    [Concur: Order Line ID]                NVARCHAR (255) NULL,
    [Concur: Service Account Name]         NVARCHAR (255) NULL,
    [Fulfillment type]                     FLOAT (53)     NULL,
    [Pre-prod flag]                        NVARCHAR (255) NULL,
    [Subscription ID]                      FLOAT (53)     NULL,
    [Concur: Item Type]                    NVARCHAR (255) NULL,
    [Concur: Rate Schedule ID]             FLOAT (53)     NULL,
    [Concur: Tier Level per Billing Cycle] FLOAT (53)     NULL,
    [Concur: Tier Level Monthly]           FLOAT (53)     NULL,
    [Concur: Move End Date]                NVARCHAR (255) NULL,
    [Concur: Move Start Date]              NVARCHAR (255) NULL,
    [Concur: Move Duration]                NVARCHAR (255) NULL,
    [Bundle ID]                            NVARCHAR (255) NULL,
    [Bundle Master]                        NVARCHAR (255) NULL,
    [Bundle roll-up]                       NVARCHAR (255) NULL,
    [Data Origin Type]                     NVARCHAR (255) NULL,
    [Cancellation flag]                    NVARCHAR (255) NULL
);

