CREATE TABLE [dbo].[rpt_v_invoice] (
    [id_invoice_export]       BIGINT           IDENTITY (1, 1) NOT NULL,
    [ili_dt_crt]              DATETIME         NOT NULL,
    [id_usage_interval]       INT              NOT NULL,
    [bill_group_id]           INT              NOT NULL,
    [id_acc]                  INT              NOT NULL,
    [payee_id_acc]            INT              NOT NULL,
    [orar_shipto_id_acc]      INT              NOT NULL,
    [invoice_number]          INT              NOT NULL,
    [invoice_string]          VARCHAR (255)    NOT NULL,
    [invoice_date]            DATETIME         NOT NULL,
    [interval_start_date]     DATETIME         NOT NULL,
    [interval_end_date]       DATETIME         NOT NULL,
    [invoice_line_number]     INT              NOT NULL,
    [context]                 VARCHAR (255)    NOT NULL,
    [line_type]               VARCHAR (255)    NOT NULL,
    [bill_nm_login]           VARCHAR (255)    NOT NULL,
    [ship_nm_login]           VARCHAR (255)    NOT NULL,
    [pi_description_external] VARCHAR (255)    NOT NULL,
    [pi_description]          VARCHAR (255)    NOT NULL,
    [currency_code]           VARCHAR (3)      NOT NULL,
    [amount]                  NUMERIC (22, 10) NULL,
    [revrec_amount]           NUMERIC (22, 10) NULL,
    [payment_terms]           VARCHAR (255)    NULL,
    [org_id]                  VARCHAR (255)    NOT NULL,
    [gst_code]                VARCHAR (255)    NULL,
    [purchase_order]          VARCHAR (255)    NULL,
    [sku]                     VARCHAR (255)    NULL,
    [invoice_uom]             VARCHAR (2)      NULL,
    [uom_name]                VARCHAR (255)    NULL,
    [tax_exempt_flag]         INT              NOT NULL,
    [tax_exempt_number]       VARCHAR (255)    NULL,
    [trans_count]             INT              NULL,
    [bundle_id_sub]           INT              NULL,
    [bundle_name]             VARCHAR (255)    NULL,
    [id_sub]                  INT              NULL,
    [is_master]               VARCHAR (3)      NULL,
    [roll_up]                 CHAR (1)         NULL,
    [concur_item_type]        INT              NULL,
    [id_po]                   INT              NULL,
    [id_pi_template]          INT              NULL,
    [id_pi_instance]          INT              NULL,
    [revrec_rate_tier]        INT              NULL,
    [revrec_rate]             NUMERIC (22, 10) NULL,
    [billed_rate]             NUMERIC (22, 10) NULL,
    [internal_comments]       VARCHAR (250)    NULL,
    [quantity]                INT              NULL,
    [transaction_type]        VARCHAR (50)     NULL,
    [is_revrec]               INT              NULL,
    [acc_charge_freq]         INT              NULL,
    [charge_start_date]       DATETIME         NULL,
    [charge_end_date]         DATETIME         NULL,
    [prod_category]           INT              NULL,
    [origsku]                 VARCHAR (255)    NULL,
    [inoutsku]                VARCHAR (255)    NULL,
    [rule_duration]           INT              NULL,
    [forcemonthly]            INT              NULL,
    [tax_amount]              NUMERIC (22, 10) NULL
);


GO
CREATE NONCLUSTERED INDEX [rpt_v_invoice_n1]
    ON [dbo].[rpt_v_invoice]([id_pi_instance] ASC);

