CREATE TABLE [dbo].[t_cnqr_provider_con_line_map_UAT03] (
    [id]                             BIGINT         NOT NULL,
    [id_sub]                         INT            NULL,
    [id_po_instance]                 INT            NULL,
    [id_pi_instance]                 INT            NULL,
    [id_sched]                       INT            NULL,
    [out_of_term_line]               BIT            NULL,
    [concur_line_item_id]            NVARCHAR (60)  NULL,
    [provider_con_id]                NVARCHAR (40)  NULL,
    [provider_con_line_num]          NVARCHAR (50)  NULL,
    [provider_con_line_id]           NVARCHAR (100) NULL,
    [business_partner_id]            NVARCHAR (40)  NULL,
    [contract_account_id]            NVARCHAR (40)  NULL,
    [concur_order_id]                NVARCHAR (40)  NULL,
    [date_created]                   DATETIME       NULL,
    [billing_account_id]             INT            NULL,
    [service_account_id]             BIGINT         NULL,
    [material_id]                    NVARCHAR (40)  NULL,
    [mn_customer_id]                 NVARCHAR (40)  NULL,
    [Concur_Line_Item_ID_Lookup]     NVARCHAR (60)  NULL,
    [n_order]                        INT            NULL,
    [OverrideValidFromDate]          DATETIME       NULL,
    [S4ValidFrom]                    DATETIME       NULL,
    [S4ValidTo]                      DATETIME       NULL,
    [S4EndOfDuration]                DATETIME       NULL,
    [S4MoveEndFlag]                  BIT            NULL,
    [S4MoveStartFlag]                BIT            NULL,
    [S4MoveDurationFlag]             BIT            NULL,
    [date_updated]                   DATETIME       NULL,
    [manual_creation]                BIT            NOT NULL,
    [PreProductionFlag]              VARCHAR (1)    NULL,
    [S4CanceledFlag]                 BIT            NULL,
    [subsidiary_business_partner_id] NVARCHAR (40)  NULL,
    [S4BillingCycle]                 NVARCHAR (20)  NULL,
    [S4Currency]                     NVARCHAR (3)   NULL
);

